[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pentacles_solana = "7MPHZUmxFcLQiqmhnfvgVtTsMRu7jHdmGzjZbKbECE5R"

[programs.localnet]
pentacles_solana = "7MPHZUmxFcLQiqmhnfvgVtTsMRu7jHdmGzjZbKbECE5R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test"
