// Constellation liquidity pools — generated by scripts/make_constellations.py
// DO NOT EDIT BY HAND; re-run the script instead.
//
// Each real constellation is a constant-product AMM pool over a pair of ESMS
// elements (0=Spirit,1=Essence,2=Matter,3=Substance). `pair` is frozen here;
// only horizon visibility changes live. Mirrors server/src/constellations.rs.
const CONSTELLATIONS = [
  {id:0,abbr:"Ori",name:"Orion",pair:[0,3],degenerate:true,feeBps:87,visibleThreshold:3,members:[24436,25336,25930,26311,26727,27366,27989],lines:[[27989,25336],[25336,25930],[25930,26311],[26311,26727],[26727,27989],[27366,26727],[24436,25930],[27366,24436]]},
  {id:1,abbr:"UMa",name:"Ursa Major",pair:[0,2],degenerate:false,feeBps:121,visibleThreshold:3,members:[53910,54061,58001,59774,62956,65378,67301],lines:[[54061,53910],[53910,58001],[58001,59774],[59774,54061],[59774,62956],[62956,65378],[65378,67301]]},
  {id:2,abbr:"Cas",name:"Cassiopeia",pair:[1,2],degenerate:true,feeBps:181,visibleThreshold:3,members:[746,3179,4427,6686,8886],lines:[[746,3179],[3179,4427],[4427,6686],[6686,8886]]},
  {id:3,abbr:"Cyg",name:"Cygnus",pair:[1,3],degenerate:false,feeBps:177,visibleThreshold:3,members:[59803,95947,97165,100453,102098],lines:[[102098,100453],[100453,59803],[100453,97165],[100453,95947]]},
  {id:4,abbr:"Lyr",name:"Lyra",pair:[1,2],degenerate:true,feeBps:224,visibleThreshold:3,members:[91262,92420,93194],lines:[[91262,93194],[93194,92420],[92420,91262]]},
  {id:5,abbr:"Sco",name:"Scorpius",pair:[0,3],degenerate:true,feeBps:71,visibleThreshold:4,members:[78265,78401,78820,80763,82396,82514,85696,85927,86228],lines:[[78820,78401],[78401,78265],[78401,80763],[80763,82396],[82396,82514],[82514,86228],[86228,85927],[85927,85696]]},
  {id:6,abbr:"Leo",name:"Leo",pair:[0,2],degenerate:false,feeBps:139,visibleThreshold:3,members:[48455,49669,50335,50583,54872,54879,57632],lines:[[49669,50583],[50583,50335],[50335,48455],[49669,54879],[54879,57632],[57632,54872],[54872,54879],[54872,50583]]},
  {id:7,abbr:"Tau",name:"Taurus",pair:[0,3],degenerate:true,feeBps:216,visibleThreshold:3,members:[21421,25428,26451],lines:[[21421,25428],[21421,26451]]},
  {id:8,abbr:"Gem",name:"Gemini",pair:[1,2],degenerate:true,feeBps:172,visibleThreshold:3,members:[31681,32246,35550,36850,37826],lines:[[36850,37826],[37826,35550],[35550,31681],[36850,32246],[32246,31681]]},
  {id:9,abbr:"CMa",name:"Canis Major",pair:[1,2],degenerate:true,feeBps:122,visibleThreshold:3,members:[30122,30324,32349,33579,34444,35904],lines:[[30324,32349],[32349,34444],[34444,33579],[34444,35904],[33579,30122]]},
  {id:10,abbr:"Boo",name:"Bootes",pair:[0,3],degenerate:true,feeBps:156,visibleThreshold:3,members:[67927,69673,71075,72105,73555,74666],lines:[[69673,72105],[72105,71075],[71075,73555],[73555,74666],[69673,67927],[67927,71075]]},
  {id:11,abbr:"Cru",name:"Crux",pair:[1,2],degenerate:true,feeBps:182,visibleThreshold:3,members:[59747,60718,61084,62434],lines:[[60718,61084],[62434,59747]]},
];
if (typeof module !== "undefined") module.exports = { CONSTELLATIONS };
