// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  burnTxHash: __t.string().primaryKey().name("burn_tx_hash"),
  player: __t.identity(),
  sourceChain: __t.string().name("source_chain"),
  targetChain: __t.string().name("target_chain"),
  sourceAddress: __t.string().name("source_address"),
  targetAddress: __t.string().name("target_address"),
  elementId: __t.u8().name("element_id"),
  amount: __t.u128(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
