// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Planet,
} from "./types";


export default __t.row({
  distributionId: __t.u64().primaryKey().name("distribution_id"),
  decanId: __t.u16().name("decan_id"),
  signIndex: __t.u8().name("sign_index"),
  get winnerFaction() {
    return Planet.name("winner_faction");
  },
  totalEsmsDistributed: __t.u64().name("total_esms_distributed"),
  settledAt: __t.timestamp().name("settled_at"),
});
