// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  txId: __t.u64().primaryKey().name("tx_id"),
  recipient: __t.identity(),
  source: __t.string(),
  spirit: __t.u32(),
  essence: __t.u32(),
  matter: __t.u32(),
  substance: __t.u32(),
  total: __t.u32(),
  createdAt: __t.timestamp().name("created_at"),
});
