// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit baca5cdf77577ed4e3f30da48a5158189c4ea43f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddStarToConstellationReducer from "./add_star_to_constellation_reducer";
import AdminAgentCastJingReducer from "./admin_agent_cast_jing_reducer";
import AdminAgentCastWordReducer from "./admin_agent_cast_word_reducer";
import AdminAgentCounterJingReducer from "./admin_agent_counter_jing_reducer";
import AdminAgentRecordStarStakeReducer from "./admin_agent_record_star_stake_reducer";
import AdminAgentRecordStarUnstakeReducer from "./admin_agent_record_star_unstake_reducer";
import AdminAgentResolveStarBattleReducer from "./admin_agent_resolve_star_battle_reducer";
import AdvanceMeleeReducer from "./advance_melee_reducer";
import AnswerAgentMeleeTurnReducer from "./answer_agent_melee_turn_reducer";
import AnswerDuelReducer from "./answer_duel_reducer";
import AnswerJingReducer from "./answer_jing_reducer";
import AnswerOracleReducer from "./answer_oracle_reducer";
import AnswerTraceReducer from "./answer_trace_reducer";
import AskOracleReducer from "./ask_oracle_reducer";
import BackfillDecansReducer from "./backfill_decans_reducer";
import BindSolanaWalletReducer from "./bind_solana_wallet_reducer";
import CancelStaleClaimReducer from "./cancel_stale_claim_reducer";
import CancelTradeReducer from "./cancel_trade_reducer";
import CaptureArConstellationReducer from "./capture_ar_constellation_reducer";
import CastJingReducer from "./cast_jing_reducer";
import CastWordReducer from "./cast_word_reducer";
import ClaimDailyFaucetReducer from "./claim_daily_faucet_reducer";
import ClaimDuelTimeoutReducer from "./claim_duel_timeout_reducer";
import ClaimProfileReducer from "./claim_profile_reducer";
import CombineCardsReducer from "./combine_cards_reducer";
import CommitDuelReducer from "./commit_duel_reducer";
import ConfirmTradeReducer from "./confirm_trade_reducer";
import ConfirmYieldClaimReducer from "./confirm_yield_claim_reducer";
import CounterJingReducer from "./counter_jing_reducer";
import CreatePlayerReducer from "./create_player_reducer";
import DeletePlayerDataReducer from "./delete_player_data_reducer";
import DeployCardReducer from "./deploy_card_reducer";
import EnqueueDuelReducer from "./enqueue_duel_reducer";
import JoinMeleeQueueReducer from "./join_melee_queue_reducer";
import LeaveMeleeQueueReducer from "./leave_melee_queue_reducer";
import LockAnomalyReducer from "./lock_anomaly_reducer";
import OpenIdentityLinkReducer from "./open_identity_link_reducer";
import OpenMeleeRoundReducer from "./open_melee_round_reducer";
import PlayMeleeCardReducer from "./play_melee_card_reducer";
import ProposeTradeReducer from "./propose_trade_reducer";
import PurgeStaleAgentsReducer from "./purge_stale_agents_reducer";
import PushEphemerisReducer from "./push_ephemeris_reducer";
import RecordMeleePlayReducer from "./record_melee_play_reducer";
import RecordStarStakeReducer from "./record_star_stake_reducer";
import RecordStarUnstakeReducer from "./record_star_unstake_reducer";
import ReportServiceHealthReducer from "./report_service_health_reducer";
import RequestYieldClaimReducer from "./request_yield_claim_reducer";
import ResolveStarBattleReducer from "./resolve_star_battle_reducer";
import SeedAgentPlayerReducer from "./seed_agent_player_reducer";
import SetLoadoutReducer from "./set_loadout_reducer";
import SetLocationReducer from "./set_location_reducer";
import SettleDecanBoundaryReducer from "./settle_decan_boundary_reducer";
import SiegeHorizonStarReducer from "./siege_horizon_star_reducer";
import StardexClaimConstellationReducer from "./stardex_claim_constellation_reducer";
import StardexFortifyNodeReducer from "./stardex_fortify_node_reducer";
import StrikeStarSingleReducer from "./strike_star_single_reducer";
import SubmitMeleeResultReducer from "./submit_melee_result_reducer";
import SyncSolanaEventReducer from "./sync_solana_event_reducer";
import SyncStardexEphemerisReducer from "./sync_stardex_ephemeris_reducer";
import TraceConstellationReducer from "./trace_constellation_reducer";
import TransferStarStakeReducer from "./transfer_star_stake_reducer";
import TriggerZoneFluxReducer from "./trigger_zone_flux_reducer";
import UpdateSeekerEnvironmentReducer from "./update_seeker_environment_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AgentChartRow from "./agent_chart_table";
import AgentMeleeTurnRow from "./agent_melee_turn_table";
import AgentRestRow from "./agent_rest_table";
import BattleRow from "./battle_table";
import CardRow from "./card_table";
import CometRow from "./comet_table";
import ConstellationRow from "./constellation_table";
import ConstellationBlockRow from "./constellation_block_table";
import ConstellationLineRow from "./constellation_line_table";
import ConstellationResolutionRow from "./constellation_resolution_table";
import ConstellationStarRow from "./constellation_star_table";
import DecanYieldDistributionRow from "./decan_yield_distribution_table";
import DeckSlotRow from "./deck_slot_table";
import DuelRow from "./duel_table";
import DuelChallengeRow from "./duel_challenge_table";
import DuelQueueRow from "./duel_queue_table";
import DuelRoundRow from "./duel_round_table";
import EphemerisRow from "./ephemeris_table";
import FaucetTransactionRow from "./faucet_transaction_table";
import GameConfigRow from "./game_config_table";
import HorizonActionReceiptRow from "./horizon_action_receipt_table";
import JingCastRow from "./jing_cast_table";
import JingDuelRow from "./jing_duel_table";
import MeleePlayRow from "./melee_play_table";
import MeleeQueueRow from "./melee_queue_table";
import MeleeSeatRow from "./melee_seat_table";
import MeleeTableRow from "./melee_table_table";
import MeleeTrickRow from "./melee_trick_table";
import NatalDecanRow from "./natal_decan_table";
import OracleCacheRow from "./oracle_cache_table";
import PlayerRow from "./player_table";
import PlayerFaucetStateRow from "./player_faucet_state_table";
import ProcessedTxRow from "./processed_tx_table";
import RoundParticipantRow from "./round_participant_table";
import RoundStateRow from "./round_state_table";
import ServiceStatusRow from "./service_status_table";
import StarAgentRow from "./star_agent_table";
import StarNodeRow from "./star_node_table";
import StarStakePoolRow from "./star_stake_pool_table";
import TradeRow from "./trade_table";
import VerifiedSolanaWalletRow from "./verified_solana_wallet_table";
import WordDuelRow from "./word_duel_table";
import ZoneRow from "./zone_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  agentChart: __table({
    name: 'agent_chart',
    indexes: [
      { accessor: 'identity', name: 'agent_chart_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'agent_chart_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AgentChartRow),
  agentMeleeTurn: __table({
    name: 'agent_melee_turn',
    indexes: [
      { accessor: 'occupant', name: 'agent_melee_turn_occupant_idx_btree', algorithm: 'btree', columns: [
        'occupant',
      ] },
      { accessor: 'seat_id', name: 'agent_melee_turn_seat_id_idx_btree', algorithm: 'btree', columns: [
        'seatId',
      ] },
      { accessor: 'table_id', name: 'agent_melee_turn_table_id_idx_btree', algorithm: 'btree', columns: [
        'tableId',
      ] },
      { accessor: 'turn_id', name: 'agent_melee_turn_turn_id_idx_btree', algorithm: 'btree', columns: [
        'turnId',
      ] },
    ],
    constraints: [
      { name: 'agent_melee_turn_turn_id_key', constraint: 'unique', columns: ['turnId'] },
    ],
  }, AgentMeleeTurnRow),
  agentRest: __table({
    name: 'agent_rest',
    indexes: [
      { accessor: 'identity', name: 'agent_rest_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'agent_rest_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AgentRestRow),
  battle: __table({
    name: 'battle',
    indexes: [
      { accessor: 'battle_id', name: 'battle_battle_id_idx_btree', algorithm: 'btree', columns: [
        'battleId',
      ] },
    ],
    constraints: [
      { name: 'battle_battle_id_key', constraint: 'unique', columns: ['battleId'] },
    ],
  }, BattleRow),
  card: __table({
    name: 'card',
    indexes: [
      { accessor: 'card_id', name: 'card_card_id_idx_btree', algorithm: 'btree', columns: [
        'cardId',
      ] },
      { accessor: 'owner', name: 'card_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'card_card_id_key', constraint: 'unique', columns: ['cardId'] },
    ],
  }, CardRow),
  comet: __table({
    name: 'comet',
    indexes: [
      { accessor: 'comet_id', name: 'comet_comet_id_idx_btree', algorithm: 'btree', columns: [
        'cometId',
      ] },
    ],
    constraints: [
      { name: 'comet_comet_id_key', constraint: 'unique', columns: ['cometId'] },
    ],
  }, CometRow),
  constellation: __table({
    name: 'constellation',
    indexes: [
      { accessor: 'constellation_id', name: 'constellation_constellation_id_idx_btree', algorithm: 'btree', columns: [
        'constellationId',
      ] },
    ],
    constraints: [
      { name: 'constellation_constellation_id_key', constraint: 'unique', columns: ['constellationId'] },
    ],
  }, ConstellationRow),
  constellationBlock: __table({
    name: 'constellation_block',
    indexes: [
      { accessor: 'block_id', name: 'constellation_block_block_id_idx_btree', algorithm: 'btree', columns: [
        'blockId',
      ] },
      { accessor: 'constellation_id', name: 'constellation_block_constellation_id_idx_btree', algorithm: 'btree', columns: [
        'constellationId',
      ] },
    ],
    constraints: [
      { name: 'constellation_block_block_id_key', constraint: 'unique', columns: ['blockId'] },
    ],
  }, ConstellationBlockRow),
  constellationLine: __table({
    name: 'constellation_line',
    indexes: [
      { accessor: 'constellation_id', name: 'constellation_line_constellation_id_idx_btree', algorithm: 'btree', columns: [
        'constellationId',
      ] },
      { accessor: 'id', name: 'constellation_line_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'constellation_line_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConstellationLineRow),
  constellationResolution: __table({
    name: 'constellation_resolution',
    indexes: [
      { accessor: 'constellation_id', name: 'constellation_resolution_constellation_id_idx_btree', algorithm: 'btree', columns: [
        'constellationId',
      ] },
    ],
    constraints: [
      { name: 'constellation_resolution_constellation_id_key', constraint: 'unique', columns: ['constellationId'] },
    ],
  }, ConstellationResolutionRow),
  constellationStar: __table({
    name: 'constellation_star',
    indexes: [
      { accessor: 'constellation_id', name: 'constellation_star_constellation_id_idx_btree', algorithm: 'btree', columns: [
        'constellationId',
      ] },
      { accessor: 'id', name: 'constellation_star_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'constellation_star_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConstellationStarRow),
  decanYieldDistribution: __table({
    name: 'decan_yield_distribution',
    indexes: [
      { accessor: 'distribution_id', name: 'decan_yield_distribution_distribution_id_idx_btree', algorithm: 'btree', columns: [
        'distributionId',
      ] },
    ],
    constraints: [
      { name: 'decan_yield_distribution_distribution_id_key', constraint: 'unique', columns: ['distributionId'] },
    ],
  }, DecanYieldDistributionRow),
  deckSlot: __table({
    name: 'deck_slot',
    indexes: [
      { accessor: 'card_id', name: 'deck_slot_card_id_idx_btree', algorithm: 'btree', columns: [
        'cardId',
      ] },
      { accessor: 'loadout', name: 'deck_slot_loadout_idx_btree', algorithm: 'btree', columns: [
        'loadout',
      ] },
      { accessor: 'owner', name: 'deck_slot_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
      { accessor: 'slot_id', name: 'deck_slot_slot_id_idx_btree', algorithm: 'btree', columns: [
        'slotId',
      ] },
    ],
    constraints: [
      { name: 'deck_slot_slot_id_key', constraint: 'unique', columns: ['slotId'] },
    ],
  }, DeckSlotRow),
  duel: __table({
    name: 'duel',
    indexes: [
      { accessor: 'duel_id', name: 'duel_duel_id_idx_btree', algorithm: 'btree', columns: [
        'duelId',
      ] },
    ],
    constraints: [
      { name: 'duel_duel_id_key', constraint: 'unique', columns: ['duelId'] },
    ],
  }, DuelRow),
  duelChallenge: __table({
    name: 'duel_challenge',
    indexes: [
      { accessor: 'challenge_id', name: 'duel_challenge_challenge_id_idx_btree', algorithm: 'btree', columns: [
        'challengeId',
      ] },
      { accessor: 'player', name: 'duel_challenge_player_idx_btree', algorithm: 'btree', columns: [
        'player',
      ] },
    ],
    constraints: [
      { name: 'duel_challenge_challenge_id_key', constraint: 'unique', columns: ['challengeId'] },
    ],
  }, DuelChallengeRow),
  duelQueue: __table({
    name: 'duel_queue',
    indexes: [
      { accessor: 'ticket_id', name: 'duel_queue_ticket_id_idx_btree', algorithm: 'btree', columns: [
        'ticketId',
      ] },
      { accessor: 'zone_id', name: 'duel_queue_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'duel_queue_ticket_id_key', constraint: 'unique', columns: ['ticketId'] },
    ],
  }, DuelQueueRow),
  duelRound: __table({
    name: 'duel_round',
    indexes: [
      { accessor: 'round_id', name: 'duel_round_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
    ],
    constraints: [
      { name: 'duel_round_round_id_key', constraint: 'unique', columns: ['roundId'] },
    ],
  }, DuelRoundRow),
  ephemeris: __table({
    name: 'ephemeris',
    indexes: [
      { accessor: 'body', name: 'ephemeris_body_idx_btree', algorithm: 'btree', columns: [
        'body',
      ] },
    ],
    constraints: [
      { name: 'ephemeris_body_key', constraint: 'unique', columns: ['body'] },
    ],
  }, EphemerisRow),
  faucetTransaction: __table({
    name: 'faucet_transaction',
    indexes: [
      { accessor: 'recipient', name: 'faucet_transaction_recipient_idx_btree', algorithm: 'btree', columns: [
        'recipient',
      ] },
      { accessor: 'tx_id', name: 'faucet_transaction_tx_id_idx_btree', algorithm: 'btree', columns: [
        'txId',
      ] },
    ],
    constraints: [
      { name: 'faucet_transaction_tx_id_key', constraint: 'unique', columns: ['txId'] },
    ],
  }, FaucetTransactionRow),
  gameConfig: __table({
    name: 'game_config',
    indexes: [
      { accessor: 'id', name: 'game_config_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_config_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameConfigRow),
  horizonActionReceipt: __table({
    name: 'horizon_action_receipt',
    indexes: [
      { accessor: 'action_key', name: 'horizon_action_receipt_action_key_idx_btree', algorithm: 'btree', columns: [
        'actionKey',
      ] },
      { accessor: 'intent_id', name: 'horizon_action_receipt_intent_id_idx_btree', algorithm: 'btree', columns: [
        'intentId',
      ] },
    ],
    constraints: [
      { name: 'horizon_action_receipt_action_key_key', constraint: 'unique', columns: ['actionKey'] },
    ],
  }, HorizonActionReceiptRow),
  jingCast: __table({
    name: 'jing_cast',
    indexes: [
      { accessor: 'cast_id', name: 'jing_cast_cast_id_idx_btree', algorithm: 'btree', columns: [
        'castId',
      ] },
      { accessor: 'duel_id', name: 'jing_cast_duel_id_idx_btree', algorithm: 'btree', columns: [
        'duelId',
      ] },
    ],
    constraints: [
      { name: 'jing_cast_cast_id_key', constraint: 'unique', columns: ['castId'] },
    ],
  }, JingCastRow),
  jingDuel: __table({
    name: 'jing_duel',
    indexes: [
      { accessor: 'duel_id', name: 'jing_duel_duel_id_idx_btree', algorithm: 'btree', columns: [
        'duelId',
      ] },
      { accessor: 'initiator', name: 'jing_duel_initiator_idx_btree', algorithm: 'btree', columns: [
        'initiator',
      ] },
    ],
    constraints: [
      { name: 'jing_duel_duel_id_key', constraint: 'unique', columns: ['duelId'] },
    ],
  }, JingDuelRow),
  meleePlay: __table({
    name: 'melee_play',
    indexes: [
      { accessor: 'play_id', name: 'melee_play_play_id_idx_btree', algorithm: 'btree', columns: [
        'playId',
      ] },
      { accessor: 'table_id', name: 'melee_play_table_id_idx_btree', algorithm: 'btree', columns: [
        'tableId',
      ] },
    ],
    constraints: [
      { name: 'melee_play_play_id_key', constraint: 'unique', columns: ['playId'] },
    ],
  }, MeleePlayRow),
  meleeQueue: __table({
    name: 'melee_queue',
    indexes: [
      { accessor: 'identity', name: 'melee_queue_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'zone_id', name: 'melee_queue_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'melee_queue_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, MeleeQueueRow),
  meleeSeat: __table({
    name: 'melee_seat',
    indexes: [
      { accessor: 'occupant', name: 'melee_seat_occupant_idx_btree', algorithm: 'btree', columns: [
        'occupant',
      ] },
      { accessor: 'seat_id', name: 'melee_seat_seat_id_idx_btree', algorithm: 'btree', columns: [
        'seatId',
      ] },
      { accessor: 'table_id', name: 'melee_seat_table_id_idx_btree', algorithm: 'btree', columns: [
        'tableId',
      ] },
    ],
    constraints: [
      { name: 'melee_seat_seat_id_key', constraint: 'unique', columns: ['seatId'] },
    ],
  }, MeleeSeatRow),
  meleeTable: __table({
    name: 'melee_table',
    indexes: [
      { accessor: 'table_id', name: 'melee_table_table_id_idx_btree', algorithm: 'btree', columns: [
        'tableId',
      ] },
      { accessor: 'zone_id', name: 'melee_table_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'melee_table_table_id_key', constraint: 'unique', columns: ['tableId'] },
    ],
  }, MeleeTableRow),
  meleeTrick: __table({
    name: 'melee_trick',
    indexes: [
      { accessor: 'table_id', name: 'melee_trick_table_id_idx_btree', algorithm: 'btree', columns: [
        'tableId',
      ] },
      { accessor: 'trick_id', name: 'melee_trick_trick_id_idx_btree', algorithm: 'btree', columns: [
        'trickId',
      ] },
    ],
    constraints: [
      { name: 'melee_trick_trick_id_key', constraint: 'unique', columns: ['trickId'] },
    ],
  }, MeleeTrickRow),
  natalDecan: __table({
    name: 'natal_decan',
    indexes: [
      { accessor: 'decan_id', name: 'natal_decan_decan_id_idx_btree', algorithm: 'btree', columns: [
        'decanId',
      ] },
      { accessor: 'owner', name: 'natal_decan_owner_idx_btree', algorithm: 'btree', columns: [
        'owner',
      ] },
    ],
    constraints: [
      { name: 'natal_decan_decan_id_key', constraint: 'unique', columns: ['decanId'] },
    ],
  }, NatalDecanRow),
  oracleCache: __table({
    name: 'oracle_cache',
    indexes: [
      { accessor: 'qhash', name: 'oracle_cache_qhash_idx_btree', algorithm: 'btree', columns: [
        'qhash',
      ] },
    ],
    constraints: [
      { name: 'oracle_cache_qhash_key', constraint: 'unique', columns: ['qhash'] },
    ],
  }, OracleCacheRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  playerFaucetState: __table({
    name: 'player_faucet_state',
    indexes: [
      { accessor: 'identity', name: 'player_faucet_state_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_faucet_state_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerFaucetStateRow),
  processedTx: __table({
    name: 'processed_tx',
    indexes: [
      { accessor: 'tx_hash', name: 'processed_tx_tx_hash_idx_btree', algorithm: 'btree', columns: [
        'txHash',
      ] },
    ],
    constraints: [
      { name: 'processed_tx_tx_hash_key', constraint: 'unique', columns: ['txHash'] },
    ],
  }, ProcessedTxRow),
  roundParticipant: __table({
    name: 'round_participant',
    indexes: [
      { accessor: 'id', name: 'round_participant_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'round_id', name: 'round_participant_round_id_idx_btree', algorithm: 'btree', columns: [
        'roundId',
      ] },
    ],
    constraints: [
      { name: 'round_participant_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoundParticipantRow),
  roundState: __table({
    name: 'round_state',
    indexes: [
      { accessor: 'identity', name: 'round_state_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'round_state_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, RoundStateRow),
  serviceStatus: __table({
    name: 'service_status',
    indexes: [
      { accessor: 'service', name: 'service_status_service_idx_btree', algorithm: 'btree', columns: [
        'service',
      ] },
    ],
    constraints: [
      { name: 'service_status_service_key', constraint: 'unique', columns: ['service'] },
    ],
  }, ServiceStatusRow),
  starAgent: __table({
    name: 'star_agent',
    indexes: [
      { accessor: 'hip_id', name: 'star_agent_hip_id_idx_btree', algorithm: 'btree', columns: [
        'hipId',
      ] },
    ],
    constraints: [
      { name: 'star_agent_hip_id_key', constraint: 'unique', columns: ['hipId'] },
    ],
  }, StarAgentRow),
  starNode: __table({
    name: 'star_node',
    indexes: [
      { accessor: 'hip_id', name: 'star_node_hip_id_idx_btree', algorithm: 'btree', columns: [
        'hipId',
      ] },
    ],
    constraints: [
      { name: 'star_node_hip_id_key', constraint: 'unique', columns: ['hipId'] },
    ],
  }, StarNodeRow),
  starStakePool: __table({
    name: 'star_stake_pool',
    indexes: [
      { accessor: 'star_id', name: 'star_stake_pool_star_id_idx_btree', algorithm: 'btree', columns: [
        'starId',
      ] },
    ],
    constraints: [
      { name: 'star_stake_pool_star_id_key', constraint: 'unique', columns: ['starId'] },
    ],
  }, StarStakePoolRow),
  trade: __table({
    name: 'trade',
    indexes: [
      { accessor: 'partner', name: 'trade_partner_idx_btree', algorithm: 'btree', columns: [
        'partner',
      ] },
      { accessor: 'proposer', name: 'trade_proposer_idx_btree', algorithm: 'btree', columns: [
        'proposer',
      ] },
      { accessor: 'trade_id', name: 'trade_trade_id_idx_btree', algorithm: 'btree', columns: [
        'tradeId',
      ] },
    ],
    constraints: [
      { name: 'trade_trade_id_key', constraint: 'unique', columns: ['tradeId'] },
    ],
  }, TradeRow),
  verifiedSolanaWallet: __table({
    name: 'verified_solana_wallet',
    indexes: [
      { accessor: 'identity', name: 'verified_solana_wallet_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'solana_pubkey', name: 'verified_solana_wallet_solana_pubkey_idx_btree', algorithm: 'btree', columns: [
        'solanaPubkey',
      ] },
    ],
    constraints: [
      { name: 'verified_solana_wallet_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'verified_solana_wallet_solana_pubkey_key', constraint: 'unique', columns: ['solanaPubkey'] },
    ],
  }, VerifiedSolanaWalletRow),
  wordDuel: __table({
    name: 'word_duel',
    indexes: [
      { accessor: 'duel_id', name: 'word_duel_duel_id_idx_btree', algorithm: 'btree', columns: [
        'duelId',
      ] },
      { accessor: 'player', name: 'word_duel_player_idx_btree', algorithm: 'btree', columns: [
        'player',
      ] },
    ],
    constraints: [
      { name: 'word_duel_duel_id_key', constraint: 'unique', columns: ['duelId'] },
    ],
  }, WordDuelRow),
  zone: __table({
    name: 'zone',
    indexes: [
      { accessor: 'zone_id', name: 'zone_zone_id_idx_btree', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'zone_zone_id_key', constraint: 'unique', columns: ['zoneId'] },
    ],
  }, ZoneRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_star_to_constellation", AddStarToConstellationReducer),
  __reducerSchema("admin_agent_cast_jing", AdminAgentCastJingReducer),
  __reducerSchema("admin_agent_cast_word", AdminAgentCastWordReducer),
  __reducerSchema("admin_agent_counter_jing", AdminAgentCounterJingReducer),
  __reducerSchema("admin_agent_record_star_stake", AdminAgentRecordStarStakeReducer),
  __reducerSchema("admin_agent_record_star_unstake", AdminAgentRecordStarUnstakeReducer),
  __reducerSchema("admin_agent_resolve_star_battle", AdminAgentResolveStarBattleReducer),
  __reducerSchema("advance_melee", AdvanceMeleeReducer),
  __reducerSchema("answer_agent_melee_turn", AnswerAgentMeleeTurnReducer),
  __reducerSchema("answer_duel", AnswerDuelReducer),
  __reducerSchema("answer_jing", AnswerJingReducer),
  __reducerSchema("answer_oracle", AnswerOracleReducer),
  __reducerSchema("answer_trace", AnswerTraceReducer),
  __reducerSchema("ask_oracle", AskOracleReducer),
  __reducerSchema("backfill_decans", BackfillDecansReducer),
  __reducerSchema("bind_solana_wallet", BindSolanaWalletReducer),
  __reducerSchema("cancel_stale_claim", CancelStaleClaimReducer),
  __reducerSchema("cancel_trade", CancelTradeReducer),
  __reducerSchema("capture_ar_constellation", CaptureArConstellationReducer),
  __reducerSchema("cast_jing", CastJingReducer),
  __reducerSchema("cast_word", CastWordReducer),
  __reducerSchema("claim_daily_faucet", ClaimDailyFaucetReducer),
  __reducerSchema("claim_duel_timeout", ClaimDuelTimeoutReducer),
  __reducerSchema("claim_profile", ClaimProfileReducer),
  __reducerSchema("combine_cards", CombineCardsReducer),
  __reducerSchema("commit_duel", CommitDuelReducer),
  __reducerSchema("confirm_trade", ConfirmTradeReducer),
  __reducerSchema("confirm_yield_claim", ConfirmYieldClaimReducer),
  __reducerSchema("counter_jing", CounterJingReducer),
  __reducerSchema("create_player", CreatePlayerReducer),
  __reducerSchema("delete_player_data", DeletePlayerDataReducer),
  __reducerSchema("deploy_card", DeployCardReducer),
  __reducerSchema("enqueue_duel", EnqueueDuelReducer),
  __reducerSchema("join_melee_queue", JoinMeleeQueueReducer),
  __reducerSchema("leave_melee_queue", LeaveMeleeQueueReducer),
  __reducerSchema("lock_anomaly", LockAnomalyReducer),
  __reducerSchema("open_identity_link", OpenIdentityLinkReducer),
  __reducerSchema("open_melee_round", OpenMeleeRoundReducer),
  __reducerSchema("play_melee_card", PlayMeleeCardReducer),
  __reducerSchema("propose_trade", ProposeTradeReducer),
  __reducerSchema("purge_stale_agents", PurgeStaleAgentsReducer),
  __reducerSchema("push_ephemeris", PushEphemerisReducer),
  __reducerSchema("record_melee_play", RecordMeleePlayReducer),
  __reducerSchema("record_star_stake", RecordStarStakeReducer),
  __reducerSchema("record_star_unstake", RecordStarUnstakeReducer),
  __reducerSchema("report_service_health", ReportServiceHealthReducer),
  __reducerSchema("request_yield_claim", RequestYieldClaimReducer),
  __reducerSchema("resolve_star_battle", ResolveStarBattleReducer),
  __reducerSchema("seed_agent_player", SeedAgentPlayerReducer),
  __reducerSchema("set_loadout", SetLoadoutReducer),
  __reducerSchema("set_location", SetLocationReducer),
  __reducerSchema("settle_decan_boundary", SettleDecanBoundaryReducer),
  __reducerSchema("siege_horizon_star", SiegeHorizonStarReducer),
  __reducerSchema("stardex_claim_constellation", StardexClaimConstellationReducer),
  __reducerSchema("stardex_fortify_node", StardexFortifyNodeReducer),
  __reducerSchema("strike_star_single", StrikeStarSingleReducer),
  __reducerSchema("submit_melee_result", SubmitMeleeResultReducer),
  __reducerSchema("sync_solana_event", SyncSolanaEventReducer),
  __reducerSchema("sync_stardex_ephemeris", SyncStardexEphemerisReducer),
  __reducerSchema("trace_constellation", TraceConstellationReducer),
  __reducerSchema("transfer_star_stake", TransferStarStakeReducer),
  __reducerSchema("trigger_zone_flux", TriggerZoneFluxReducer),
  __reducerSchema("update_seeker_environment", UpdateSeekerEnvironmentReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `agentChart` instead. This alias will be removed in the next major version. */
    readonly "agent_chart": Omit<typeof tablesSchema.schemaType.tables["agentChart"], "accessorName"> & { readonly accessorName: "agent_chart" };
    /** @deprecated Use `agentMeleeTurn` instead. This alias will be removed in the next major version. */
    readonly "agent_melee_turn": Omit<typeof tablesSchema.schemaType.tables["agentMeleeTurn"], "accessorName"> & { readonly accessorName: "agent_melee_turn" };
    /** @deprecated Use `agentRest` instead. This alias will be removed in the next major version. */
    readonly "agent_rest": Omit<typeof tablesSchema.schemaType.tables["agentRest"], "accessorName"> & { readonly accessorName: "agent_rest" };
    /** @deprecated Use `constellationBlock` instead. This alias will be removed in the next major version. */
    readonly "constellation_block": Omit<typeof tablesSchema.schemaType.tables["constellationBlock"], "accessorName"> & { readonly accessorName: "constellation_block" };
    /** @deprecated Use `constellationLine` instead. This alias will be removed in the next major version. */
    readonly "constellation_line": Omit<typeof tablesSchema.schemaType.tables["constellationLine"], "accessorName"> & { readonly accessorName: "constellation_line" };
    /** @deprecated Use `constellationResolution` instead. This alias will be removed in the next major version. */
    readonly "constellation_resolution": Omit<typeof tablesSchema.schemaType.tables["constellationResolution"], "accessorName"> & { readonly accessorName: "constellation_resolution" };
    /** @deprecated Use `constellationStar` instead. This alias will be removed in the next major version. */
    readonly "constellation_star": Omit<typeof tablesSchema.schemaType.tables["constellationStar"], "accessorName"> & { readonly accessorName: "constellation_star" };
    /** @deprecated Use `decanYieldDistribution` instead. This alias will be removed in the next major version. */
    readonly "decan_yield_distribution": Omit<typeof tablesSchema.schemaType.tables["decanYieldDistribution"], "accessorName"> & { readonly accessorName: "decan_yield_distribution" };
    /** @deprecated Use `deckSlot` instead. This alias will be removed in the next major version. */
    readonly "deck_slot": Omit<typeof tablesSchema.schemaType.tables["deckSlot"], "accessorName"> & { readonly accessorName: "deck_slot" };
    /** @deprecated Use `duelChallenge` instead. This alias will be removed in the next major version. */
    readonly "duel_challenge": Omit<typeof tablesSchema.schemaType.tables["duelChallenge"], "accessorName"> & { readonly accessorName: "duel_challenge" };
    /** @deprecated Use `duelQueue` instead. This alias will be removed in the next major version. */
    readonly "duel_queue": Omit<typeof tablesSchema.schemaType.tables["duelQueue"], "accessorName"> & { readonly accessorName: "duel_queue" };
    /** @deprecated Use `duelRound` instead. This alias will be removed in the next major version. */
    readonly "duel_round": Omit<typeof tablesSchema.schemaType.tables["duelRound"], "accessorName"> & { readonly accessorName: "duel_round" };
    /** @deprecated Use `faucetTransaction` instead. This alias will be removed in the next major version. */
    readonly "faucet_transaction": Omit<typeof tablesSchema.schemaType.tables["faucetTransaction"], "accessorName"> & { readonly accessorName: "faucet_transaction" };
    /** @deprecated Use `gameConfig` instead. This alias will be removed in the next major version. */
    readonly "game_config": Omit<typeof tablesSchema.schemaType.tables["gameConfig"], "accessorName"> & { readonly accessorName: "game_config" };
    /** @deprecated Use `horizonActionReceipt` instead. This alias will be removed in the next major version. */
    readonly "horizon_action_receipt": Omit<typeof tablesSchema.schemaType.tables["horizonActionReceipt"], "accessorName"> & { readonly accessorName: "horizon_action_receipt" };
    /** @deprecated Use `jingCast` instead. This alias will be removed in the next major version. */
    readonly "jing_cast": Omit<typeof tablesSchema.schemaType.tables["jingCast"], "accessorName"> & { readonly accessorName: "jing_cast" };
    /** @deprecated Use `jingDuel` instead. This alias will be removed in the next major version. */
    readonly "jing_duel": Omit<typeof tablesSchema.schemaType.tables["jingDuel"], "accessorName"> & { readonly accessorName: "jing_duel" };
    /** @deprecated Use `meleePlay` instead. This alias will be removed in the next major version. */
    readonly "melee_play": Omit<typeof tablesSchema.schemaType.tables["meleePlay"], "accessorName"> & { readonly accessorName: "melee_play" };
    /** @deprecated Use `meleeQueue` instead. This alias will be removed in the next major version. */
    readonly "melee_queue": Omit<typeof tablesSchema.schemaType.tables["meleeQueue"], "accessorName"> & { readonly accessorName: "melee_queue" };
    /** @deprecated Use `meleeSeat` instead. This alias will be removed in the next major version. */
    readonly "melee_seat": Omit<typeof tablesSchema.schemaType.tables["meleeSeat"], "accessorName"> & { readonly accessorName: "melee_seat" };
    /** @deprecated Use `meleeTable` instead. This alias will be removed in the next major version. */
    readonly "melee_table": Omit<typeof tablesSchema.schemaType.tables["meleeTable"], "accessorName"> & { readonly accessorName: "melee_table" };
    /** @deprecated Use `meleeTrick` instead. This alias will be removed in the next major version. */
    readonly "melee_trick": Omit<typeof tablesSchema.schemaType.tables["meleeTrick"], "accessorName"> & { readonly accessorName: "melee_trick" };
    /** @deprecated Use `natalDecan` instead. This alias will be removed in the next major version. */
    readonly "natal_decan": Omit<typeof tablesSchema.schemaType.tables["natalDecan"], "accessorName"> & { readonly accessorName: "natal_decan" };
    /** @deprecated Use `oracleCache` instead. This alias will be removed in the next major version. */
    readonly "oracle_cache": Omit<typeof tablesSchema.schemaType.tables["oracleCache"], "accessorName"> & { readonly accessorName: "oracle_cache" };
    /** @deprecated Use `playerFaucetState` instead. This alias will be removed in the next major version. */
    readonly "player_faucet_state": Omit<typeof tablesSchema.schemaType.tables["playerFaucetState"], "accessorName"> & { readonly accessorName: "player_faucet_state" };
    /** @deprecated Use `processedTx` instead. This alias will be removed in the next major version. */
    readonly "processed_tx": Omit<typeof tablesSchema.schemaType.tables["processedTx"], "accessorName"> & { readonly accessorName: "processed_tx" };
    /** @deprecated Use `roundParticipant` instead. This alias will be removed in the next major version. */
    readonly "round_participant": Omit<typeof tablesSchema.schemaType.tables["roundParticipant"], "accessorName"> & { readonly accessorName: "round_participant" };
    /** @deprecated Use `roundState` instead. This alias will be removed in the next major version. */
    readonly "round_state": Omit<typeof tablesSchema.schemaType.tables["roundState"], "accessorName"> & { readonly accessorName: "round_state" };
    /** @deprecated Use `serviceStatus` instead. This alias will be removed in the next major version. */
    readonly "service_status": Omit<typeof tablesSchema.schemaType.tables["serviceStatus"], "accessorName"> & { readonly accessorName: "service_status" };
    /** @deprecated Use `starAgent` instead. This alias will be removed in the next major version. */
    readonly "star_agent": Omit<typeof tablesSchema.schemaType.tables["starAgent"], "accessorName"> & { readonly accessorName: "star_agent" };
    /** @deprecated Use `starNode` instead. This alias will be removed in the next major version. */
    readonly "star_node": Omit<typeof tablesSchema.schemaType.tables["starNode"], "accessorName"> & { readonly accessorName: "star_node" };
    /** @deprecated Use `starStakePool` instead. This alias will be removed in the next major version. */
    readonly "star_stake_pool": Omit<typeof tablesSchema.schemaType.tables["starStakePool"], "accessorName"> & { readonly accessorName: "star_stake_pool" };
    /** @deprecated Use `verifiedSolanaWallet` instead. This alias will be removed in the next major version. */
    readonly "verified_solana_wallet": Omit<typeof tablesSchema.schemaType.tables["verifiedSolanaWallet"], "accessorName"> & { readonly accessorName: "verified_solana_wallet" };
    /** @deprecated Use `wordDuel` instead. This alias will be removed in the next major version. */
    readonly "word_duel": Omit<typeof tablesSchema.schemaType.tables["wordDuel"], "accessorName"> & { readonly accessorName: "word_duel" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.0" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "agent_chart": "agentChart",
  "agent_melee_turn": "agentMeleeTurn",
  "agent_rest": "agentRest",
  "constellation_block": "constellationBlock",
  "constellation_line": "constellationLine",
  "constellation_resolution": "constellationResolution",
  "constellation_star": "constellationStar",
  "decan_yield_distribution": "decanYieldDistribution",
  "deck_slot": "deckSlot",
  "duel_challenge": "duelChallenge",
  "duel_queue": "duelQueue",
  "duel_round": "duelRound",
  "faucet_transaction": "faucetTransaction",
  "game_config": "gameConfig",
  "horizon_action_receipt": "horizonActionReceipt",
  "jing_cast": "jingCast",
  "jing_duel": "jingDuel",
  "melee_play": "meleePlay",
  "melee_queue": "meleeQueue",
  "melee_seat": "meleeSeat",
  "melee_table": "meleeTable",
  "melee_trick": "meleeTrick",
  "natal_decan": "natalDecan",
  "oracle_cache": "oracleCache",
  "player_faucet_state": "playerFaucetState",
  "processed_tx": "processedTx",
  "round_participant": "roundParticipant",
  "round_state": "roundState",
  "service_status": "serviceStatus",
  "star_agent": "starAgent",
  "star_node": "starNode",
  "star_stake_pool": "starStakePool",
  "verified_solana_wallet": "verifiedSolanaWallet",
  "word_duel": "wordDuel",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `agentChart` instead. This alias will be removed in the next major version. */
  readonly "agent_chart": __DbViewBase["agentChart"];
  /** @deprecated Use `agentMeleeTurn` instead. This alias will be removed in the next major version. */
  readonly "agent_melee_turn": __DbViewBase["agentMeleeTurn"];
  /** @deprecated Use `agentRest` instead. This alias will be removed in the next major version. */
  readonly "agent_rest": __DbViewBase["agentRest"];
  /** @deprecated Use `constellationBlock` instead. This alias will be removed in the next major version. */
  readonly "constellation_block": __DbViewBase["constellationBlock"];
  /** @deprecated Use `constellationLine` instead. This alias will be removed in the next major version. */
  readonly "constellation_line": __DbViewBase["constellationLine"];
  /** @deprecated Use `constellationResolution` instead. This alias will be removed in the next major version. */
  readonly "constellation_resolution": __DbViewBase["constellationResolution"];
  /** @deprecated Use `constellationStar` instead. This alias will be removed in the next major version. */
  readonly "constellation_star": __DbViewBase["constellationStar"];
  /** @deprecated Use `decanYieldDistribution` instead. This alias will be removed in the next major version. */
  readonly "decan_yield_distribution": __DbViewBase["decanYieldDistribution"];
  /** @deprecated Use `deckSlot` instead. This alias will be removed in the next major version. */
  readonly "deck_slot": __DbViewBase["deckSlot"];
  /** @deprecated Use `duelChallenge` instead. This alias will be removed in the next major version. */
  readonly "duel_challenge": __DbViewBase["duelChallenge"];
  /** @deprecated Use `duelQueue` instead. This alias will be removed in the next major version. */
  readonly "duel_queue": __DbViewBase["duelQueue"];
  /** @deprecated Use `duelRound` instead. This alias will be removed in the next major version. */
  readonly "duel_round": __DbViewBase["duelRound"];
  /** @deprecated Use `faucetTransaction` instead. This alias will be removed in the next major version. */
  readonly "faucet_transaction": __DbViewBase["faucetTransaction"];
  /** @deprecated Use `gameConfig` instead. This alias will be removed in the next major version. */
  readonly "game_config": __DbViewBase["gameConfig"];
  /** @deprecated Use `horizonActionReceipt` instead. This alias will be removed in the next major version. */
  readonly "horizon_action_receipt": __DbViewBase["horizonActionReceipt"];
  /** @deprecated Use `jingCast` instead. This alias will be removed in the next major version. */
  readonly "jing_cast": __DbViewBase["jingCast"];
  /** @deprecated Use `jingDuel` instead. This alias will be removed in the next major version. */
  readonly "jing_duel": __DbViewBase["jingDuel"];
  /** @deprecated Use `meleePlay` instead. This alias will be removed in the next major version. */
  readonly "melee_play": __DbViewBase["meleePlay"];
  /** @deprecated Use `meleeQueue` instead. This alias will be removed in the next major version. */
  readonly "melee_queue": __DbViewBase["meleeQueue"];
  /** @deprecated Use `meleeSeat` instead. This alias will be removed in the next major version. */
  readonly "melee_seat": __DbViewBase["meleeSeat"];
  /** @deprecated Use `meleeTable` instead. This alias will be removed in the next major version. */
  readonly "melee_table": __DbViewBase["meleeTable"];
  /** @deprecated Use `meleeTrick` instead. This alias will be removed in the next major version. */
  readonly "melee_trick": __DbViewBase["meleeTrick"];
  /** @deprecated Use `natalDecan` instead. This alias will be removed in the next major version. */
  readonly "natal_decan": __DbViewBase["natalDecan"];
  /** @deprecated Use `oracleCache` instead. This alias will be removed in the next major version. */
  readonly "oracle_cache": __DbViewBase["oracleCache"];
  /** @deprecated Use `playerFaucetState` instead. This alias will be removed in the next major version. */
  readonly "player_faucet_state": __DbViewBase["playerFaucetState"];
  /** @deprecated Use `processedTx` instead. This alias will be removed in the next major version. */
  readonly "processed_tx": __DbViewBase["processedTx"];
  /** @deprecated Use `roundParticipant` instead. This alias will be removed in the next major version. */
  readonly "round_participant": __DbViewBase["roundParticipant"];
  /** @deprecated Use `roundState` instead. This alias will be removed in the next major version. */
  readonly "round_state": __DbViewBase["roundState"];
  /** @deprecated Use `serviceStatus` instead. This alias will be removed in the next major version. */
  readonly "service_status": __DbViewBase["serviceStatus"];
  /** @deprecated Use `starAgent` instead. This alias will be removed in the next major version. */
  readonly "star_agent": __DbViewBase["starAgent"];
  /** @deprecated Use `starNode` instead. This alias will be removed in the next major version. */
  readonly "star_node": __DbViewBase["starNode"];
  /** @deprecated Use `starStakePool` instead. This alias will be removed in the next major version. */
  readonly "star_stake_pool": __DbViewBase["starStakePool"];
  /** @deprecated Use `verifiedSolanaWallet` instead. This alias will be removed in the next major version. */
  readonly "verified_solana_wallet": __DbViewBase["verifiedSolanaWallet"];
  /** @deprecated Use `wordDuel` instead. This alias will be removed in the next major version. */
  readonly "word_duel": __DbViewBase["wordDuel"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `agentChart` instead. This alias will be removed in the next major version. */
  readonly "agent_chart": __TablesBase["agentChart"];
  /** @deprecated Use `agentMeleeTurn` instead. This alias will be removed in the next major version. */
  readonly "agent_melee_turn": __TablesBase["agentMeleeTurn"];
  /** @deprecated Use `agentRest` instead. This alias will be removed in the next major version. */
  readonly "agent_rest": __TablesBase["agentRest"];
  /** @deprecated Use `constellationBlock` instead. This alias will be removed in the next major version. */
  readonly "constellation_block": __TablesBase["constellationBlock"];
  /** @deprecated Use `constellationLine` instead. This alias will be removed in the next major version. */
  readonly "constellation_line": __TablesBase["constellationLine"];
  /** @deprecated Use `constellationResolution` instead. This alias will be removed in the next major version. */
  readonly "constellation_resolution": __TablesBase["constellationResolution"];
  /** @deprecated Use `constellationStar` instead. This alias will be removed in the next major version. */
  readonly "constellation_star": __TablesBase["constellationStar"];
  /** @deprecated Use `decanYieldDistribution` instead. This alias will be removed in the next major version. */
  readonly "decan_yield_distribution": __TablesBase["decanYieldDistribution"];
  /** @deprecated Use `deckSlot` instead. This alias will be removed in the next major version. */
  readonly "deck_slot": __TablesBase["deckSlot"];
  /** @deprecated Use `duelChallenge` instead. This alias will be removed in the next major version. */
  readonly "duel_challenge": __TablesBase["duelChallenge"];
  /** @deprecated Use `duelQueue` instead. This alias will be removed in the next major version. */
  readonly "duel_queue": __TablesBase["duelQueue"];
  /** @deprecated Use `duelRound` instead. This alias will be removed in the next major version. */
  readonly "duel_round": __TablesBase["duelRound"];
  /** @deprecated Use `faucetTransaction` instead. This alias will be removed in the next major version. */
  readonly "faucet_transaction": __TablesBase["faucetTransaction"];
  /** @deprecated Use `gameConfig` instead. This alias will be removed in the next major version. */
  readonly "game_config": __TablesBase["gameConfig"];
  /** @deprecated Use `horizonActionReceipt` instead. This alias will be removed in the next major version. */
  readonly "horizon_action_receipt": __TablesBase["horizonActionReceipt"];
  /** @deprecated Use `jingCast` instead. This alias will be removed in the next major version. */
  readonly "jing_cast": __TablesBase["jingCast"];
  /** @deprecated Use `jingDuel` instead. This alias will be removed in the next major version. */
  readonly "jing_duel": __TablesBase["jingDuel"];
  /** @deprecated Use `meleePlay` instead. This alias will be removed in the next major version. */
  readonly "melee_play": __TablesBase["meleePlay"];
  /** @deprecated Use `meleeQueue` instead. This alias will be removed in the next major version. */
  readonly "melee_queue": __TablesBase["meleeQueue"];
  /** @deprecated Use `meleeSeat` instead. This alias will be removed in the next major version. */
  readonly "melee_seat": __TablesBase["meleeSeat"];
  /** @deprecated Use `meleeTable` instead. This alias will be removed in the next major version. */
  readonly "melee_table": __TablesBase["meleeTable"];
  /** @deprecated Use `meleeTrick` instead. This alias will be removed in the next major version. */
  readonly "melee_trick": __TablesBase["meleeTrick"];
  /** @deprecated Use `natalDecan` instead. This alias will be removed in the next major version. */
  readonly "natal_decan": __TablesBase["natalDecan"];
  /** @deprecated Use `oracleCache` instead. This alias will be removed in the next major version. */
  readonly "oracle_cache": __TablesBase["oracleCache"];
  /** @deprecated Use `playerFaucetState` instead. This alias will be removed in the next major version. */
  readonly "player_faucet_state": __TablesBase["playerFaucetState"];
  /** @deprecated Use `processedTx` instead. This alias will be removed in the next major version. */
  readonly "processed_tx": __TablesBase["processedTx"];
  /** @deprecated Use `roundParticipant` instead. This alias will be removed in the next major version. */
  readonly "round_participant": __TablesBase["roundParticipant"];
  /** @deprecated Use `roundState` instead. This alias will be removed in the next major version. */
  readonly "round_state": __TablesBase["roundState"];
  /** @deprecated Use `serviceStatus` instead. This alias will be removed in the next major version. */
  readonly "service_status": __TablesBase["serviceStatus"];
  /** @deprecated Use `starAgent` instead. This alias will be removed in the next major version. */
  readonly "star_agent": __TablesBase["starAgent"];
  /** @deprecated Use `starNode` instead. This alias will be removed in the next major version. */
  readonly "star_node": __TablesBase["starNode"];
  /** @deprecated Use `starStakePool` instead. This alias will be removed in the next major version. */
  readonly "star_stake_pool": __TablesBase["starStakePool"];
  /** @deprecated Use `verifiedSolanaWallet` instead. This alias will be removed in the next major version. */
  readonly "verified_solana_wallet": __TablesBase["verifiedSolanaWallet"];
  /** @deprecated Use `wordDuel` instead. This alias will be removed in the next major version. */
  readonly "word_duel": __TablesBase["wordDuel"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

