// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  lastDailyClaimAt: __t.timestamp().name("last_daily_claim_at"),
  lifetimeClaims: __t.u32().name("lifetime_claims"),
  currentStreakDays: __t.u32().name("current_streak_days"),
  lastClaimYield: __t.array(__t.u32()).name("last_claim_yield"),
});
