// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit 31fd1c8c3346dfec38dfcc2e89c2ecf457cf26ff).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        internal RemoteReducers(DbConnection conn) : base(conn) { }
        internal event Action<ReducerEventContext, Exception>? InternalOnUnhandledReducerError;
    }

    public sealed partial class RemoteProcedures : RemoteBase
    {
        internal RemoteProcedures(DbConnection conn) : base(conn) { }
    }

    public sealed partial class RemoteTables : RemoteTablesBase
    {
        public RemoteTables(DbConnection conn)
        {
            AddTable(AgentChart = new(conn));
            AddTable(Battle = new(conn));
            AddTable(BridgeTransfer = new(conn));
            AddTable(Card = new(conn));
            AddTable(Comet = new(conn));
            AddTable(Constellation = new(conn));
            AddTable(ConstellationBlock = new(conn));
            AddTable(ConstellationLine = new(conn));
            AddTable(ConstellationResolution = new(conn));
            AddTable(ConstellationStar = new(conn));
            AddTable(DeckSlot = new(conn));
            AddTable(Duel = new(conn));
            AddTable(DuelChallenge = new(conn));
            AddTable(DuelQueue = new(conn));
            AddTable(DuelRound = new(conn));
            AddTable(Ephemeris = new(conn));
            AddTable(GameConfig = new(conn));
            AddTable(HorizonActionReceipt = new(conn));
            AddTable(JingCast = new(conn));
            AddTable(JingDuel = new(conn));
            AddTable(JingPool = new(conn));
            AddTable(NatalDecan = new(conn));
            AddTable(OracleCache = new(conn));
            AddTable(OracleReply = new(conn));
            AddTable(OracleRequest = new(conn));
            AddTable(Player = new(conn));
            AddTable(ProcessedTx = new(conn));
            AddTable(RoundParticipant = new(conn));
            AddTable(RoundState = new(conn));
            AddTable(ServiceStatus = new(conn));
            AddTable(StarAgent = new(conn));
            AddTable(StarNode = new(conn));
            AddTable(StarStake = new(conn));
            AddTable(StarStakePool = new(conn));
            AddTable(TraceAttestation = new(conn));
            AddTable(TraceIntent = new(conn));
            AddTable(Trade = new(conn));
            AddTable(VerifiedEvmWallet = new(conn));
            AddTable(VerifiedSolanaWallet = new(conn));
            AddTable(WordDuel = new(conn));
            AddTable(Zone = new(conn));
        }
    }


        public interface IRemoteDbContext : IDbContext<RemoteTables, RemoteReducers, SubscriptionBuilder, RemoteProcedures> {
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError;
        }

        public sealed class EventContext : IEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;

            /// <summary>
            /// The event that caused this callback to run.
            /// </summary>
            public readonly Event<Reducer> Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal EventContext(DbConnection conn, Event<Reducer> Event)
            {
                this.conn = conn;
                this.Event = Event;
            }
        }

        public sealed class ReducerEventContext : IReducerEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The reducer event that caused this callback to run.
            /// </summary>
            public readonly ReducerEvent<Reducer> Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ReducerEventContext(DbConnection conn, ReducerEvent<Reducer> reducerEvent)
            {
                this.conn = conn;
                Event = reducerEvent;
            }
        }

        public sealed class ErrorContext : IErrorContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The <c>Exception</c> that caused this error callback to be run.
            /// </summary>
            public readonly Exception Event;
            Exception IErrorContext.Event {
                get {
                    return Event;
                }
            }

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ErrorContext(DbConnection conn, Exception error)
            {
                this.conn = conn;
                Event = error;
            }
        }

        public sealed class SubscriptionEventContext : ISubscriptionEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal SubscriptionEventContext(DbConnection conn)
            {
                this.conn = conn;
            }
        }

        public sealed class ProcedureEventContext : IProcedureEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The procedure event that caused this callback to run.
            /// </summary>
            public readonly ProcedureEvent Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ProcedureEventContext(DbConnection conn, ProcedureEvent Event)
            {
                this.conn = conn;
                this.Event = Event;
            }
        }

        /// <summary>
        /// Builder-pattern constructor for subscription queries.
        /// </summary>
        public sealed class SubscriptionBuilder
        {
            private readonly IDbConnection conn;

            private event Action<SubscriptionEventContext>? Applied;
            private event Action<ErrorContext, Exception>? Error;

            /// <summary>
            /// Private API, use <c>conn.SubscriptionBuilder()</c> instead.
            /// </summary>
            public SubscriptionBuilder(IDbConnection conn)
            {
                this.conn = conn;
            }

            /// <summary>
            /// Register a callback to run when the subscription is applied.
            /// </summary>
            public SubscriptionBuilder OnApplied(
                Action<SubscriptionEventContext> callback
            )
            {
                Applied += callback;
                return this;
            }

            /// <summary>
            /// Register a callback to run when the subscription fails.
            ///
            /// Note that this callback may run either when attempting to apply the subscription,
            /// in which case <c>Self::on_applied</c> will never run,
            /// or later during the subscription's lifetime if the module's interface changes,
            /// in which case <c>Self::on_applied</c> may have already run.
            /// </summary>
            public SubscriptionBuilder OnError(
                Action<ErrorContext, Exception> callback
            )
            {
                Error += callback;
                return this;
            }
        
            /// <summary>
            /// Add a typed query to this subscription.
            ///
            /// This is the entry point for building subscriptions without writing SQL by hand.
            /// Once a typed query is added, only typed queries may follow (SQL and typed queries cannot be mixed).
            /// </summary>
            public TypedSubscriptionBuilder AddQuery<TRow>(
                Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build
            )
            {
                var typed = new TypedSubscriptionBuilder(conn, Applied, Error);
                return typed.AddQuery(build);
            }

            /// <summary>
            /// Subscribe to the following SQL queries.
            ///
            /// This method returns immediately, with the data not yet added to the DbConnection.
            /// The provided callbacks will be invoked once the data is returned from the remote server.
            /// Data from all the provided queries will be returned at the same time.
            ///
            /// See the SpacetimeDB SQL docs for more information on SQL syntax:
            /// <a href="https://spacetimedb.com/docs/sql">https://spacetimedb.com/docs/sql</a>
            /// </summary>
            public SubscriptionHandle Subscribe(
                string[] querySqls
            ) => new(conn, Applied, Error, querySqls);

            /// <summary>
            /// Subscribe to all rows from all tables.
            ///
            /// This method is intended as a convenience
            /// for applications where client-side memory use and network bandwidth are not concerns.
            /// Applications where these resources are a constraint
            /// should register more precise queries via <c>Self.Subscribe</c>
            /// in order to replicate only the subset of data which the client needs to function.
            ///
            /// This method should not be combined with <c>Self.Subscribe</c> on the same <c>DbConnection</c>.
            /// A connection may either <c>Self.Subscribe</c> to particular queries,
            /// or <c>Self.SubscribeToAllTables</c>, but not both.
            /// Attempting to call <c>Self.Subscribe</c>
            /// on a <c>DbConnection</c> that has previously used <c>Self.SubscribeToAllTables</c>,
            /// or vice versa, may misbehave in any number of ways,
            /// including dropping subscriptions, corrupting the client cache, or panicking.
            /// </summary>
            public SubscriptionHandle SubscribeToAllTables() =>
                new(conn, Applied, Error, QueryBuilder.AllTablesSqlQueries());
        }

        public sealed class SubscriptionHandle : SubscriptionHandleBase<SubscriptionEventContext, ErrorContext> {
            /// <summary>
            /// Internal API. Construct <c>SubscriptionHandle</c>s using <c>conn.SubscriptionBuilder</c>.
            /// </summary>
            public SubscriptionHandle(
                IDbConnection conn,
                Action<SubscriptionEventContext>? onApplied,
                Action<ErrorContext, Exception>? onError,
                string[] querySqls
            ) : base(conn, onApplied, onError, querySqls)
            { }
        }

    public sealed class QueryBuilder
    {
        public From From { get; } = new();

        internal static string[] AllTablesSqlQueries() => new string[]
        {
            new QueryBuilder().From.AgentChart().ToSql(),
            new QueryBuilder().From.Battle().ToSql(),
            new QueryBuilder().From.BridgeTransfer().ToSql(),
            new QueryBuilder().From.Card().ToSql(),
            new QueryBuilder().From.Comet().ToSql(),
            new QueryBuilder().From.Constellation().ToSql(),
            new QueryBuilder().From.ConstellationBlock().ToSql(),
            new QueryBuilder().From.ConstellationLine().ToSql(),
            new QueryBuilder().From.ConstellationResolution().ToSql(),
            new QueryBuilder().From.ConstellationStar().ToSql(),
            new QueryBuilder().From.DeckSlot().ToSql(),
            new QueryBuilder().From.Duel().ToSql(),
            new QueryBuilder().From.DuelChallenge().ToSql(),
            new QueryBuilder().From.DuelQueue().ToSql(),
            new QueryBuilder().From.DuelRound().ToSql(),
            new QueryBuilder().From.Ephemeris().ToSql(),
            new QueryBuilder().From.GameConfig().ToSql(),
            new QueryBuilder().From.HorizonActionReceipt().ToSql(),
            new QueryBuilder().From.JingCast().ToSql(),
            new QueryBuilder().From.JingDuel().ToSql(),
            new QueryBuilder().From.JingPool().ToSql(),
            new QueryBuilder().From.NatalDecan().ToSql(),
            new QueryBuilder().From.OracleCache().ToSql(),
            new QueryBuilder().From.OracleReply().ToSql(),
            new QueryBuilder().From.OracleRequest().ToSql(),
            new QueryBuilder().From.Player().ToSql(),
            new QueryBuilder().From.ProcessedTx().ToSql(),
            new QueryBuilder().From.RoundParticipant().ToSql(),
            new QueryBuilder().From.RoundState().ToSql(),
            new QueryBuilder().From.ServiceStatus().ToSql(),
            new QueryBuilder().From.StarAgent().ToSql(),
            new QueryBuilder().From.StarNode().ToSql(),
            new QueryBuilder().From.StarStake().ToSql(),
            new QueryBuilder().From.StarStakePool().ToSql(),
            new QueryBuilder().From.TraceAttestation().ToSql(),
            new QueryBuilder().From.TraceIntent().ToSql(),
            new QueryBuilder().From.Trade().ToSql(),
            new QueryBuilder().From.VerifiedEvmWallet().ToSql(),
            new QueryBuilder().From.VerifiedSolanaWallet().ToSql(),
            new QueryBuilder().From.WordDuel().ToSql(),
            new QueryBuilder().From.Zone().ToSql(),
        }
        ;
    }

    public sealed class From
    {
        public global::SpacetimeDB.Table<AgentChart, AgentChartCols, AgentChartIxCols> AgentChart() => new("agent_chart", new AgentChartCols("agent_chart"), new AgentChartIxCols("agent_chart"));
        public global::SpacetimeDB.Table<Battle, BattleCols, BattleIxCols> Battle() => new("battle", new BattleCols("battle"), new BattleIxCols("battle"));
        public global::SpacetimeDB.Table<BridgeTransfer, BridgeTransferCols, BridgeTransferIxCols> BridgeTransfer() => new("bridge_transfer", new BridgeTransferCols("bridge_transfer"), new BridgeTransferIxCols("bridge_transfer"));
        public global::SpacetimeDB.Table<Card, CardCols, CardIxCols> Card() => new("card", new CardCols("card"), new CardIxCols("card"));
        public global::SpacetimeDB.Table<Comet, CometCols, CometIxCols> Comet() => new("comet", new CometCols("comet"), new CometIxCols("comet"));
        public global::SpacetimeDB.Table<Constellation, ConstellationCols, ConstellationIxCols> Constellation() => new("constellation", new ConstellationCols("constellation"), new ConstellationIxCols("constellation"));
        public global::SpacetimeDB.Table<ConstellationBlock, ConstellationBlockCols, ConstellationBlockIxCols> ConstellationBlock() => new("constellation_block", new ConstellationBlockCols("constellation_block"), new ConstellationBlockIxCols("constellation_block"));
        public global::SpacetimeDB.Table<ConstellationLine, ConstellationLineCols, ConstellationLineIxCols> ConstellationLine() => new("constellation_line", new ConstellationLineCols("constellation_line"), new ConstellationLineIxCols("constellation_line"));
        public global::SpacetimeDB.Table<ConstellationResolution, ConstellationResolutionCols, ConstellationResolutionIxCols> ConstellationResolution() => new("constellation_resolution", new ConstellationResolutionCols("constellation_resolution"), new ConstellationResolutionIxCols("constellation_resolution"));
        public global::SpacetimeDB.Table<ConstellationStar, ConstellationStarCols, ConstellationStarIxCols> ConstellationStar() => new("constellation_star", new ConstellationStarCols("constellation_star"), new ConstellationStarIxCols("constellation_star"));
        public global::SpacetimeDB.Table<DeckSlot, DeckSlotCols, DeckSlotIxCols> DeckSlot() => new("deck_slot", new DeckSlotCols("deck_slot"), new DeckSlotIxCols("deck_slot"));
        public global::SpacetimeDB.Table<Duel, DuelCols, DuelIxCols> Duel() => new("duel", new DuelCols("duel"), new DuelIxCols("duel"));
        public global::SpacetimeDB.Table<DuelChallenge, DuelChallengeCols, DuelChallengeIxCols> DuelChallenge() => new("duel_challenge", new DuelChallengeCols("duel_challenge"), new DuelChallengeIxCols("duel_challenge"));
        public global::SpacetimeDB.Table<DuelQueue, DuelQueueCols, DuelQueueIxCols> DuelQueue() => new("duel_queue", new DuelQueueCols("duel_queue"), new DuelQueueIxCols("duel_queue"));
        public global::SpacetimeDB.Table<DuelRound, DuelRoundCols, DuelRoundIxCols> DuelRound() => new("duel_round", new DuelRoundCols("duel_round"), new DuelRoundIxCols("duel_round"));
        public global::SpacetimeDB.Table<Ephemeris, EphemerisCols, EphemerisIxCols> Ephemeris() => new("ephemeris", new EphemerisCols("ephemeris"), new EphemerisIxCols("ephemeris"));
        public global::SpacetimeDB.Table<GameConfig, GameConfigCols, GameConfigIxCols> GameConfig() => new("game_config", new GameConfigCols("game_config"), new GameConfigIxCols("game_config"));
        public global::SpacetimeDB.Table<HorizonActionReceipt, HorizonActionReceiptCols, HorizonActionReceiptIxCols> HorizonActionReceipt() => new("horizon_action_receipt", new HorizonActionReceiptCols("horizon_action_receipt"), new HorizonActionReceiptIxCols("horizon_action_receipt"));
        public global::SpacetimeDB.Table<JingCast, JingCastCols, JingCastIxCols> JingCast() => new("jing_cast", new JingCastCols("jing_cast"), new JingCastIxCols("jing_cast"));
        public global::SpacetimeDB.Table<JingDuel, JingDuelCols, JingDuelIxCols> JingDuel() => new("jing_duel", new JingDuelCols("jing_duel"), new JingDuelIxCols("jing_duel"));
        public global::SpacetimeDB.Table<JingPool, JingPoolCols, JingPoolIxCols> JingPool() => new("jing_pool", new JingPoolCols("jing_pool"), new JingPoolIxCols("jing_pool"));
        public global::SpacetimeDB.Table<NatalDecan, NatalDecanCols, NatalDecanIxCols> NatalDecan() => new("natal_decan", new NatalDecanCols("natal_decan"), new NatalDecanIxCols("natal_decan"));
        public global::SpacetimeDB.Table<OracleCache, OracleCacheCols, OracleCacheIxCols> OracleCache() => new("oracle_cache", new OracleCacheCols("oracle_cache"), new OracleCacheIxCols("oracle_cache"));
        public global::SpacetimeDB.Table<OracleReply, OracleReplyCols, OracleReplyIxCols> OracleReply() => new("oracle_reply", new OracleReplyCols("oracle_reply"), new OracleReplyIxCols("oracle_reply"));
        public global::SpacetimeDB.Table<OracleRequest, OracleRequestCols, OracleRequestIxCols> OracleRequest() => new("oracle_request", new OracleRequestCols("oracle_request"), new OracleRequestIxCols("oracle_request"));
        public global::SpacetimeDB.Table<Player, PlayerCols, PlayerIxCols> Player() => new("player", new PlayerCols("player"), new PlayerIxCols("player"));
        public global::SpacetimeDB.Table<ProcessedTx, ProcessedTxCols, ProcessedTxIxCols> ProcessedTx() => new("processed_tx", new ProcessedTxCols("processed_tx"), new ProcessedTxIxCols("processed_tx"));
        public global::SpacetimeDB.Table<RoundParticipant, RoundParticipantCols, RoundParticipantIxCols> RoundParticipant() => new("round_participant", new RoundParticipantCols("round_participant"), new RoundParticipantIxCols("round_participant"));
        public global::SpacetimeDB.Table<RoundState, RoundStateCols, RoundStateIxCols> RoundState() => new("round_state", new RoundStateCols("round_state"), new RoundStateIxCols("round_state"));
        public global::SpacetimeDB.Table<ServiceStatus, ServiceStatusCols, ServiceStatusIxCols> ServiceStatus() => new("service_status", new ServiceStatusCols("service_status"), new ServiceStatusIxCols("service_status"));
        public global::SpacetimeDB.Table<StarAgent, StarAgentCols, StarAgentIxCols> StarAgent() => new("star_agent", new StarAgentCols("star_agent"), new StarAgentIxCols("star_agent"));
        public global::SpacetimeDB.Table<StarNode, StarNodeCols, StarNodeIxCols> StarNode() => new("star_node", new StarNodeCols("star_node"), new StarNodeIxCols("star_node"));
        public global::SpacetimeDB.Table<StarStake, StarStakeCols, StarStakeIxCols> StarStake() => new("star_stake", new StarStakeCols("star_stake"), new StarStakeIxCols("star_stake"));
        public global::SpacetimeDB.Table<StarStakePool, StarStakePoolCols, StarStakePoolIxCols> StarStakePool() => new("star_stake_pool", new StarStakePoolCols("star_stake_pool"), new StarStakePoolIxCols("star_stake_pool"));
        public global::SpacetimeDB.Table<TraceAttestation, TraceAttestationCols, TraceAttestationIxCols> TraceAttestation() => new("trace_attestation", new TraceAttestationCols("trace_attestation"), new TraceAttestationIxCols("trace_attestation"));
        public global::SpacetimeDB.Table<TraceIntent, TraceIntentCols, TraceIntentIxCols> TraceIntent() => new("trace_intent", new TraceIntentCols("trace_intent"), new TraceIntentIxCols("trace_intent"));
        public global::SpacetimeDB.Table<Trade, TradeCols, TradeIxCols> Trade() => new("trade", new TradeCols("trade"), new TradeIxCols("trade"));
        public global::SpacetimeDB.Table<VerifiedEvmWallet, VerifiedEvmWalletCols, VerifiedEvmWalletIxCols> VerifiedEvmWallet() => new("verified_evm_wallet", new VerifiedEvmWalletCols("verified_evm_wallet"), new VerifiedEvmWalletIxCols("verified_evm_wallet"));
        public global::SpacetimeDB.Table<VerifiedSolanaWallet, VerifiedSolanaWalletCols, VerifiedSolanaWalletIxCols> VerifiedSolanaWallet() => new("verified_solana_wallet", new VerifiedSolanaWalletCols("verified_solana_wallet"), new VerifiedSolanaWalletIxCols("verified_solana_wallet"));
        public global::SpacetimeDB.Table<WordDuel, WordDuelCols, WordDuelIxCols> WordDuel() => new("word_duel", new WordDuelCols("word_duel"), new WordDuelIxCols("word_duel"));
        public global::SpacetimeDB.Table<Zone, ZoneCols, ZoneIxCols> Zone() => new("zone", new ZoneCols("zone"), new ZoneIxCols("zone"));
    }

    public sealed class TypedSubscriptionBuilder
    {
        private readonly IDbConnection conn;
        private Action<SubscriptionEventContext>? Applied;
        private Action<ErrorContext, Exception>? Error;
        private readonly List<string> querySqls = new();

        internal TypedSubscriptionBuilder(IDbConnection conn, Action<SubscriptionEventContext>? applied, Action<ErrorContext, Exception>? error)
        {
            this.conn = conn;
            Applied = applied;
            Error = error;
        }

        public TypedSubscriptionBuilder OnApplied(Action<SubscriptionEventContext> callback)
        {
            Applied += callback;
            return this;
        }

        public TypedSubscriptionBuilder OnError(Action<ErrorContext, Exception> callback)
        {
            Error += callback;
            return this;
        }

        public TypedSubscriptionBuilder AddQuery<TRow>(Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build)
        {
            var qb = new QueryBuilder();
            querySqls.Add(build(qb).ToSql());
            return this;
        }

        public SubscriptionHandle Subscribe() => new(conn, Applied, Error, querySqls.ToArray());
    }

    public abstract partial class Reducer
    {
        private Reducer() { }
    }

    public abstract partial class Procedure
    {
        private Procedure() { }
    }

    public sealed class DbConnection : DbConnectionBase<DbConnection, RemoteTables, Reducer>
    {
        public override RemoteTables Db { get; }
        public readonly RemoteReducers Reducers;
        public readonly RemoteProcedures Procedures;

        public DbConnection()
        {
            Db = new(this);
            Reducers = new(this);
            Procedures = new(this);
        }

        protected override IEventContext ToEventContext(Event<Reducer> Event) =>
        new EventContext(this, Event);

        protected override IReducerEventContext ToReducerEventContext(ReducerEvent<Reducer> reducerEvent) =>
        new ReducerEventContext(this, reducerEvent);

        protected override ISubscriptionEventContext MakeSubscriptionEventContext() =>
        new SubscriptionEventContext(this);

        protected override IErrorContext ToErrorContext(Exception exception) =>
        new ErrorContext(this, exception);

        protected override IProcedureEventContext ToProcedureEventContext(ProcedureEvent procedureEvent) =>
        new ProcedureEventContext(this, procedureEvent);

        protected override bool Dispatch(IReducerEventContext context, Reducer reducer)
        {
            var eventContext = (ReducerEventContext)context;
            return reducer switch {
                Reducer.AddStarToConstellation args => Reducers.InvokeAddStarToConstellation(eventContext, args),
                Reducer.AdminAgentCastJing args => Reducers.InvokeAdminAgentCastJing(eventContext, args),
                Reducer.AdminAgentCastWord args => Reducers.InvokeAdminAgentCastWord(eventContext, args),
                Reducer.AdminAgentCounterJing args => Reducers.InvokeAdminAgentCounterJing(eventContext, args),
                Reducer.AdminAgentRecordStarStake args => Reducers.InvokeAdminAgentRecordStarStake(eventContext, args),
                Reducer.AdminAgentRecordStarUnstake args => Reducers.InvokeAdminAgentRecordStarUnstake(eventContext, args),
                Reducer.AdminAgentResolveStarBattle args => Reducers.InvokeAdminAgentResolveStarBattle(eventContext, args),
                Reducer.AnswerDuel args => Reducers.InvokeAnswerDuel(eventContext, args),
                Reducer.AnswerJing args => Reducers.InvokeAnswerJing(eventContext, args),
                Reducer.AnswerOracle args => Reducers.InvokeAnswerOracle(eventContext, args),
                Reducer.AnswerTrace args => Reducers.InvokeAnswerTrace(eventContext, args),
                Reducer.AskOracle args => Reducers.InvokeAskOracle(eventContext, args),
                Reducer.AssertEsmsBridgeReady args => Reducers.InvokeAssertEsmsBridgeReady(eventContext, args),
                Reducer.BackfillDecans args => Reducers.InvokeBackfillDecans(eventContext, args),
                Reducer.BindWalletAddress args => Reducers.InvokeBindWalletAddress(eventContext, args),
                Reducer.BridgeEsmsCrosschain args => Reducers.InvokeBridgeEsmsCrosschain(eventContext, args),
                Reducer.CancelStaleClaim args => Reducers.InvokeCancelStaleClaim(eventContext, args),
                Reducer.CancelTrade args => Reducers.InvokeCancelTrade(eventContext, args),
                Reducer.CastJing args => Reducers.InvokeCastJing(eventContext, args),
                Reducer.CastWord args => Reducers.InvokeCastWord(eventContext, args),
                Reducer.ClaimDuelTimeout args => Reducers.InvokeClaimDuelTimeout(eventContext, args),
                Reducer.ClaimProfile args => Reducers.InvokeClaimProfile(eventContext, args),
                Reducer.CombineCards args => Reducers.InvokeCombineCards(eventContext, args),
                Reducer.CommitDuel args => Reducers.InvokeCommitDuel(eventContext, args),
                Reducer.CompleteEsmsBridge args => Reducers.InvokeCompleteEsmsBridge(eventContext, args),
                Reducer.ConfirmTrade args => Reducers.InvokeConfirmTrade(eventContext, args),
                Reducer.ConfirmYieldClaim args => Reducers.InvokeConfirmYieldClaim(eventContext, args),
                Reducer.CounterJing args => Reducers.InvokeCounterJing(eventContext, args),
                Reducer.CreatePlayer args => Reducers.InvokeCreatePlayer(eventContext, args),
                Reducer.DeployCard args => Reducers.InvokeDeployCard(eventContext, args),
                Reducer.EnqueueDuel args => Reducers.InvokeEnqueueDuel(eventContext, args),
                Reducer.OpenIdentityLink args => Reducers.InvokeOpenIdentityLink(eventContext, args),
                Reducer.ProposeTrade args => Reducers.InvokeProposeTrade(eventContext, args),
                Reducer.PurgeStaleAgents args => Reducers.InvokePurgeStaleAgents(eventContext, args),
                Reducer.PushEphemeris args => Reducers.InvokePushEphemeris(eventContext, args),
                Reducer.RecordStarStake args => Reducers.InvokeRecordStarStake(eventContext, args),
                Reducer.RecordStarUnstake args => Reducers.InvokeRecordStarUnstake(eventContext, args),
                Reducer.ReportServiceHealth args => Reducers.InvokeReportServiceHealth(eventContext, args),
                Reducer.RequestYieldClaim args => Reducers.InvokeRequestYieldClaim(eventContext, args),
                Reducer.ResolveStarBattle args => Reducers.InvokeResolveStarBattle(eventContext, args),
                Reducer.SeedAgentPlayer args => Reducers.InvokeSeedAgentPlayer(eventContext, args),
                Reducer.SetLoadout args => Reducers.InvokeSetLoadout(eventContext, args),
                Reducer.SetLocation args => Reducers.InvokeSetLocation(eventContext, args),
                Reducer.SiegeHorizonStar args => Reducers.InvokeSiegeHorizonStar(eventContext, args),
                Reducer.StardexClaimConstellation args => Reducers.InvokeStardexClaimConstellation(eventContext, args),
                Reducer.StardexFortifyNode args => Reducers.InvokeStardexFortifyNode(eventContext, args),
                Reducer.StrikeStarSingle args => Reducers.InvokeStrikeStarSingle(eventContext, args),
                Reducer.SyncEvmEvent args => Reducers.InvokeSyncEvmEvent(eventContext, args),
                Reducer.SyncSolanaEvent args => Reducers.InvokeSyncSolanaEvent(eventContext, args),
                Reducer.SyncStardexEphemeris args => Reducers.InvokeSyncStardexEphemeris(eventContext, args),
                Reducer.TraceConstellation args => Reducers.InvokeTraceConstellation(eventContext, args),
                Reducer.TransferStarStake args => Reducers.InvokeTransferStarStake(eventContext, args),
                Reducer.VerifyEvmWalletBinding args => Reducers.InvokeVerifyEvmWalletBinding(eventContext, args),
                Reducer.VerifySolanaWalletBinding args => Reducers.InvokeVerifySolanaWalletBinding(eventContext, args),
                _ => throw new ArgumentOutOfRangeException("Reducer", $"Unknown reducer {reducer}")
            };
        }

        public SubscriptionBuilder SubscriptionBuilder() => new(this);
        public event Action<ReducerEventContext, Exception> OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }
    }
}
