//! Constellation liquidity pools — generated by scripts/make_constellations.py
//! DO NOT EDIT BY HAND; re-run the script instead.
//!
//! Each real constellation is a constant-product AMM pool over a pair of ESMS
//! elements (0=Spirit,1=Essence,2=Matter,3=Substance). `pair` is frozen here;
//! only horizon visibility changes live. Mirrors constellations.js.

pub struct ConstellationDef {
    pub id: u16,
    pub abbr: &'static str,
    pub name: &'static str,
    pub elem_a: u8,
    pub elem_b: u8,
    pub degenerate: bool,
    pub fee_bps: u16,
    pub visible_threshold: u16,
    pub members: &'static [u32],
    pub lines: &'static [(u32, u32)],
}

pub const CONSTELLATIONS: &[ConstellationDef] = &[
    ConstellationDef { id: 0, abbr: "Ori", name: "Orion", elem_a: 0, elem_b: 3, degenerate: true, fee_bps: 87, visible_threshold: 3, members: &[24436, 25336, 25930, 26311, 26727, 27366, 27989], lines: &[(27989, 25336), (25336, 25930), (25930, 26311), (26311, 26727), (26727, 27989), (27366, 26727), (24436, 25930), (27366, 24436)] },
    ConstellationDef { id: 1, abbr: "UMa", name: "Ursa Major", elem_a: 0, elem_b: 2, degenerate: false, fee_bps: 121, visible_threshold: 3, members: &[53910, 54061, 58001, 59774, 62956, 65378, 67301], lines: &[(54061, 53910), (53910, 58001), (58001, 59774), (59774, 54061), (59774, 62956), (62956, 65378), (65378, 67301)] },
    ConstellationDef { id: 2, abbr: "Cas", name: "Cassiopeia", elem_a: 1, elem_b: 2, degenerate: true, fee_bps: 181, visible_threshold: 3, members: &[746, 3179, 4427, 6686, 8886], lines: &[(746, 3179), (3179, 4427), (4427, 6686), (6686, 8886)] },
    ConstellationDef { id: 3, abbr: "Cyg", name: "Cygnus", elem_a: 1, elem_b: 3, degenerate: false, fee_bps: 177, visible_threshold: 3, members: &[59803, 95947, 97165, 100453, 102098], lines: &[(102098, 100453), (100453, 59803), (100453, 97165), (100453, 95947)] },
    ConstellationDef { id: 4, abbr: "Lyr", name: "Lyra", elem_a: 1, elem_b: 2, degenerate: true, fee_bps: 224, visible_threshold: 3, members: &[91262, 92420, 93194], lines: &[(91262, 93194), (93194, 92420), (92420, 91262)] },
    ConstellationDef { id: 5, abbr: "Sco", name: "Scorpius", elem_a: 0, elem_b: 3, degenerate: true, fee_bps: 71, visible_threshold: 4, members: &[78265, 78401, 78820, 80763, 82396, 82514, 85696, 85927, 86228], lines: &[(78820, 78401), (78401, 78265), (78401, 80763), (80763, 82396), (82396, 82514), (82514, 86228), (86228, 85927), (85927, 85696)] },
    ConstellationDef { id: 6, abbr: "Leo", name: "Leo", elem_a: 0, elem_b: 2, degenerate: false, fee_bps: 139, visible_threshold: 3, members: &[48455, 49669, 50335, 50583, 54872, 54879, 57632], lines: &[(49669, 50583), (50583, 50335), (50335, 48455), (49669, 54879), (54879, 57632), (57632, 54872), (54872, 54879), (54872, 50583)] },
    ConstellationDef { id: 7, abbr: "Tau", name: "Taurus", elem_a: 0, elem_b: 3, degenerate: true, fee_bps: 216, visible_threshold: 3, members: &[21421, 25428, 26451], lines: &[(21421, 25428), (21421, 26451)] },
    ConstellationDef { id: 8, abbr: "Gem", name: "Gemini", elem_a: 1, elem_b: 2, degenerate: true, fee_bps: 172, visible_threshold: 3, members: &[31681, 32246, 35550, 36850, 37826], lines: &[(36850, 37826), (37826, 35550), (35550, 31681), (36850, 32246), (32246, 31681)] },
    ConstellationDef { id: 9, abbr: "CMa", name: "Canis Major", elem_a: 1, elem_b: 2, degenerate: true, fee_bps: 122, visible_threshold: 3, members: &[30122, 30324, 32349, 33579, 34444, 35904], lines: &[(30324, 32349), (32349, 34444), (34444, 33579), (34444, 35904), (33579, 30122)] },
    ConstellationDef { id: 10, abbr: "Boo", name: "Bootes", elem_a: 0, elem_b: 3, degenerate: true, fee_bps: 156, visible_threshold: 3, members: &[67927, 69673, 71075, 72105, 73555, 74666], lines: &[(69673, 72105), (72105, 71075), (71075, 73555), (73555, 74666), (69673, 67927), (67927, 71075)] },
    ConstellationDef { id: 11, abbr: "Cru", name: "Crux", elem_a: 1, elem_b: 2, degenerate: true, fee_bps: 182, visible_threshold: 3, members: &[59747, 60718, 61084, 62434], lines: &[(60718, 61084), (62434, 59747)] },
];
