// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddStarToConstellationHandler(ReducerEventContext ctx, ushort constellationId, uint hipId);
        public event AddStarToConstellationHandler? OnAddStarToConstellation;

        public void AddStarToConstellation(ushort constellationId, uint hipId)
        {
            conn.InternalCallReducer(new Reducer.AddStarToConstellation(constellationId, hipId));
        }

        public bool InvokeAddStarToConstellation(ReducerEventContext ctx, Reducer.AddStarToConstellation args)
        {
            if (OnAddStarToConstellation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddStarToConstellation(
                ctx,
                args.ConstellationId,
                args.HipId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddStarToConstellation : Reducer, IReducerArgs
        {
            [DataMember(Name = "constellation_id")]
            public ushort ConstellationId;
            [DataMember(Name = "hip_id")]
            public uint HipId;

            public AddStarToConstellation(
                ushort ConstellationId,
                uint HipId
            )
            {
                this.ConstellationId = ConstellationId;
                this.HipId = HipId;
            }

            public AddStarToConstellation()
            {
            }

            string IReducerArgs.ReducerName => "add_star_to_constellation";
        }
    }
}
