// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAgentCounterJingHandler(ReducerEventContext ctx, string agentKey, ulong duelId, SpacetimeDB.Types.JingMove mv);
        public event AdminAgentCounterJingHandler? OnAdminAgentCounterJing;

        public void AdminAgentCounterJing(string agentKey, ulong duelId, SpacetimeDB.Types.JingMove mv)
        {
            conn.InternalCallReducer(new Reducer.AdminAgentCounterJing(agentKey, duelId, mv));
        }

        public bool InvokeAdminAgentCounterJing(ReducerEventContext ctx, Reducer.AdminAgentCounterJing args)
        {
            if (OnAdminAgentCounterJing == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAgentCounterJing(
                ctx,
                args.AgentKey,
                args.DuelId,
                args.Mv
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAgentCounterJing : Reducer, IReducerArgs
        {
            [DataMember(Name = "agent_key")]
            public string AgentKey;
            [DataMember(Name = "duel_id")]
            public ulong DuelId;
            [DataMember(Name = "mv")]
            public JingMove Mv;

            public AdminAgentCounterJing(
                string AgentKey,
                ulong DuelId,
                JingMove Mv
            )
            {
                this.AgentKey = AgentKey;
                this.DuelId = DuelId;
                this.Mv = Mv;
            }

            public AdminAgentCounterJing()
            {
                this.AgentKey = "";
            }

            string IReducerArgs.ReducerName => "admin_agent_counter_jing";
        }
    }
}
