// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAgentResolveStarBattleHandler(ReducerEventContext ctx, string agentKey, uint hipId, SpacetimeDB.Types.BattleLog log);
        public event AdminAgentResolveStarBattleHandler? OnAdminAgentResolveStarBattle;

        public void AdminAgentResolveStarBattle(string agentKey, uint hipId, SpacetimeDB.Types.BattleLog log)
        {
            conn.InternalCallReducer(new Reducer.AdminAgentResolveStarBattle(agentKey, hipId, log));
        }

        public bool InvokeAdminAgentResolveStarBattle(ReducerEventContext ctx, Reducer.AdminAgentResolveStarBattle args)
        {
            if (OnAdminAgentResolveStarBattle == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAgentResolveStarBattle(
                ctx,
                args.AgentKey,
                args.HipId,
                args.Log
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAgentResolveStarBattle : Reducer, IReducerArgs
        {
            [DataMember(Name = "agent_key")]
            public string AgentKey;
            [DataMember(Name = "hip_id")]
            public uint HipId;
            [DataMember(Name = "log")]
            public BattleLog Log;

            public AdminAgentResolveStarBattle(
                string AgentKey,
                uint HipId,
                BattleLog Log
            )
            {
                this.AgentKey = AgentKey;
                this.HipId = HipId;
                this.Log = Log;
            }

            public AdminAgentResolveStarBattle()
            {
                this.AgentKey = "";
                this.Log = new();
            }

            string IReducerArgs.ReducerName => "admin_agent_resolve_star_battle";
        }
    }
}
