// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAgentRecordStarUnstakeHandler(ReducerEventContext ctx, string agentKey, ulong stakeId);
        public event AdminAgentRecordStarUnstakeHandler? OnAdminAgentRecordStarUnstake;

        public void AdminAgentRecordStarUnstake(string agentKey, ulong stakeId)
        {
            conn.InternalCallReducer(new Reducer.AdminAgentRecordStarUnstake(agentKey, stakeId));
        }

        public bool InvokeAdminAgentRecordStarUnstake(ReducerEventContext ctx, Reducer.AdminAgentRecordStarUnstake args)
        {
            if (OnAdminAgentRecordStarUnstake == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAgentRecordStarUnstake(
                ctx,
                args.AgentKey,
                args.StakeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAgentRecordStarUnstake : Reducer, IReducerArgs
        {
            [DataMember(Name = "agent_key")]
            public string AgentKey;
            [DataMember(Name = "stake_id")]
            public ulong StakeId;

            public AdminAgentRecordStarUnstake(
                string AgentKey,
                ulong StakeId
            )
            {
                this.AgentKey = AgentKey;
                this.StakeId = StakeId;
            }

            public AdminAgentRecordStarUnstake()
            {
                this.AgentKey = "";
            }

            string IReducerArgs.ReducerName => "admin_agent_record_star_unstake";
        }
    }
}
