// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAgentRecordStarStakeHandler(ReducerEventContext ctx, string agentKey, uint starId, ulong principalUsdc, U128 shares);
        public event AdminAgentRecordStarStakeHandler? OnAdminAgentRecordStarStake;

        public void AdminAgentRecordStarStake(string agentKey, uint starId, ulong principalUsdc, U128 shares)
        {
            conn.InternalCallReducer(new Reducer.AdminAgentRecordStarStake(agentKey, starId, principalUsdc, shares));
        }

        public bool InvokeAdminAgentRecordStarStake(ReducerEventContext ctx, Reducer.AdminAgentRecordStarStake args)
        {
            if (OnAdminAgentRecordStarStake == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAgentRecordStarStake(
                ctx,
                args.AgentKey,
                args.StarId,
                args.PrincipalUsdc,
                args.Shares
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAgentRecordStarStake : Reducer, IReducerArgs
        {
            [DataMember(Name = "agent_key")]
            public string AgentKey;
            [DataMember(Name = "star_id")]
            public uint StarId;
            [DataMember(Name = "principal_usdc")]
            public ulong PrincipalUsdc;
            [DataMember(Name = "shares")]
            public U128 Shares;

            public AdminAgentRecordStarStake(
                string AgentKey,
                uint StarId,
                ulong PrincipalUsdc,
                U128 Shares
            )
            {
                this.AgentKey = AgentKey;
                this.StarId = StarId;
                this.PrincipalUsdc = PrincipalUsdc;
                this.Shares = Shares;
            }

            public AdminAgentRecordStarStake()
            {
                this.AgentKey = "";
            }

            string IReducerArgs.ReducerName => "admin_agent_record_star_stake";
        }
    }
}
