// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAgentCastWordHandler(ReducerEventContext ctx, string agentKey, string word, SpacetimeDB.Types.Planet opponent);
        public event AdminAgentCastWordHandler? OnAdminAgentCastWord;

        public void AdminAgentCastWord(string agentKey, string word, SpacetimeDB.Types.Planet opponent)
        {
            conn.InternalCallReducer(new Reducer.AdminAgentCastWord(agentKey, word, opponent));
        }

        public bool InvokeAdminAgentCastWord(ReducerEventContext ctx, Reducer.AdminAgentCastWord args)
        {
            if (OnAdminAgentCastWord == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAgentCastWord(
                ctx,
                args.AgentKey,
                args.Word,
                args.Opponent
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAgentCastWord : Reducer, IReducerArgs
        {
            [DataMember(Name = "agent_key")]
            public string AgentKey;
            [DataMember(Name = "word")]
            public string Word;
            [DataMember(Name = "opponent")]
            public Planet Opponent;

            public AdminAgentCastWord(
                string AgentKey,
                string Word,
                Planet Opponent
            )
            {
                this.AgentKey = AgentKey;
                this.Word = Word;
                this.Opponent = Opponent;
            }

            public AdminAgentCastWord()
            {
                this.AgentKey = "";
                this.Word = "";
            }

            string IReducerArgs.ReducerName => "admin_agent_cast_word";
        }
    }
}
