// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAgentCastJingHandler(ReducerEventContext ctx, string agentKey, SpacetimeDB.Types.JingMove mv, SpacetimeDB.Identity? targetPlayer, SpacetimeDB.Types.Planet? targetAgent);
        public event AdminAgentCastJingHandler? OnAdminAgentCastJing;

        public void AdminAgentCastJing(string agentKey, SpacetimeDB.Types.JingMove mv, SpacetimeDB.Identity? targetPlayer, SpacetimeDB.Types.Planet? targetAgent)
        {
            conn.InternalCallReducer(new Reducer.AdminAgentCastJing(agentKey, mv, targetPlayer, targetAgent));
        }

        public bool InvokeAdminAgentCastJing(ReducerEventContext ctx, Reducer.AdminAgentCastJing args)
        {
            if (OnAdminAgentCastJing == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAgentCastJing(
                ctx,
                args.AgentKey,
                args.Mv,
                args.TargetPlayer,
                args.TargetAgent
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAgentCastJing : Reducer, IReducerArgs
        {
            [DataMember(Name = "agent_key")]
            public string AgentKey;
            [DataMember(Name = "mv")]
            public JingMove Mv;
            [DataMember(Name = "target_player")]
            public SpacetimeDB.Identity? TargetPlayer;
            [DataMember(Name = "target_agent")]
            public Planet? TargetAgent;

            public AdminAgentCastJing(
                string AgentKey,
                JingMove Mv,
                SpacetimeDB.Identity? TargetPlayer,
                Planet? TargetAgent
            )
            {
                this.AgentKey = AgentKey;
                this.Mv = Mv;
                this.TargetPlayer = TargetPlayer;
                this.TargetAgent = TargetAgent;
            }

            public AdminAgentCastJing()
            {
                this.AgentKey = "";
            }

            string IReducerArgs.ReducerName => "admin_agent_cast_jing";
        }
    }
}
