// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AnswerJingHandler(ReducerEventContext ctx, ulong duelId, SpacetimeDB.Types.JingMove agentMove, string voice);
        public event AnswerJingHandler? OnAnswerJing;

        public void AnswerJing(ulong duelId, SpacetimeDB.Types.JingMove agentMove, string voice)
        {
            conn.InternalCallReducer(new Reducer.AnswerJing(duelId, agentMove, voice));
        }

        public bool InvokeAnswerJing(ReducerEventContext ctx, Reducer.AnswerJing args)
        {
            if (OnAnswerJing == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAnswerJing(
                ctx,
                args.DuelId,
                args.AgentMove,
                args.Voice
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AnswerJing : Reducer, IReducerArgs
        {
            [DataMember(Name = "duel_id")]
            public ulong DuelId;
            [DataMember(Name = "agent_move")]
            public JingMove AgentMove;
            [DataMember(Name = "voice")]
            public string Voice;

            public AnswerJing(
                ulong DuelId,
                JingMove AgentMove,
                string Voice
            )
            {
                this.DuelId = DuelId;
                this.AgentMove = AgentMove;
                this.Voice = Voice;
            }

            public AnswerJing()
            {
                this.Voice = "";
            }

            string IReducerArgs.ReducerName => "answer_jing";
        }
    }
}
