// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AnswerDuelHandler(ReducerEventContext ctx, ulong challengeId, string agentWord, string agentRationale, uint agentScore);
        public event AnswerDuelHandler? OnAnswerDuel;

        public void AnswerDuel(ulong challengeId, string agentWord, string agentRationale, uint agentScore)
        {
            conn.InternalCallReducer(new Reducer.AnswerDuel(challengeId, agentWord, agentRationale, agentScore));
        }

        public bool InvokeAnswerDuel(ReducerEventContext ctx, Reducer.AnswerDuel args)
        {
            if (OnAnswerDuel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAnswerDuel(
                ctx,
                args.ChallengeId,
                args.AgentWord,
                args.AgentRationale,
                args.AgentScore
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AnswerDuel : Reducer, IReducerArgs
        {
            [DataMember(Name = "challenge_id")]
            public ulong ChallengeId;
            [DataMember(Name = "agent_word")]
            public string AgentWord;
            [DataMember(Name = "agent_rationale")]
            public string AgentRationale;
            [DataMember(Name = "agent_score")]
            public uint AgentScore;

            public AnswerDuel(
                ulong ChallengeId,
                string AgentWord,
                string AgentRationale,
                uint AgentScore
            )
            {
                this.ChallengeId = ChallengeId;
                this.AgentWord = AgentWord;
                this.AgentRationale = AgentRationale;
                this.AgentScore = AgentScore;
            }

            public AnswerDuel()
            {
                this.AgentWord = "";
                this.AgentRationale = "";
            }

            string IReducerArgs.ReducerName => "answer_duel";
        }
    }
}
