// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AnswerOracleHandler(ReducerEventContext ctx, ulong requestId, string text, string model);
        public event AnswerOracleHandler? OnAnswerOracle;

        public void AnswerOracle(ulong requestId, string text, string model)
        {
            conn.InternalCallReducer(new Reducer.AnswerOracle(requestId, text, model));
        }

        public bool InvokeAnswerOracle(ReducerEventContext ctx, Reducer.AnswerOracle args)
        {
            if (OnAnswerOracle == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAnswerOracle(
                ctx,
                args.RequestId,
                args.Text,
                args.Model
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AnswerOracle : Reducer, IReducerArgs
        {
            [DataMember(Name = "request_id")]
            public ulong RequestId;
            [DataMember(Name = "text")]
            public string Text;
            [DataMember(Name = "model")]
            public string Model;

            public AnswerOracle(
                ulong RequestId,
                string Text,
                string Model
            )
            {
                this.RequestId = RequestId;
                this.Text = Text;
                this.Model = Model;
            }

            public AnswerOracle()
            {
                this.Text = "";
                this.Model = "";
            }

            string IReducerArgs.ReducerName => "answer_oracle";
        }
    }
}
