// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AnswerTraceHandler(ReducerEventContext ctx, ulong intentId, string regionCommit, byte visibleStars, ulong nonce, ulong deadline, string signature);
        public event AnswerTraceHandler? OnAnswerTrace;

        public void AnswerTrace(ulong intentId, string regionCommit, byte visibleStars, ulong nonce, ulong deadline, string signature)
        {
            conn.InternalCallReducer(new Reducer.AnswerTrace(intentId, regionCommit, visibleStars, nonce, deadline, signature));
        }

        public bool InvokeAnswerTrace(ReducerEventContext ctx, Reducer.AnswerTrace args)
        {
            if (OnAnswerTrace == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAnswerTrace(
                ctx,
                args.IntentId,
                args.RegionCommit,
                args.VisibleStars,
                args.Nonce,
                args.Deadline,
                args.Signature
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AnswerTrace : Reducer, IReducerArgs
        {
            [DataMember(Name = "intent_id")]
            public ulong IntentId;
            [DataMember(Name = "region_commit")]
            public string RegionCommit;
            [DataMember(Name = "visible_stars")]
            public byte VisibleStars;
            [DataMember(Name = "nonce")]
            public ulong Nonce;
            [DataMember(Name = "deadline")]
            public ulong Deadline;
            [DataMember(Name = "signature")]
            public string Signature;

            public AnswerTrace(
                ulong IntentId,
                string RegionCommit,
                byte VisibleStars,
                ulong Nonce,
                ulong Deadline,
                string Signature
            )
            {
                this.IntentId = IntentId;
                this.RegionCommit = RegionCommit;
                this.VisibleStars = VisibleStars;
                this.Nonce = Nonce;
                this.Deadline = Deadline;
                this.Signature = Signature;
            }

            public AnswerTrace()
            {
                this.RegionCommit = "";
                this.Signature = "";
            }

            string IReducerArgs.ReducerName => "answer_trace";
        }
    }
}
