// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AskOracleHandler(ReducerEventContext ctx, string question, string context, bool cacheable);
        public event AskOracleHandler? OnAskOracle;

        public void AskOracle(string question, string context, bool cacheable)
        {
            conn.InternalCallReducer(new Reducer.AskOracle(question, context, cacheable));
        }

        public bool InvokeAskOracle(ReducerEventContext ctx, Reducer.AskOracle args)
        {
            if (OnAskOracle == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAskOracle(
                ctx,
                args.Question,
                args.Context,
                args.Cacheable
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AskOracle : Reducer, IReducerArgs
        {
            [DataMember(Name = "question")]
            public string Question;
            [DataMember(Name = "context")]
            public string Context;
            [DataMember(Name = "cacheable")]
            public bool Cacheable;

            public AskOracle(
                string Question,
                string Context,
                bool Cacheable
            )
            {
                this.Question = Question;
                this.Context = Context;
                this.Cacheable = Cacheable;
            }

            public AskOracle()
            {
                this.Question = "";
                this.Context = "";
            }

            string IReducerArgs.ReducerName => "ask_oracle";
        }
    }
}
