// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AssertEsmsBridgeReadyHandler(ReducerEventContext ctx, string sourceChain, string targetChain, byte elementId, U128 amount);
        public event AssertEsmsBridgeReadyHandler? OnAssertEsmsBridgeReady;

        public void AssertEsmsBridgeReady(string sourceChain, string targetChain, byte elementId, U128 amount)
        {
            conn.InternalCallReducer(new Reducer.AssertEsmsBridgeReady(sourceChain, targetChain, elementId, amount));
        }

        public bool InvokeAssertEsmsBridgeReady(ReducerEventContext ctx, Reducer.AssertEsmsBridgeReady args)
        {
            if (OnAssertEsmsBridgeReady == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAssertEsmsBridgeReady(
                ctx,
                args.SourceChain,
                args.TargetChain,
                args.ElementId,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AssertEsmsBridgeReady : Reducer, IReducerArgs
        {
            [DataMember(Name = "source_chain")]
            public string SourceChain;
            [DataMember(Name = "target_chain")]
            public string TargetChain;
            [DataMember(Name = "element_id")]
            public byte ElementId;
            [DataMember(Name = "amount")]
            public U128 Amount;

            public AssertEsmsBridgeReady(
                string SourceChain,
                string TargetChain,
                byte ElementId,
                U128 Amount
            )
            {
                this.SourceChain = SourceChain;
                this.TargetChain = TargetChain;
                this.ElementId = ElementId;
                this.Amount = Amount;
            }

            public AssertEsmsBridgeReady()
            {
                this.SourceChain = "";
                this.TargetChain = "";
            }

            string IReducerArgs.ReducerName => "assert_esms_bridge_ready";
        }
    }
}
