// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BindWalletAddressHandler(ReducerEventContext ctx, string? evmAddress, string? solanaPubkey);
        public event BindWalletAddressHandler? OnBindWalletAddress;

        public void BindWalletAddress(string? evmAddress, string? solanaPubkey)
        {
            conn.InternalCallReducer(new Reducer.BindWalletAddress(evmAddress, solanaPubkey));
        }

        public bool InvokeBindWalletAddress(ReducerEventContext ctx, Reducer.BindWalletAddress args)
        {
            if (OnBindWalletAddress == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBindWalletAddress(
                ctx,
                args.EvmAddress,
                args.SolanaPubkey
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BindWalletAddress : Reducer, IReducerArgs
        {
            [DataMember(Name = "evm_address")]
            public string? EvmAddress;
            [DataMember(Name = "solana_pubkey")]
            public string? SolanaPubkey;

            public BindWalletAddress(
                string? EvmAddress,
                string? SolanaPubkey
            )
            {
                this.EvmAddress = EvmAddress;
                this.SolanaPubkey = SolanaPubkey;
            }

            public BindWalletAddress()
            {
            }

            string IReducerArgs.ReducerName => "bind_wallet_address";
        }
    }
}
