// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BridgeEsmsCrosschainHandler(ReducerEventContext ctx, string burnTxHash, string sourceChain, string targetChain, byte elementId, U128 amount);
        public event BridgeEsmsCrosschainHandler? OnBridgeEsmsCrosschain;

        public void BridgeEsmsCrosschain(string burnTxHash, string sourceChain, string targetChain, byte elementId, U128 amount)
        {
            conn.InternalCallReducer(new Reducer.BridgeEsmsCrosschain(burnTxHash, sourceChain, targetChain, elementId, amount));
        }

        public bool InvokeBridgeEsmsCrosschain(ReducerEventContext ctx, Reducer.BridgeEsmsCrosschain args)
        {
            if (OnBridgeEsmsCrosschain == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBridgeEsmsCrosschain(
                ctx,
                args.BurnTxHash,
                args.SourceChain,
                args.TargetChain,
                args.ElementId,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BridgeEsmsCrosschain : Reducer, IReducerArgs
        {
            [DataMember(Name = "burn_tx_hash")]
            public string BurnTxHash;
            [DataMember(Name = "source_chain")]
            public string SourceChain;
            [DataMember(Name = "target_chain")]
            public string TargetChain;
            [DataMember(Name = "element_id")]
            public byte ElementId;
            [DataMember(Name = "amount")]
            public U128 Amount;

            public BridgeEsmsCrosschain(
                string BurnTxHash,
                string SourceChain,
                string TargetChain,
                byte ElementId,
                U128 Amount
            )
            {
                this.BurnTxHash = BurnTxHash;
                this.SourceChain = SourceChain;
                this.TargetChain = TargetChain;
                this.ElementId = ElementId;
                this.Amount = Amount;
            }

            public BridgeEsmsCrosschain()
            {
                this.BurnTxHash = "";
                this.SourceChain = "";
                this.TargetChain = "";
            }

            string IReducerArgs.ReducerName => "bridge_esms_crosschain";
        }
    }
}
