// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CancelTradeHandler(ReducerEventContext ctx, ulong tradeId);
        public event CancelTradeHandler? OnCancelTrade;

        public void CancelTrade(ulong tradeId)
        {
            conn.InternalCallReducer(new Reducer.CancelTrade(tradeId));
        }

        public bool InvokeCancelTrade(ReducerEventContext ctx, Reducer.CancelTrade args)
        {
            if (OnCancelTrade == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCancelTrade(
                ctx,
                args.TradeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CancelTrade : Reducer, IReducerArgs
        {
            [DataMember(Name = "trade_id")]
            public ulong TradeId;

            public CancelTrade(ulong TradeId)
            {
                this.TradeId = TradeId;
            }

            public CancelTrade()
            {
            }

            string IReducerArgs.ReducerName => "cancel_trade";
        }
    }
}
