// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CastJingHandler(ReducerEventContext ctx, SpacetimeDB.Types.JingMove mv, SpacetimeDB.Identity? targetPlayer, SpacetimeDB.Types.Planet? targetAgent);
        public event CastJingHandler? OnCastJing;

        public void CastJing(SpacetimeDB.Types.JingMove mv, SpacetimeDB.Identity? targetPlayer, SpacetimeDB.Types.Planet? targetAgent)
        {
            conn.InternalCallReducer(new Reducer.CastJing(mv, targetPlayer, targetAgent));
        }

        public bool InvokeCastJing(ReducerEventContext ctx, Reducer.CastJing args)
        {
            if (OnCastJing == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCastJing(
                ctx,
                args.Mv,
                args.TargetPlayer,
                args.TargetAgent
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CastJing : Reducer, IReducerArgs
        {
            [DataMember(Name = "mv")]
            public JingMove Mv;
            [DataMember(Name = "target_player")]
            public SpacetimeDB.Identity? TargetPlayer;
            [DataMember(Name = "target_agent")]
            public Planet? TargetAgent;

            public CastJing(
                JingMove Mv,
                SpacetimeDB.Identity? TargetPlayer,
                Planet? TargetAgent
            )
            {
                this.Mv = Mv;
                this.TargetPlayer = TargetPlayer;
                this.TargetAgent = TargetAgent;
            }

            public CastJing()
            {
            }

            string IReducerArgs.ReducerName => "cast_jing";
        }
    }
}
