// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimProfileHandler(ReducerEventContext ctx, string code);
        public event ClaimProfileHandler? OnClaimProfile;

        public void ClaimProfile(string code)
        {
            conn.InternalCallReducer(new Reducer.ClaimProfile(code));
        }

        public bool InvokeClaimProfile(ReducerEventContext ctx, Reducer.ClaimProfile args)
        {
            if (OnClaimProfile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimProfile(
                ctx,
                args.Code
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimProfile : Reducer, IReducerArgs
        {
            [DataMember(Name = "code")]
            public string Code;

            public ClaimProfile(string Code)
            {
                this.Code = Code;
            }

            public ClaimProfile()
            {
                this.Code = "";
            }

            string IReducerArgs.ReducerName => "claim_profile";
        }
    }
}
