// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimDuelTimeoutHandler(ReducerEventContext ctx, ulong duelId);
        public event ClaimDuelTimeoutHandler? OnClaimDuelTimeout;

        public void ClaimDuelTimeout(ulong duelId)
        {
            conn.InternalCallReducer(new Reducer.ClaimDuelTimeout(duelId));
        }

        public bool InvokeClaimDuelTimeout(ReducerEventContext ctx, Reducer.ClaimDuelTimeout args)
        {
            if (OnClaimDuelTimeout == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimDuelTimeout(
                ctx,
                args.DuelId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimDuelTimeout : Reducer, IReducerArgs
        {
            [DataMember(Name = "duel_id")]
            public ulong DuelId;

            public ClaimDuelTimeout(ulong DuelId)
            {
                this.DuelId = DuelId;
            }

            public ClaimDuelTimeout()
            {
            }

            string IReducerArgs.ReducerName => "claim_duel_timeout";
        }
    }
}
