// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CombineCardsHandler(ReducerEventContext ctx, ulong keepId, ulong consumeId);
        public event CombineCardsHandler? OnCombineCards;

        public void CombineCards(ulong keepId, ulong consumeId)
        {
            conn.InternalCallReducer(new Reducer.CombineCards(keepId, consumeId));
        }

        public bool InvokeCombineCards(ReducerEventContext ctx, Reducer.CombineCards args)
        {
            if (OnCombineCards == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCombineCards(
                ctx,
                args.KeepId,
                args.ConsumeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CombineCards : Reducer, IReducerArgs
        {
            [DataMember(Name = "keep_id")]
            public ulong KeepId;
            [DataMember(Name = "consume_id")]
            public ulong ConsumeId;

            public CombineCards(
                ulong KeepId,
                ulong ConsumeId
            )
            {
                this.KeepId = KeepId;
                this.ConsumeId = ConsumeId;
            }

            public CombineCards()
            {
            }

            string IReducerArgs.ReducerName => "combine_cards";
        }
    }
}
