// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CommitDuelHandler(ReducerEventContext ctx, ulong duelId, ulong lane0, ulong lane1, ulong lane2);
        public event CommitDuelHandler? OnCommitDuel;

        public void CommitDuel(ulong duelId, ulong lane0, ulong lane1, ulong lane2)
        {
            conn.InternalCallReducer(new Reducer.CommitDuel(duelId, lane0, lane1, lane2));
        }

        public bool InvokeCommitDuel(ReducerEventContext ctx, Reducer.CommitDuel args)
        {
            if (OnCommitDuel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCommitDuel(
                ctx,
                args.DuelId,
                args.Lane0,
                args.Lane1,
                args.Lane2
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CommitDuel : Reducer, IReducerArgs
        {
            [DataMember(Name = "duel_id")]
            public ulong DuelId;
            [DataMember(Name = "lane_0")]
            public ulong Lane0;
            [DataMember(Name = "lane_1")]
            public ulong Lane1;
            [DataMember(Name = "lane_2")]
            public ulong Lane2;

            public CommitDuel(
                ulong DuelId,
                ulong Lane0,
                ulong Lane1,
                ulong Lane2
            )
            {
                this.DuelId = DuelId;
                this.Lane0 = Lane0;
                this.Lane1 = Lane1;
                this.Lane2 = Lane2;
            }

            public CommitDuel()
            {
            }

            string IReducerArgs.ReducerName => "commit_duel";
        }
    }
}
