// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CompleteEsmsBridgeHandler(ReducerEventContext ctx, string burnTxHash, string destinationTxHash);
        public event CompleteEsmsBridgeHandler? OnCompleteEsmsBridge;

        public void CompleteEsmsBridge(string burnTxHash, string destinationTxHash)
        {
            conn.InternalCallReducer(new Reducer.CompleteEsmsBridge(burnTxHash, destinationTxHash));
        }

        public bool InvokeCompleteEsmsBridge(ReducerEventContext ctx, Reducer.CompleteEsmsBridge args)
        {
            if (OnCompleteEsmsBridge == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCompleteEsmsBridge(
                ctx,
                args.BurnTxHash,
                args.DestinationTxHash
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CompleteEsmsBridge : Reducer, IReducerArgs
        {
            [DataMember(Name = "burn_tx_hash")]
            public string BurnTxHash;
            [DataMember(Name = "destination_tx_hash")]
            public string DestinationTxHash;

            public CompleteEsmsBridge(
                string BurnTxHash,
                string DestinationTxHash
            )
            {
                this.BurnTxHash = BurnTxHash;
                this.DestinationTxHash = DestinationTxHash;
            }

            public CompleteEsmsBridge()
            {
                this.BurnTxHash = "";
                this.DestinationTxHash = "";
            }

            string IReducerArgs.ReducerName => "complete_esms_bridge";
        }
    }
}
