// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ConfirmYieldClaimHandler(ReducerEventContext ctx, string txHash, ulong stakeId, ulong claimNonce);
        public event ConfirmYieldClaimHandler? OnConfirmYieldClaim;

        public void ConfirmYieldClaim(string txHash, ulong stakeId, ulong claimNonce)
        {
            conn.InternalCallReducer(new Reducer.ConfirmYieldClaim(txHash, stakeId, claimNonce));
        }

        public bool InvokeConfirmYieldClaim(ReducerEventContext ctx, Reducer.ConfirmYieldClaim args)
        {
            if (OnConfirmYieldClaim == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnConfirmYieldClaim(
                ctx,
                args.TxHash,
                args.StakeId,
                args.ClaimNonce
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ConfirmYieldClaim : Reducer, IReducerArgs
        {
            [DataMember(Name = "tx_hash")]
            public string TxHash;
            [DataMember(Name = "stake_id")]
            public ulong StakeId;
            [DataMember(Name = "claim_nonce")]
            public ulong ClaimNonce;

            public ConfirmYieldClaim(
                string TxHash,
                ulong StakeId,
                ulong ClaimNonce
            )
            {
                this.TxHash = TxHash;
                this.StakeId = StakeId;
                this.ClaimNonce = ClaimNonce;
            }

            public ConfirmYieldClaim()
            {
                this.TxHash = "";
            }

            string IReducerArgs.ReducerName => "confirm_yield_claim";
        }
    }
}
