// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ConfirmTradeHandler(ReducerEventContext ctx, ulong tradeId);
        public event ConfirmTradeHandler? OnConfirmTrade;

        public void ConfirmTrade(ulong tradeId)
        {
            conn.InternalCallReducer(new Reducer.ConfirmTrade(tradeId));
        }

        public bool InvokeConfirmTrade(ReducerEventContext ctx, Reducer.ConfirmTrade args)
        {
            if (OnConfirmTrade == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnConfirmTrade(
                ctx,
                args.TradeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ConfirmTrade : Reducer, IReducerArgs
        {
            [DataMember(Name = "trade_id")]
            public ulong TradeId;

            public ConfirmTrade(ulong TradeId)
            {
                this.TradeId = TradeId;
            }

            public ConfirmTrade()
            {
            }

            string IReducerArgs.ReducerName => "confirm_trade";
        }
    }
}
