// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CounterJingHandler(ReducerEventContext ctx, ulong duelId, SpacetimeDB.Types.JingMove mv);
        public event CounterJingHandler? OnCounterJing;

        public void CounterJing(ulong duelId, SpacetimeDB.Types.JingMove mv)
        {
            conn.InternalCallReducer(new Reducer.CounterJing(duelId, mv));
        }

        public bool InvokeCounterJing(ReducerEventContext ctx, Reducer.CounterJing args)
        {
            if (OnCounterJing == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCounterJing(
                ctx,
                args.DuelId,
                args.Mv
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CounterJing : Reducer, IReducerArgs
        {
            [DataMember(Name = "duel_id")]
            public ulong DuelId;
            [DataMember(Name = "mv")]
            public JingMove Mv;

            public CounterJing(
                ulong DuelId,
                JingMove Mv
            )
            {
                this.DuelId = DuelId;
                this.Mv = Mv;
            }

            public CounterJing()
            {
            }

            string IReducerArgs.ReducerName => "counter_jing";
        }
    }
}
