// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreatePlayerHandler(ReducerEventContext ctx, string handle, SpacetimeDB.Types.NatalChart chart, SpacetimeDB.Types.Planet faction);
        public event CreatePlayerHandler? OnCreatePlayer;

        public void CreatePlayer(string handle, SpacetimeDB.Types.NatalChart chart, SpacetimeDB.Types.Planet faction)
        {
            conn.InternalCallReducer(new Reducer.CreatePlayer(handle, chart, faction));
        }

        public bool InvokeCreatePlayer(ReducerEventContext ctx, Reducer.CreatePlayer args)
        {
            if (OnCreatePlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreatePlayer(
                ctx,
                args.Handle,
                args.Chart,
                args.Faction
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreatePlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "handle")]
            public string Handle;
            [DataMember(Name = "chart")]
            public NatalChart Chart;
            [DataMember(Name = "faction")]
            public Planet Faction;

            public CreatePlayer(
                string Handle,
                NatalChart Chart,
                Planet Faction
            )
            {
                this.Handle = Handle;
                this.Chart = Chart;
                this.Faction = Faction;
            }

            public CreatePlayer()
            {
                this.Handle = "";
                this.Chart = new();
            }

            string IReducerArgs.ReducerName => "create_player";
        }
    }
}
