// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeployCardHandler(ReducerEventContext ctx, ulong cardId, byte zoneId);
        public event DeployCardHandler? OnDeployCard;

        public void DeployCard(ulong cardId, byte zoneId)
        {
            conn.InternalCallReducer(new Reducer.DeployCard(cardId, zoneId));
        }

        public bool InvokeDeployCard(ReducerEventContext ctx, Reducer.DeployCard args)
        {
            if (OnDeployCard == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeployCard(
                ctx,
                args.CardId,
                args.ZoneId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeployCard : Reducer, IReducerArgs
        {
            [DataMember(Name = "card_id")]
            public ulong CardId;
            [DataMember(Name = "zone_id")]
            public byte ZoneId;

            public DeployCard(
                ulong CardId,
                byte ZoneId
            )
            {
                this.CardId = CardId;
                this.ZoneId = ZoneId;
            }

            public DeployCard()
            {
            }

            string IReducerArgs.ReducerName => "deploy_card";
        }
    }
}
