// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnqueueDuelHandler(ReducerEventContext ctx, byte zoneId);
        public event EnqueueDuelHandler? OnEnqueueDuel;

        public void EnqueueDuel(byte zoneId)
        {
            conn.InternalCallReducer(new Reducer.EnqueueDuel(zoneId));
        }

        public bool InvokeEnqueueDuel(ReducerEventContext ctx, Reducer.EnqueueDuel args)
        {
            if (OnEnqueueDuel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnqueueDuel(
                ctx,
                args.ZoneId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnqueueDuel : Reducer, IReducerArgs
        {
            [DataMember(Name = "zone_id")]
            public byte ZoneId;

            public EnqueueDuel(byte ZoneId)
            {
                this.ZoneId = ZoneId;
            }

            public EnqueueDuel()
            {
            }

            string IReducerArgs.ReducerName => "enqueue_duel";
        }
    }
}
