// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void OpenIdentityLinkHandler(ReducerEventContext ctx, string codeHash);
        public event OpenIdentityLinkHandler? OnOpenIdentityLink;

        public void OpenIdentityLink(string codeHash)
        {
            conn.InternalCallReducer(new Reducer.OpenIdentityLink(codeHash));
        }

        public bool InvokeOpenIdentityLink(ReducerEventContext ctx, Reducer.OpenIdentityLink args)
        {
            if (OnOpenIdentityLink == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnOpenIdentityLink(
                ctx,
                args.CodeHash
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class OpenIdentityLink : Reducer, IReducerArgs
        {
            [DataMember(Name = "code_hash")]
            public string CodeHash;

            public OpenIdentityLink(string CodeHash)
            {
                this.CodeHash = CodeHash;
            }

            public OpenIdentityLink()
            {
                this.CodeHash = "";
            }

            string IReducerArgs.ReducerName => "open_identity_link";
        }
    }
}
