// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ProposeTradeHandler(ReducerEventContext ctx, SpacetimeDB.Identity partner, System.Collections.Generic.List<ulong> offer, System.Collections.Generic.List<ulong> request);
        public event ProposeTradeHandler? OnProposeTrade;

        public void ProposeTrade(SpacetimeDB.Identity partner, System.Collections.Generic.List<ulong> offer, System.Collections.Generic.List<ulong> request)
        {
            conn.InternalCallReducer(new Reducer.ProposeTrade(partner, offer, request));
        }

        public bool InvokeProposeTrade(ReducerEventContext ctx, Reducer.ProposeTrade args)
        {
            if (OnProposeTrade == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnProposeTrade(
                ctx,
                args.Partner,
                args.Offer,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ProposeTrade : Reducer, IReducerArgs
        {
            [DataMember(Name = "partner")]
            public SpacetimeDB.Identity Partner;
            [DataMember(Name = "offer")]
            public System.Collections.Generic.List<ulong> Offer;
            [DataMember(Name = "request")]
            public System.Collections.Generic.List<ulong> Request;

            public ProposeTrade(
                SpacetimeDB.Identity Partner,
                System.Collections.Generic.List<ulong> Offer,
                System.Collections.Generic.List<ulong> Request
            )
            {
                this.Partner = Partner;
                this.Offer = Offer;
                this.Request = Request;
            }

            public ProposeTrade()
            {
                this.Offer = new();
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "propose_trade";
        }
    }
}
