// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PurgeStaleAgentsHandler(ReducerEventContext ctx, System.Collections.Generic.List<string> keepKeys);
        public event PurgeStaleAgentsHandler? OnPurgeStaleAgents;

        public void PurgeStaleAgents(System.Collections.Generic.List<string> keepKeys)
        {
            conn.InternalCallReducer(new Reducer.PurgeStaleAgents(keepKeys));
        }

        public bool InvokePurgeStaleAgents(ReducerEventContext ctx, Reducer.PurgeStaleAgents args)
        {
            if (OnPurgeStaleAgents == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPurgeStaleAgents(
                ctx,
                args.KeepKeys
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PurgeStaleAgents : Reducer, IReducerArgs
        {
            [DataMember(Name = "keep_keys")]
            public System.Collections.Generic.List<string> KeepKeys;

            public PurgeStaleAgents(System.Collections.Generic.List<string> KeepKeys)
            {
                this.KeepKeys = KeepKeys;
            }

            public PurgeStaleAgents()
            {
                this.KeepKeys = new();
            }

            string IReducerArgs.ReducerName => "purge_stale_agents";
        }
    }
}
