// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PushEphemerisHandler(ReducerEventContext ctx, byte bodyIdx, double ra, double dec, byte transitingZone);
        public event PushEphemerisHandler? OnPushEphemeris;

        public void PushEphemeris(byte bodyIdx, double ra, double dec, byte transitingZone)
        {
            conn.InternalCallReducer(new Reducer.PushEphemeris(bodyIdx, ra, dec, transitingZone));
        }

        public bool InvokePushEphemeris(ReducerEventContext ctx, Reducer.PushEphemeris args)
        {
            if (OnPushEphemeris == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPushEphemeris(
                ctx,
                args.BodyIdx,
                args.Ra,
                args.Dec,
                args.TransitingZone
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PushEphemeris : Reducer, IReducerArgs
        {
            [DataMember(Name = "body_idx")]
            public byte BodyIdx;
            [DataMember(Name = "ra")]
            public double Ra;
            [DataMember(Name = "dec")]
            public double Dec;
            [DataMember(Name = "transiting_zone")]
            public byte TransitingZone;

            public PushEphemeris(
                byte BodyIdx,
                double Ra,
                double Dec,
                byte TransitingZone
            )
            {
                this.BodyIdx = BodyIdx;
                this.Ra = Ra;
                this.Dec = Dec;
                this.TransitingZone = TransitingZone;
            }

            public PushEphemeris()
            {
            }

            string IReducerArgs.ReducerName => "push_ephemeris";
        }
    }
}
