// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RecordStarUnstakeHandler(ReducerEventContext ctx, ulong stakeId);
        public event RecordStarUnstakeHandler? OnRecordStarUnstake;

        public void RecordStarUnstake(ulong stakeId)
        {
            conn.InternalCallReducer(new Reducer.RecordStarUnstake(stakeId));
        }

        public bool InvokeRecordStarUnstake(ReducerEventContext ctx, Reducer.RecordStarUnstake args)
        {
            if (OnRecordStarUnstake == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRecordStarUnstake(
                ctx,
                args.StakeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RecordStarUnstake : Reducer, IReducerArgs
        {
            [DataMember(Name = "stake_id")]
            public ulong StakeId;

            public RecordStarUnstake(ulong StakeId)
            {
                this.StakeId = StakeId;
            }

            public RecordStarUnstake()
            {
            }

            string IReducerArgs.ReducerName => "record_star_unstake";
        }
    }
}
