// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RecordStarStakeHandler(ReducerEventContext ctx, uint starId, ulong principalUsdc, U128 shares);
        public event RecordStarStakeHandler? OnRecordStarStake;

        public void RecordStarStake(uint starId, ulong principalUsdc, U128 shares)
        {
            conn.InternalCallReducer(new Reducer.RecordStarStake(starId, principalUsdc, shares));
        }

        public bool InvokeRecordStarStake(ReducerEventContext ctx, Reducer.RecordStarStake args)
        {
            if (OnRecordStarStake == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRecordStarStake(
                ctx,
                args.StarId,
                args.PrincipalUsdc,
                args.Shares
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RecordStarStake : Reducer, IReducerArgs
        {
            [DataMember(Name = "star_id")]
            public uint StarId;
            [DataMember(Name = "principal_usdc")]
            public ulong PrincipalUsdc;
            [DataMember(Name = "shares")]
            public U128 Shares;

            public RecordStarStake(
                uint StarId,
                ulong PrincipalUsdc,
                U128 Shares
            )
            {
                this.StarId = StarId;
                this.PrincipalUsdc = PrincipalUsdc;
                this.Shares = Shares;
            }

            public RecordStarStake()
            {
            }

            string IReducerArgs.ReducerName => "record_star_stake";
        }
    }
}
