// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportServiceHealthHandler(ReducerEventContext ctx, string service, bool healthy, string detail, uint latencyMs);
        public event ReportServiceHealthHandler? OnReportServiceHealth;

        public void ReportServiceHealth(string service, bool healthy, string detail, uint latencyMs)
        {
            conn.InternalCallReducer(new Reducer.ReportServiceHealth(service, healthy, detail, latencyMs));
        }

        public bool InvokeReportServiceHealth(ReducerEventContext ctx, Reducer.ReportServiceHealth args)
        {
            if (OnReportServiceHealth == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportServiceHealth(
                ctx,
                args.Service,
                args.Healthy,
                args.Detail,
                args.LatencyMs
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportServiceHealth : Reducer, IReducerArgs
        {
            [DataMember(Name = "service")]
            public string Service;
            [DataMember(Name = "healthy")]
            public bool Healthy;
            [DataMember(Name = "detail")]
            public string Detail;
            [DataMember(Name = "latency_ms")]
            public uint LatencyMs;

            public ReportServiceHealth(
                string Service,
                bool Healthy,
                string Detail,
                uint LatencyMs
            )
            {
                this.Service = Service;
                this.Healthy = Healthy;
                this.Detail = Detail;
                this.LatencyMs = LatencyMs;
            }

            public ReportServiceHealth()
            {
                this.Service = "";
                this.Detail = "";
            }

            string IReducerArgs.ReducerName => "report_service_health";
        }
    }
}
