// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RequestYieldClaimHandler(ReducerEventContext ctx, ulong stakeId);
        public event RequestYieldClaimHandler? OnRequestYieldClaim;

        public void RequestYieldClaim(ulong stakeId)
        {
            conn.InternalCallReducer(new Reducer.RequestYieldClaim(stakeId));
        }

        public bool InvokeRequestYieldClaim(ReducerEventContext ctx, Reducer.RequestYieldClaim args)
        {
            if (OnRequestYieldClaim == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRequestYieldClaim(
                ctx,
                args.StakeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RequestYieldClaim : Reducer, IReducerArgs
        {
            [DataMember(Name = "stake_id")]
            public ulong StakeId;

            public RequestYieldClaim(ulong StakeId)
            {
                this.StakeId = StakeId;
            }

            public RequestYieldClaim()
            {
            }

            string IReducerArgs.ReducerName => "request_yield_claim";
        }
    }
}
