// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ResolveStarBattleHandler(ReducerEventContext ctx, uint hipId, SpacetimeDB.Types.BattleLog log);
        public event ResolveStarBattleHandler? OnResolveStarBattle;

        public void ResolveStarBattle(uint hipId, SpacetimeDB.Types.BattleLog log)
        {
            conn.InternalCallReducer(new Reducer.ResolveStarBattle(hipId, log));
        }

        public bool InvokeResolveStarBattle(ReducerEventContext ctx, Reducer.ResolveStarBattle args)
        {
            if (OnResolveStarBattle == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnResolveStarBattle(
                ctx,
                args.HipId,
                args.Log
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ResolveStarBattle : Reducer, IReducerArgs
        {
            [DataMember(Name = "hip_id")]
            public uint HipId;
            [DataMember(Name = "log")]
            public BattleLog Log;

            public ResolveStarBattle(
                uint HipId,
                BattleLog Log
            )
            {
                this.HipId = HipId;
                this.Log = Log;
            }

            public ResolveStarBattle()
            {
                this.Log = new();
            }

            string IReducerArgs.ReducerName => "resolve_star_battle";
        }
    }
}
