// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SeedAgentPlayerHandler(ReducerEventContext ctx, string agentKey, string handle, SpacetimeDB.Types.NatalChart chart, SpacetimeDB.Types.Planet faction);
        public event SeedAgentPlayerHandler? OnSeedAgentPlayer;

        public void SeedAgentPlayer(string agentKey, string handle, SpacetimeDB.Types.NatalChart chart, SpacetimeDB.Types.Planet faction)
        {
            conn.InternalCallReducer(new Reducer.SeedAgentPlayer(agentKey, handle, chart, faction));
        }

        public bool InvokeSeedAgentPlayer(ReducerEventContext ctx, Reducer.SeedAgentPlayer args)
        {
            if (OnSeedAgentPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSeedAgentPlayer(
                ctx,
                args.AgentKey,
                args.Handle,
                args.Chart,
                args.Faction
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SeedAgentPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "agent_key")]
            public string AgentKey;
            [DataMember(Name = "handle")]
            public string Handle;
            [DataMember(Name = "chart")]
            public NatalChart Chart;
            [DataMember(Name = "faction")]
            public Planet Faction;

            public SeedAgentPlayer(
                string AgentKey,
                string Handle,
                NatalChart Chart,
                Planet Faction
            )
            {
                this.AgentKey = AgentKey;
                this.Handle = Handle;
                this.Chart = Chart;
                this.Faction = Faction;
            }

            public SeedAgentPlayer()
            {
                this.AgentKey = "";
                this.Handle = "";
                this.Chart = new();
            }

            string IReducerArgs.ReducerName => "seed_agent_player";
        }
    }
}
