// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetLocationHandler(ReducerEventContext ctx, double lat, double lon);
        public event SetLocationHandler? OnSetLocation;

        public void SetLocation(double lat, double lon)
        {
            conn.InternalCallReducer(new Reducer.SetLocation(lat, lon));
        }

        public bool InvokeSetLocation(ReducerEventContext ctx, Reducer.SetLocation args)
        {
            if (OnSetLocation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetLocation(
                ctx,
                args.Lat,
                args.Lon
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetLocation : Reducer, IReducerArgs
        {
            [DataMember(Name = "lat")]
            public double Lat;
            [DataMember(Name = "lon")]
            public double Lon;

            public SetLocation(
                double Lat,
                double Lon
            )
            {
                this.Lat = Lat;
                this.Lon = Lon;
            }

            public SetLocation()
            {
            }

            string IReducerArgs.ReducerName => "set_location";
        }
    }
}
