// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetLoadoutHandler(ReducerEventContext ctx, ulong cardId, SpacetimeDB.Types.Loadout loadout);
        public event SetLoadoutHandler? OnSetLoadout;

        public void SetLoadout(ulong cardId, SpacetimeDB.Types.Loadout loadout)
        {
            conn.InternalCallReducer(new Reducer.SetLoadout(cardId, loadout));
        }

        public bool InvokeSetLoadout(ReducerEventContext ctx, Reducer.SetLoadout args)
        {
            if (OnSetLoadout == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetLoadout(
                ctx,
                args.CardId,
                args.Loadout
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetLoadout : Reducer, IReducerArgs
        {
            [DataMember(Name = "card_id")]
            public ulong CardId;
            [DataMember(Name = "loadout")]
            public Loadout Loadout;

            public SetLoadout(
                ulong CardId,
                Loadout Loadout
            )
            {
                this.CardId = CardId;
                this.Loadout = Loadout;
            }

            public SetLoadout()
            {
            }

            string IReducerArgs.ReducerName => "set_loadout";
        }
    }
}
