// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SiegeHorizonStarHandler(ReducerEventContext ctx, uint starId);
        public event SiegeHorizonStarHandler? OnSiegeHorizonStar;

        public void SiegeHorizonStar(uint starId)
        {
            conn.InternalCallReducer(new Reducer.SiegeHorizonStar(starId));
        }

        public bool InvokeSiegeHorizonStar(ReducerEventContext ctx, Reducer.SiegeHorizonStar args)
        {
            if (OnSiegeHorizonStar == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSiegeHorizonStar(
                ctx,
                args.StarId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SiegeHorizonStar : Reducer, IReducerArgs
        {
            [DataMember(Name = "star_id")]
            public uint StarId;

            public SiegeHorizonStar(uint StarId)
            {
                this.StarId = StarId;
            }

            public SiegeHorizonStar()
            {
            }

            string IReducerArgs.ReducerName => "siege_horizon_star";
        }
    }
}
