// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StardexFortifyNodeHandler(ReducerEventContext ctx, string txHash, ulong horizonIntentId, uint starId, uint energyAmount);
        public event StardexFortifyNodeHandler? OnStardexFortifyNode;

        public void StardexFortifyNode(string txHash, ulong horizonIntentId, uint starId, uint energyAmount)
        {
            conn.InternalCallReducer(new Reducer.StardexFortifyNode(txHash, horizonIntentId, starId, energyAmount));
        }

        public bool InvokeStardexFortifyNode(ReducerEventContext ctx, Reducer.StardexFortifyNode args)
        {
            if (OnStardexFortifyNode == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStardexFortifyNode(
                ctx,
                args.TxHash,
                args.HorizonIntentId,
                args.StarId,
                args.EnergyAmount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StardexFortifyNode : Reducer, IReducerArgs
        {
            [DataMember(Name = "tx_hash")]
            public string TxHash;
            [DataMember(Name = "horizon_intent_id")]
            public ulong HorizonIntentId;
            [DataMember(Name = "star_id")]
            public uint StarId;
            [DataMember(Name = "energy_amount")]
            public uint EnergyAmount;

            public StardexFortifyNode(
                string TxHash,
                ulong HorizonIntentId,
                uint StarId,
                uint EnergyAmount
            )
            {
                this.TxHash = TxHash;
                this.HorizonIntentId = HorizonIntentId;
                this.StarId = StarId;
                this.EnergyAmount = EnergyAmount;
            }

            public StardexFortifyNode()
            {
                this.TxHash = "";
            }

            string IReducerArgs.ReducerName => "stardex_fortify_node";
        }
    }
}
