// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StardexClaimConstellationHandler(ReducerEventContext ctx, string txHash, ulong horizonIntentId, string constellationName);
        public event StardexClaimConstellationHandler? OnStardexClaimConstellation;

        public void StardexClaimConstellation(string txHash, ulong horizonIntentId, string constellationName)
        {
            conn.InternalCallReducer(new Reducer.StardexClaimConstellation(txHash, horizonIntentId, constellationName));
        }

        public bool InvokeStardexClaimConstellation(ReducerEventContext ctx, Reducer.StardexClaimConstellation args)
        {
            if (OnStardexClaimConstellation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStardexClaimConstellation(
                ctx,
                args.TxHash,
                args.HorizonIntentId,
                args.ConstellationName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StardexClaimConstellation : Reducer, IReducerArgs
        {
            [DataMember(Name = "tx_hash")]
            public string TxHash;
            [DataMember(Name = "horizon_intent_id")]
            public ulong HorizonIntentId;
            [DataMember(Name = "constellation_name")]
            public string ConstellationName;

            public StardexClaimConstellation(
                string TxHash,
                ulong HorizonIntentId,
                string ConstellationName
            )
            {
                this.TxHash = TxHash;
                this.HorizonIntentId = HorizonIntentId;
                this.ConstellationName = ConstellationName;
            }

            public StardexClaimConstellation()
            {
                this.TxHash = "";
                this.ConstellationName = "";
            }

            string IReducerArgs.ReducerName => "stardex_claim_constellation";
        }
    }
}
