// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StrikeStarSingleHandler(ReducerEventContext ctx, uint hipId, ulong cardId);
        public event StrikeStarSingleHandler? OnStrikeStarSingle;

        public void StrikeStarSingle(uint hipId, ulong cardId)
        {
            conn.InternalCallReducer(new Reducer.StrikeStarSingle(hipId, cardId));
        }

        public bool InvokeStrikeStarSingle(ReducerEventContext ctx, Reducer.StrikeStarSingle args)
        {
            if (OnStrikeStarSingle == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStrikeStarSingle(
                ctx,
                args.HipId,
                args.CardId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StrikeStarSingle : Reducer, IReducerArgs
        {
            [DataMember(Name = "hip_id")]
            public uint HipId;
            [DataMember(Name = "card_id")]
            public ulong CardId;

            public StrikeStarSingle(
                uint HipId,
                ulong CardId
            )
            {
                this.HipId = HipId;
                this.CardId = CardId;
            }

            public StrikeStarSingle()
            {
            }

            string IReducerArgs.ReducerName => "strike_star_single";
        }
    }
}
