// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SyncStardexEphemerisHandler(ReducerEventContext ctx, string txHash, ulong horizonIntentId, double lat, double lon, double elevM);
        public event SyncStardexEphemerisHandler? OnSyncStardexEphemeris;

        public void SyncStardexEphemeris(string txHash, ulong horizonIntentId, double lat, double lon, double elevM)
        {
            conn.InternalCallReducer(new Reducer.SyncStardexEphemeris(txHash, horizonIntentId, lat, lon, elevM));
        }

        public bool InvokeSyncStardexEphemeris(ReducerEventContext ctx, Reducer.SyncStardexEphemeris args)
        {
            if (OnSyncStardexEphemeris == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSyncStardexEphemeris(
                ctx,
                args.TxHash,
                args.HorizonIntentId,
                args.Lat,
                args.Lon,
                args.ElevM
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SyncStardexEphemeris : Reducer, IReducerArgs
        {
            [DataMember(Name = "tx_hash")]
            public string TxHash;
            [DataMember(Name = "horizon_intent_id")]
            public ulong HorizonIntentId;
            [DataMember(Name = "lat")]
            public double Lat;
            [DataMember(Name = "lon")]
            public double Lon;
            [DataMember(Name = "elev_m")]
            public double ElevM;

            public SyncStardexEphemeris(
                string TxHash,
                ulong HorizonIntentId,
                double Lat,
                double Lon,
                double ElevM
            )
            {
                this.TxHash = TxHash;
                this.HorizonIntentId = HorizonIntentId;
                this.Lat = Lat;
                this.Lon = Lon;
                this.ElevM = ElevM;
            }

            public SyncStardexEphemeris()
            {
                this.TxHash = "";
            }

            string IReducerArgs.ReducerName => "sync_stardex_ephemeris";
        }
    }
}
