// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SyncSolanaEventHandler(ReducerEventContext ctx, string txHash, string playerPubkey, string eventType, byte elementId, ulong amount);
        public event SyncSolanaEventHandler? OnSyncSolanaEvent;

        public void SyncSolanaEvent(string txHash, string playerPubkey, string eventType, byte elementId, ulong amount)
        {
            conn.InternalCallReducer(new Reducer.SyncSolanaEvent(txHash, playerPubkey, eventType, elementId, amount));
        }

        public bool InvokeSyncSolanaEvent(ReducerEventContext ctx, Reducer.SyncSolanaEvent args)
        {
            if (OnSyncSolanaEvent == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSyncSolanaEvent(
                ctx,
                args.TxHash,
                args.PlayerPubkey,
                args.EventType,
                args.ElementId,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SyncSolanaEvent : Reducer, IReducerArgs
        {
            [DataMember(Name = "tx_hash")]
            public string TxHash;
            [DataMember(Name = "player_pubkey")]
            public string PlayerPubkey;
            [DataMember(Name = "event_type")]
            public string EventType;
            [DataMember(Name = "element_id")]
            public byte ElementId;
            [DataMember(Name = "amount")]
            public ulong Amount;

            public SyncSolanaEvent(
                string TxHash,
                string PlayerPubkey,
                string EventType,
                byte ElementId,
                ulong Amount
            )
            {
                this.TxHash = TxHash;
                this.PlayerPubkey = PlayerPubkey;
                this.EventType = EventType;
                this.ElementId = ElementId;
                this.Amount = Amount;
            }

            public SyncSolanaEvent()
            {
                this.TxHash = "";
                this.PlayerPubkey = "";
                this.EventType = "";
            }

            string IReducerArgs.ReducerName => "sync_solana_event";
        }
    }
}
