// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SyncEvmEventHandler(ReducerEventContext ctx, string txHash, string playerAddress, string eventType, byte elementId, string amount);
        public event SyncEvmEventHandler? OnSyncEvmEvent;

        public void SyncEvmEvent(string txHash, string playerAddress, string eventType, byte elementId, string amount)
        {
            conn.InternalCallReducer(new Reducer.SyncEvmEvent(txHash, playerAddress, eventType, elementId, amount));
        }

        public bool InvokeSyncEvmEvent(ReducerEventContext ctx, Reducer.SyncEvmEvent args)
        {
            if (OnSyncEvmEvent == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSyncEvmEvent(
                ctx,
                args.TxHash,
                args.PlayerAddress,
                args.EventType,
                args.ElementId,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SyncEvmEvent : Reducer, IReducerArgs
        {
            [DataMember(Name = "tx_hash")]
            public string TxHash;
            [DataMember(Name = "player_address")]
            public string PlayerAddress;
            [DataMember(Name = "event_type")]
            public string EventType;
            [DataMember(Name = "element_id")]
            public byte ElementId;
            [DataMember(Name = "amount")]
            public string Amount;

            public SyncEvmEvent(
                string TxHash,
                string PlayerAddress,
                string EventType,
                byte ElementId,
                string Amount
            )
            {
                this.TxHash = TxHash;
                this.PlayerAddress = PlayerAddress;
                this.EventType = EventType;
                this.ElementId = ElementId;
                this.Amount = Amount;
            }

            public SyncEvmEvent()
            {
                this.TxHash = "";
                this.PlayerAddress = "";
                this.EventType = "";
                this.Amount = "";
            }

            string IReducerArgs.ReducerName => "sync_evm_event";
        }
    }
}
