// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TraceConstellationHandler(ReducerEventContext ctx, ushort constellationId, string evmAddress);
        public event TraceConstellationHandler? OnTraceConstellation;

        public void TraceConstellation(ushort constellationId, string evmAddress)
        {
            conn.InternalCallReducer(new Reducer.TraceConstellation(constellationId, evmAddress));
        }

        public bool InvokeTraceConstellation(ReducerEventContext ctx, Reducer.TraceConstellation args)
        {
            if (OnTraceConstellation == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTraceConstellation(
                ctx,
                args.ConstellationId,
                args.EvmAddress
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TraceConstellation : Reducer, IReducerArgs
        {
            [DataMember(Name = "constellation_id")]
            public ushort ConstellationId;
            [DataMember(Name = "evm_address")]
            public string EvmAddress;

            public TraceConstellation(
                ushort ConstellationId,
                string EvmAddress
            )
            {
                this.ConstellationId = ConstellationId;
                this.EvmAddress = EvmAddress;
            }

            public TraceConstellation()
            {
                this.EvmAddress = "";
            }

            string IReducerArgs.ReducerName => "trace_constellation";
        }
    }
}
