// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TransferStarStakeHandler(ReducerEventContext ctx, string txHash, string fromSolanaPubkey, string toSolanaPubkey, ulong tokenAmount);
        public event TransferStarStakeHandler? OnTransferStarStake;

        public void TransferStarStake(string txHash, string fromSolanaPubkey, string toSolanaPubkey, ulong tokenAmount)
        {
            conn.InternalCallReducer(new Reducer.TransferStarStake(txHash, fromSolanaPubkey, toSolanaPubkey, tokenAmount));
        }

        public bool InvokeTransferStarStake(ReducerEventContext ctx, Reducer.TransferStarStake args)
        {
            if (OnTransferStarStake == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTransferStarStake(
                ctx,
                args.TxHash,
                args.FromSolanaPubkey,
                args.ToSolanaPubkey,
                args.TokenAmount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TransferStarStake : Reducer, IReducerArgs
        {
            [DataMember(Name = "tx_hash")]
            public string TxHash;
            [DataMember(Name = "from_solana_pubkey")]
            public string FromSolanaPubkey;
            [DataMember(Name = "to_solana_pubkey")]
            public string ToSolanaPubkey;
            [DataMember(Name = "token_amount")]
            public ulong TokenAmount;

            public TransferStarStake(
                string TxHash,
                string FromSolanaPubkey,
                string ToSolanaPubkey,
                ulong TokenAmount
            )
            {
                this.TxHash = TxHash;
                this.FromSolanaPubkey = FromSolanaPubkey;
                this.ToSolanaPubkey = ToSolanaPubkey;
                this.TokenAmount = TokenAmount;
            }

            public TransferStarStake()
            {
                this.TxHash = "";
                this.FromSolanaPubkey = "";
                this.ToSolanaPubkey = "";
            }

            string IReducerArgs.ReducerName => "transfer_star_stake";
        }
    }
}
