// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void VerifySolanaWalletBindingHandler(ReducerEventContext ctx, SpacetimeDB.Identity playerIdentity, string solanaPubkey, string proofHash);
        public event VerifySolanaWalletBindingHandler? OnVerifySolanaWalletBinding;

        public void VerifySolanaWalletBinding(SpacetimeDB.Identity playerIdentity, string solanaPubkey, string proofHash)
        {
            conn.InternalCallReducer(new Reducer.VerifySolanaWalletBinding(playerIdentity, solanaPubkey, proofHash));
        }

        public bool InvokeVerifySolanaWalletBinding(ReducerEventContext ctx, Reducer.VerifySolanaWalletBinding args)
        {
            if (OnVerifySolanaWalletBinding == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnVerifySolanaWalletBinding(
                ctx,
                args.PlayerIdentity,
                args.SolanaPubkey,
                args.ProofHash
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class VerifySolanaWalletBinding : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_identity")]
            public SpacetimeDB.Identity PlayerIdentity;
            [DataMember(Name = "solana_pubkey")]
            public string SolanaPubkey;
            [DataMember(Name = "proof_hash")]
            public string ProofHash;

            public VerifySolanaWalletBinding(
                SpacetimeDB.Identity PlayerIdentity,
                string SolanaPubkey,
                string ProofHash
            )
            {
                this.PlayerIdentity = PlayerIdentity;
                this.SolanaPubkey = SolanaPubkey;
                this.ProofHash = ProofHash;
            }

            public VerifySolanaWalletBinding()
            {
                this.SolanaPubkey = "";
                this.ProofHash = "";
            }

            string IReducerArgs.ReducerName => "verify_solana_wallet_binding";
        }
    }
}
