// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AgentChartHandle : RemoteTableHandle<EventContext, AgentChart>
        {
            protected override string RemoteTableName => "agent_chart";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(AgentChart row) => row.Identity;

                public IdentityUniqueIndex(AgentChartHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal AgentChartHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(AgentChart row) => row.Identity;
        }

        public readonly AgentChartHandle AgentChart;
    }

    public sealed class AgentChartCols
    {
        public global::SpacetimeDB.Col<AgentChart, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<AgentChart, string> Handle { get; }
        public global::SpacetimeDB.Col<AgentChart, long> BirthUnix { get; }
        public global::SpacetimeDB.Col<AgentChart, double> BirthLat { get; }
        public global::SpacetimeDB.Col<AgentChart, double> BirthLon { get; }
        public global::SpacetimeDB.Col<AgentChart, bool> TimeKnown { get; }
        public global::SpacetimeDB.Col<AgentChart, System.Collections.Generic.List<Placement>> Placements { get; }
        public global::SpacetimeDB.Col<AgentChart, ushort> Ascendant { get; }
        public global::SpacetimeDB.Col<AgentChart, ushort> Midheaven { get; }
        public global::SpacetimeDB.Col<AgentChart, System.Collections.Generic.List<ushort>> HouseCusps { get; }
        public global::SpacetimeDB.Col<AgentChart, HouseSystem> HouseSystem { get; }
        public global::SpacetimeDB.Col<AgentChart, System.Collections.Generic.List<byte>> InterceptedSigns { get; }

        public AgentChartCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<AgentChart, SpacetimeDB.Identity>(tableName, "identity");
            Handle = new global::SpacetimeDB.Col<AgentChart, string>(tableName, "handle");
            BirthUnix = new global::SpacetimeDB.Col<AgentChart, long>(tableName, "birth_unix");
            BirthLat = new global::SpacetimeDB.Col<AgentChart, double>(tableName, "birth_lat");
            BirthLon = new global::SpacetimeDB.Col<AgentChart, double>(tableName, "birth_lon");
            TimeKnown = new global::SpacetimeDB.Col<AgentChart, bool>(tableName, "time_known");
            Placements = new global::SpacetimeDB.Col<AgentChart, System.Collections.Generic.List<Placement>>(tableName, "placements");
            Ascendant = new global::SpacetimeDB.Col<AgentChart, ushort>(tableName, "ascendant");
            Midheaven = new global::SpacetimeDB.Col<AgentChart, ushort>(tableName, "midheaven");
            HouseCusps = new global::SpacetimeDB.Col<AgentChart, System.Collections.Generic.List<ushort>>(tableName, "house_cusps");
            HouseSystem = new global::SpacetimeDB.Col<AgentChart, HouseSystem>(tableName, "house_system");
            InterceptedSigns = new global::SpacetimeDB.Col<AgentChart, System.Collections.Generic.List<byte>>(tableName, "intercepted_signs");
        }
    }

    public sealed class AgentChartIxCols
    {
        public global::SpacetimeDB.IxCol<AgentChart, SpacetimeDB.Identity> Identity { get; }

        public AgentChartIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<AgentChart, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
