// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BattleHandle : RemoteTableHandle<EventContext, Battle>
        {
            protected override string RemoteTableName => "battle";

            public sealed class BattleIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Battle row) => row.BattleId;

                public BattleIdUniqueIndex(BattleHandle table) : base(table) { }
            }

            public readonly BattleIdUniqueIndex BattleId;

            internal BattleHandle(DbConnection conn) : base(conn)
            {
                BattleId = new(this);
            }

            protected override object GetPrimaryKey(Battle row) => row.BattleId;
        }

        public readonly BattleHandle Battle;
    }

    public sealed class BattleCols
    {
        public global::SpacetimeDB.Col<Battle, ulong> BattleId { get; }
        public global::SpacetimeDB.Col<Battle, uint> StarId { get; }
        public global::SpacetimeDB.Col<Battle, SpacetimeDB.Identity> Attacker { get; }
        public global::SpacetimeDB.Col<Battle, bool> Won { get; }
        public global::SpacetimeDB.Col<Battle, uint> AttackerScore { get; }
        public global::SpacetimeDB.Col<Battle, uint> DefenseRating { get; }
        public global::SpacetimeDB.Col<Battle, SpacetimeDB.Timestamp> CreatedAt { get; }

        public BattleCols(string tableName)
        {
            BattleId = new global::SpacetimeDB.Col<Battle, ulong>(tableName, "battle_id");
            StarId = new global::SpacetimeDB.Col<Battle, uint>(tableName, "star_id");
            Attacker = new global::SpacetimeDB.Col<Battle, SpacetimeDB.Identity>(tableName, "attacker");
            Won = new global::SpacetimeDB.Col<Battle, bool>(tableName, "won");
            AttackerScore = new global::SpacetimeDB.Col<Battle, uint>(tableName, "attacker_score");
            DefenseRating = new global::SpacetimeDB.Col<Battle, uint>(tableName, "defense_rating");
            CreatedAt = new global::SpacetimeDB.Col<Battle, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class BattleIxCols
    {
        public global::SpacetimeDB.IxCol<Battle, ulong> BattleId { get; }

        public BattleIxCols(string tableName)
        {
            BattleId = new global::SpacetimeDB.IxCol<Battle, ulong>(tableName, "battle_id");
        }
    }
}
