// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BridgeTransferHandle : RemoteTableHandle<EventContext, BridgeTransfer>
        {
            protected override string RemoteTableName => "bridge_transfer";

            public sealed class BurnTxHashUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(BridgeTransfer row) => row.BurnTxHash;

                public BurnTxHashUniqueIndex(BridgeTransferHandle table) : base(table) { }
            }

            public readonly BurnTxHashUniqueIndex BurnTxHash;

            public sealed class PlayerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(BridgeTransfer row) => row.Player;

                public PlayerIndex(BridgeTransferHandle table) : base(table) { }
            }

            public readonly PlayerIndex Player;

            internal BridgeTransferHandle(DbConnection conn) : base(conn)
            {
                BurnTxHash = new(this);
                Player = new(this);
            }

            protected override object GetPrimaryKey(BridgeTransfer row) => row.BurnTxHash;
        }

        public readonly BridgeTransferHandle BridgeTransfer;
    }

    public sealed class BridgeTransferCols
    {
        public global::SpacetimeDB.Col<BridgeTransfer, string> BurnTxHash { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, BridgeChain> SourceChain { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, BridgeChain> TargetChain { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, string> SourceAddress { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, string> TargetAddress { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, byte> ElementId { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, U128> Amount { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, BridgeStatus> Status { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, string> DestinationTxHash { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<BridgeTransfer, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public BridgeTransferCols(string tableName)
        {
            BurnTxHash = new global::SpacetimeDB.Col<BridgeTransfer, string>(tableName, "burn_tx_hash");
            Player = new global::SpacetimeDB.Col<BridgeTransfer, SpacetimeDB.Identity>(tableName, "player");
            SourceChain = new global::SpacetimeDB.Col<BridgeTransfer, BridgeChain>(tableName, "source_chain");
            TargetChain = new global::SpacetimeDB.Col<BridgeTransfer, BridgeChain>(tableName, "target_chain");
            SourceAddress = new global::SpacetimeDB.Col<BridgeTransfer, string>(tableName, "source_address");
            TargetAddress = new global::SpacetimeDB.Col<BridgeTransfer, string>(tableName, "target_address");
            ElementId = new global::SpacetimeDB.Col<BridgeTransfer, byte>(tableName, "element_id");
            Amount = new global::SpacetimeDB.Col<BridgeTransfer, U128>(tableName, "amount");
            Status = new global::SpacetimeDB.Col<BridgeTransfer, BridgeStatus>(tableName, "status");
            DestinationTxHash = new global::SpacetimeDB.Col<BridgeTransfer, string>(tableName, "destination_tx_hash");
            CreatedAt = new global::SpacetimeDB.Col<BridgeTransfer, SpacetimeDB.Timestamp>(tableName, "created_at");
            UpdatedAt = new global::SpacetimeDB.Col<BridgeTransfer, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class BridgeTransferIxCols
    {
        public global::SpacetimeDB.IxCol<BridgeTransfer, string> BurnTxHash { get; }
        public global::SpacetimeDB.IxCol<BridgeTransfer, SpacetimeDB.Identity> Player { get; }

        public BridgeTransferIxCols(string tableName)
        {
            BurnTxHash = new global::SpacetimeDB.IxCol<BridgeTransfer, string>(tableName, "burn_tx_hash");
            Player = new global::SpacetimeDB.IxCol<BridgeTransfer, SpacetimeDB.Identity>(tableName, "player");
        }
    }
}
