// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CardHandle : RemoteTableHandle<EventContext, Card>
        {
            protected override string RemoteTableName => "card";

            public sealed class CardIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Card row) => row.CardId;

                public CardIdUniqueIndex(CardHandle table) : base(table) { }
            }

            public readonly CardIdUniqueIndex CardId;

            internal CardHandle(DbConnection conn) : base(conn)
            {
                CardId = new(this);
            }

            protected override object GetPrimaryKey(Card row) => row.CardId;
        }

        public readonly CardHandle Card;
    }

    public sealed class CardCols
    {
        public global::SpacetimeDB.Col<Card, ulong> CardId { get; }
        public global::SpacetimeDB.Col<Card, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<Card, Suit> Suit { get; }
        public global::SpacetimeDB.Col<Card, byte> Rank { get; }
        public global::SpacetimeDB.Col<Card, ushort> Health { get; }
        public global::SpacetimeDB.Col<Card, ushort> Attack { get; }
        public global::SpacetimeDB.Col<Card, ushort> Armour { get; }
        public global::SpacetimeDB.Col<Card, ushort> CooldownMs { get; }
        public global::SpacetimeDB.Col<Card, Planet> SourceBody { get; }
        public global::SpacetimeDB.Col<Card, bool> Inverted { get; }
        public global::SpacetimeDB.Col<Card, bool> IsTrump { get; }
        public global::SpacetimeDB.Col<Card, byte> Level { get; }
        public global::SpacetimeDB.Col<Card, SpacetimeDB.Timestamp> MintedAt { get; }

        public CardCols(string tableName)
        {
            CardId = new global::SpacetimeDB.Col<Card, ulong>(tableName, "card_id");
            Owner = new global::SpacetimeDB.Col<Card, SpacetimeDB.Identity>(tableName, "owner");
            Suit = new global::SpacetimeDB.Col<Card, Suit>(tableName, "suit");
            Rank = new global::SpacetimeDB.Col<Card, byte>(tableName, "rank");
            Health = new global::SpacetimeDB.Col<Card, ushort>(tableName, "health");
            Attack = new global::SpacetimeDB.Col<Card, ushort>(tableName, "attack");
            Armour = new global::SpacetimeDB.Col<Card, ushort>(tableName, "armour");
            CooldownMs = new global::SpacetimeDB.Col<Card, ushort>(tableName, "cooldown_ms");
            SourceBody = new global::SpacetimeDB.Col<Card, Planet>(tableName, "source_body");
            Inverted = new global::SpacetimeDB.Col<Card, bool>(tableName, "inverted");
            IsTrump = new global::SpacetimeDB.Col<Card, bool>(tableName, "is_trump");
            Level = new global::SpacetimeDB.Col<Card, byte>(tableName, "level");
            MintedAt = new global::SpacetimeDB.Col<Card, SpacetimeDB.Timestamp>(tableName, "minted_at");
        }
    }

    public sealed class CardIxCols
    {
        public global::SpacetimeDB.IxCol<Card, ulong> CardId { get; }

        public CardIxCols(string tableName)
        {
            CardId = new global::SpacetimeDB.IxCol<Card, ulong>(tableName, "card_id");
        }
    }
}
