// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CometHandle : RemoteTableHandle<EventContext, Comet>
        {
            protected override string RemoteTableName => "comet";

            public sealed class CometIdUniqueIndex : UniqueIndexBase<ushort>
            {
                protected override ushort GetKey(Comet row) => row.CometId;

                public CometIdUniqueIndex(CometHandle table) : base(table) { }
            }

            public readonly CometIdUniqueIndex CometId;

            internal CometHandle(DbConnection conn) : base(conn)
            {
                CometId = new(this);
            }

            protected override object GetPrimaryKey(Comet row) => row.CometId;
        }

        public readonly CometHandle Comet;
    }

    public sealed class CometCols
    {
        public global::SpacetimeDB.Col<Comet, ushort> CometId { get; }
        public global::SpacetimeDB.Col<Comet, string> Name { get; }
        public global::SpacetimeDB.Col<Comet, string> Designation { get; }
        public global::SpacetimeDB.Col<Comet, byte> Element { get; }
        public global::SpacetimeDB.Col<Comet, System.Collections.Generic.List<ushort>> Composition { get; }
        public global::SpacetimeDB.Col<Comet, string> Specialty { get; }
        public global::SpacetimeDB.Col<Comet, double> SemiMajorAu { get; }
        public global::SpacetimeDB.Col<Comet, double> Eccentricity { get; }
        public global::SpacetimeDB.Col<Comet, double> InclinationDeg { get; }
        public global::SpacetimeDB.Col<Comet, double> MeanLongDeg { get; }
        public global::SpacetimeDB.Col<Comet, double> LongPeriDeg { get; }
        public global::SpacetimeDB.Col<Comet, double> LongNodeDeg { get; }
        public global::SpacetimeDB.Col<Comet, double> MeanLongRate { get; }
        public global::SpacetimeDB.Col<Comet, bool> Active { get; }

        public CometCols(string tableName)
        {
            CometId = new global::SpacetimeDB.Col<Comet, ushort>(tableName, "comet_id");
            Name = new global::SpacetimeDB.Col<Comet, string>(tableName, "name");
            Designation = new global::SpacetimeDB.Col<Comet, string>(tableName, "designation");
            Element = new global::SpacetimeDB.Col<Comet, byte>(tableName, "element");
            Composition = new global::SpacetimeDB.Col<Comet, System.Collections.Generic.List<ushort>>(tableName, "composition");
            Specialty = new global::SpacetimeDB.Col<Comet, string>(tableName, "specialty");
            SemiMajorAu = new global::SpacetimeDB.Col<Comet, double>(tableName, "semi_major_au");
            Eccentricity = new global::SpacetimeDB.Col<Comet, double>(tableName, "eccentricity");
            InclinationDeg = new global::SpacetimeDB.Col<Comet, double>(tableName, "inclination_deg");
            MeanLongDeg = new global::SpacetimeDB.Col<Comet, double>(tableName, "mean_long_deg");
            LongPeriDeg = new global::SpacetimeDB.Col<Comet, double>(tableName, "long_peri_deg");
            LongNodeDeg = new global::SpacetimeDB.Col<Comet, double>(tableName, "long_node_deg");
            MeanLongRate = new global::SpacetimeDB.Col<Comet, double>(tableName, "mean_long_rate");
            Active = new global::SpacetimeDB.Col<Comet, bool>(tableName, "active");
        }
    }

    public sealed class CometIxCols
    {
        public global::SpacetimeDB.IxCol<Comet, ushort> CometId { get; }

        public CometIxCols(string tableName)
        {
            CometId = new global::SpacetimeDB.IxCol<Comet, ushort>(tableName, "comet_id");
        }
    }
}
