// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConstellationResolutionHandle : RemoteTableHandle<EventContext, ConstellationResolution>
        {
            protected override string RemoteTableName => "constellation_resolution";

            public sealed class ConstellationIdUniqueIndex : UniqueIndexBase<ushort>
            {
                protected override ushort GetKey(ConstellationResolution row) => row.ConstellationId;

                public ConstellationIdUniqueIndex(ConstellationResolutionHandle table) : base(table) { }
            }

            public readonly ConstellationIdUniqueIndex ConstellationId;

            internal ConstellationResolutionHandle(DbConnection conn) : base(conn)
            {
                ConstellationId = new(this);
            }

            protected override object GetPrimaryKey(ConstellationResolution row) => row.ConstellationId;
        }

        public readonly ConstellationResolutionHandle ConstellationResolution;
    }

    public sealed class ConstellationResolutionCols
    {
        public global::SpacetimeDB.Col<ConstellationResolution, ushort> ConstellationId { get; }
        public global::SpacetimeDB.Col<ConstellationResolution, ushort> BaselineMembers { get; }
        public global::SpacetimeDB.Col<ConstellationResolution, ushort> AddedMembers { get; }
        public global::SpacetimeDB.Col<ConstellationResolution, ushort> ResolutionLevel { get; }
        public global::SpacetimeDB.Col<ConstellationResolution, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public ConstellationResolutionCols(string tableName)
        {
            ConstellationId = new global::SpacetimeDB.Col<ConstellationResolution, ushort>(tableName, "constellation_id");
            BaselineMembers = new global::SpacetimeDB.Col<ConstellationResolution, ushort>(tableName, "baseline_members");
            AddedMembers = new global::SpacetimeDB.Col<ConstellationResolution, ushort>(tableName, "added_members");
            ResolutionLevel = new global::SpacetimeDB.Col<ConstellationResolution, ushort>(tableName, "resolution_level");
            UpdatedAt = new global::SpacetimeDB.Col<ConstellationResolution, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class ConstellationResolutionIxCols
    {
        public global::SpacetimeDB.IxCol<ConstellationResolution, ushort> ConstellationId { get; }

        public ConstellationResolutionIxCols(string tableName)
        {
            ConstellationId = new global::SpacetimeDB.IxCol<ConstellationResolution, ushort>(tableName, "constellation_id");
        }
    }
}
