// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConstellationHandle : RemoteTableHandle<EventContext, Constellation>
        {
            protected override string RemoteTableName => "constellation";

            public sealed class ConstellationIdUniqueIndex : UniqueIndexBase<ushort>
            {
                protected override ushort GetKey(Constellation row) => row.ConstellationId;

                public ConstellationIdUniqueIndex(ConstellationHandle table) : base(table) { }
            }

            public readonly ConstellationIdUniqueIndex ConstellationId;

            internal ConstellationHandle(DbConnection conn) : base(conn)
            {
                ConstellationId = new(this);
            }

            protected override object GetPrimaryKey(Constellation row) => row.ConstellationId;
        }

        public readonly ConstellationHandle Constellation;
    }

    public sealed class ConstellationCols
    {
        public global::SpacetimeDB.Col<Constellation, ushort> ConstellationId { get; }
        public global::SpacetimeDB.Col<Constellation, string> Abbr { get; }
        public global::SpacetimeDB.Col<Constellation, string> Name { get; }
        public global::SpacetimeDB.Col<Constellation, byte> ElemA { get; }
        public global::SpacetimeDB.Col<Constellation, byte> ElemB { get; }
        public global::SpacetimeDB.Col<Constellation, bool> Degenerate { get; }
        public global::SpacetimeDB.Col<Constellation, ushort> FeeBps { get; }
        public global::SpacetimeDB.Col<Constellation, ushort> MemberCount { get; }
        public global::SpacetimeDB.Col<Constellation, ushort> VisibleThreshold { get; }

        public ConstellationCols(string tableName)
        {
            ConstellationId = new global::SpacetimeDB.Col<Constellation, ushort>(tableName, "constellation_id");
            Abbr = new global::SpacetimeDB.Col<Constellation, string>(tableName, "abbr");
            Name = new global::SpacetimeDB.Col<Constellation, string>(tableName, "name");
            ElemA = new global::SpacetimeDB.Col<Constellation, byte>(tableName, "elem_a");
            ElemB = new global::SpacetimeDB.Col<Constellation, byte>(tableName, "elem_b");
            Degenerate = new global::SpacetimeDB.Col<Constellation, bool>(tableName, "degenerate");
            FeeBps = new global::SpacetimeDB.Col<Constellation, ushort>(tableName, "fee_bps");
            MemberCount = new global::SpacetimeDB.Col<Constellation, ushort>(tableName, "member_count");
            VisibleThreshold = new global::SpacetimeDB.Col<Constellation, ushort>(tableName, "visible_threshold");
        }
    }

    public sealed class ConstellationIxCols
    {
        public global::SpacetimeDB.IxCol<Constellation, ushort> ConstellationId { get; }

        public ConstellationIxCols(string tableName)
        {
            ConstellationId = new global::SpacetimeDB.IxCol<Constellation, ushort>(tableName, "constellation_id");
        }
    }
}
