// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConstellationStarHandle : RemoteTableHandle<EventContext, ConstellationStar>
        {
            protected override string RemoteTableName => "constellation_star";

            public sealed class ConstellationIdIndex : BTreeIndexBase<ushort>
            {
                protected override ushort GetKey(ConstellationStar row) => row.ConstellationId;

                public ConstellationIdIndex(ConstellationStarHandle table) : base(table) { }
            }

            public readonly ConstellationIdIndex ConstellationId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ConstellationStar row) => row.Id;

                public IdUniqueIndex(ConstellationStarHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ConstellationStarHandle(DbConnection conn) : base(conn)
            {
                ConstellationId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(ConstellationStar row) => row.Id;
        }

        public readonly ConstellationStarHandle ConstellationStar;
    }

    public sealed class ConstellationStarCols
    {
        public global::SpacetimeDB.Col<ConstellationStar, ulong> Id { get; }
        public global::SpacetimeDB.Col<ConstellationStar, ushort> ConstellationId { get; }
        public global::SpacetimeDB.Col<ConstellationStar, uint> HipId { get; }

        public ConstellationStarCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ConstellationStar, ulong>(tableName, "id");
            ConstellationId = new global::SpacetimeDB.Col<ConstellationStar, ushort>(tableName, "constellation_id");
            HipId = new global::SpacetimeDB.Col<ConstellationStar, uint>(tableName, "hip_id");
        }
    }

    public sealed class ConstellationStarIxCols
    {
        public global::SpacetimeDB.IxCol<ConstellationStar, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<ConstellationStar, ushort> ConstellationId { get; }

        public ConstellationStarIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ConstellationStar, ulong>(tableName, "id");
            ConstellationId = new global::SpacetimeDB.IxCol<ConstellationStar, ushort>(tableName, "constellation_id");
        }
    }
}
