// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConstellationLineHandle : RemoteTableHandle<EventContext, ConstellationLine>
        {
            protected override string RemoteTableName => "constellation_line";

            public sealed class ConstellationIdIndex : BTreeIndexBase<ushort>
            {
                protected override ushort GetKey(ConstellationLine row) => row.ConstellationId;

                public ConstellationIdIndex(ConstellationLineHandle table) : base(table) { }
            }

            public readonly ConstellationIdIndex ConstellationId;

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ConstellationLine row) => row.Id;

                public IdUniqueIndex(ConstellationLineHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ConstellationLineHandle(DbConnection conn) : base(conn)
            {
                ConstellationId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(ConstellationLine row) => row.Id;
        }

        public readonly ConstellationLineHandle ConstellationLine;
    }

    public sealed class ConstellationLineCols
    {
        public global::SpacetimeDB.Col<ConstellationLine, ulong> Id { get; }
        public global::SpacetimeDB.Col<ConstellationLine, ushort> ConstellationId { get; }
        public global::SpacetimeDB.Col<ConstellationLine, uint> HipA { get; }
        public global::SpacetimeDB.Col<ConstellationLine, uint> HipB { get; }

        public ConstellationLineCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ConstellationLine, ulong>(tableName, "id");
            ConstellationId = new global::SpacetimeDB.Col<ConstellationLine, ushort>(tableName, "constellation_id");
            HipA = new global::SpacetimeDB.Col<ConstellationLine, uint>(tableName, "hip_a");
            HipB = new global::SpacetimeDB.Col<ConstellationLine, uint>(tableName, "hip_b");
        }
    }

    public sealed class ConstellationLineIxCols
    {
        public global::SpacetimeDB.IxCol<ConstellationLine, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<ConstellationLine, ushort> ConstellationId { get; }

        public ConstellationLineIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ConstellationLine, ulong>(tableName, "id");
            ConstellationId = new global::SpacetimeDB.IxCol<ConstellationLine, ushort>(tableName, "constellation_id");
        }
    }
}
