// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConstellationBlockHandle : RemoteTableHandle<EventContext, ConstellationBlock>
        {
            protected override string RemoteTableName => "constellation_block";

            public sealed class BlockIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ConstellationBlock row) => row.BlockId;

                public BlockIdUniqueIndex(ConstellationBlockHandle table) : base(table) { }
            }

            public readonly BlockIdUniqueIndex BlockId;

            public sealed class ConstellationIdIndex : BTreeIndexBase<ushort>
            {
                protected override ushort GetKey(ConstellationBlock row) => row.ConstellationId;

                public ConstellationIdIndex(ConstellationBlockHandle table) : base(table) { }
            }

            public readonly ConstellationIdIndex ConstellationId;

            internal ConstellationBlockHandle(DbConnection conn) : base(conn)
            {
                BlockId = new(this);
                ConstellationId = new(this);
            }

            protected override object GetPrimaryKey(ConstellationBlock row) => row.BlockId;
        }

        public readonly ConstellationBlockHandle ConstellationBlock;
    }

    public sealed class ConstellationBlockCols
    {
        public global::SpacetimeDB.Col<ConstellationBlock, ulong> BlockId { get; }
        public global::SpacetimeDB.Col<ConstellationBlock, ushort> ConstellationId { get; }
        public global::SpacetimeDB.Col<ConstellationBlock, SpacetimeDB.Identity> Minter { get; }
        public global::SpacetimeDB.Col<ConstellationBlock, uint> HipId { get; }
        public global::SpacetimeDB.Col<ConstellationBlock, ushort> LevelAfter { get; }
        public global::SpacetimeDB.Col<ConstellationBlock, ulong> OnchainBlock { get; }
        public global::SpacetimeDB.Col<ConstellationBlock, SpacetimeDB.Timestamp> CreatedAt { get; }

        public ConstellationBlockCols(string tableName)
        {
            BlockId = new global::SpacetimeDB.Col<ConstellationBlock, ulong>(tableName, "block_id");
            ConstellationId = new global::SpacetimeDB.Col<ConstellationBlock, ushort>(tableName, "constellation_id");
            Minter = new global::SpacetimeDB.Col<ConstellationBlock, SpacetimeDB.Identity>(tableName, "minter");
            HipId = new global::SpacetimeDB.Col<ConstellationBlock, uint>(tableName, "hip_id");
            LevelAfter = new global::SpacetimeDB.Col<ConstellationBlock, ushort>(tableName, "level_after");
            OnchainBlock = new global::SpacetimeDB.Col<ConstellationBlock, ulong>(tableName, "onchain_block");
            CreatedAt = new global::SpacetimeDB.Col<ConstellationBlock, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class ConstellationBlockIxCols
    {
        public global::SpacetimeDB.IxCol<ConstellationBlock, ulong> BlockId { get; }
        public global::SpacetimeDB.IxCol<ConstellationBlock, ushort> ConstellationId { get; }

        public ConstellationBlockIxCols(string tableName)
        {
            BlockId = new global::SpacetimeDB.IxCol<ConstellationBlock, ulong>(tableName, "block_id");
            ConstellationId = new global::SpacetimeDB.IxCol<ConstellationBlock, ushort>(tableName, "constellation_id");
        }
    }
}
