// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DeckSlotHandle : RemoteTableHandle<EventContext, DeckSlot>
        {
            protected override string RemoteTableName => "deck_slot";

            public sealed class CardIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(DeckSlot row) => row.CardId;

                public CardIdIndex(DeckSlotHandle table) : base(table) { }
            }

            public readonly CardIdIndex CardId;

            public sealed class OwnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(DeckSlot row) => row.Owner;

                public OwnerIndex(DeckSlotHandle table) : base(table) { }
            }

            public readonly OwnerIndex Owner;

            public sealed class SlotIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DeckSlot row) => row.SlotId;

                public SlotIdUniqueIndex(DeckSlotHandle table) : base(table) { }
            }

            public readonly SlotIdUniqueIndex SlotId;

            internal DeckSlotHandle(DbConnection conn) : base(conn)
            {
                CardId = new(this);
                Owner = new(this);
                SlotId = new(this);
            }

            protected override object GetPrimaryKey(DeckSlot row) => row.SlotId;
        }

        public readonly DeckSlotHandle DeckSlot;
    }

    public sealed class DeckSlotCols
    {
        public global::SpacetimeDB.Col<DeckSlot, ulong> SlotId { get; }
        public global::SpacetimeDB.Col<DeckSlot, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<DeckSlot, ulong> CardId { get; }
        public global::SpacetimeDB.Col<DeckSlot, Loadout> Loadout { get; }

        public DeckSlotCols(string tableName)
        {
            SlotId = new global::SpacetimeDB.Col<DeckSlot, ulong>(tableName, "slot_id");
            Owner = new global::SpacetimeDB.Col<DeckSlot, SpacetimeDB.Identity>(tableName, "owner");
            CardId = new global::SpacetimeDB.Col<DeckSlot, ulong>(tableName, "card_id");
            Loadout = new global::SpacetimeDB.Col<DeckSlot, Loadout>(tableName, "loadout");
        }
    }

    public sealed class DeckSlotIxCols
    {
        public global::SpacetimeDB.IxCol<DeckSlot, ulong> SlotId { get; }
        public global::SpacetimeDB.IxCol<DeckSlot, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.IxCol<DeckSlot, ulong> CardId { get; }

        public DeckSlotIxCols(string tableName)
        {
            SlotId = new global::SpacetimeDB.IxCol<DeckSlot, ulong>(tableName, "slot_id");
            Owner = new global::SpacetimeDB.IxCol<DeckSlot, SpacetimeDB.Identity>(tableName, "owner");
            CardId = new global::SpacetimeDB.IxCol<DeckSlot, ulong>(tableName, "card_id");
        }
    }
}
