// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DuelQueueHandle : RemoteTableHandle<EventContext, DuelQueue>
        {
            protected override string RemoteTableName => "duel_queue";

            public sealed class TicketIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DuelQueue row) => row.TicketId;

                public TicketIdUniqueIndex(DuelQueueHandle table) : base(table) { }
            }

            public readonly TicketIdUniqueIndex TicketId;

            internal DuelQueueHandle(DbConnection conn) : base(conn)
            {
                TicketId = new(this);
            }

            protected override object GetPrimaryKey(DuelQueue row) => row.TicketId;
        }

        public readonly DuelQueueHandle DuelQueue;
    }

    public sealed class DuelQueueCols
    {
        public global::SpacetimeDB.Col<DuelQueue, ulong> TicketId { get; }
        public global::SpacetimeDB.Col<DuelQueue, byte> ZoneId { get; }
        public global::SpacetimeDB.Col<DuelQueue, SpacetimeDB.Identity> Seeker { get; }
        public global::SpacetimeDB.Col<DuelQueue, SpacetimeDB.Timestamp> EnqueuedAt { get; }

        public DuelQueueCols(string tableName)
        {
            TicketId = new global::SpacetimeDB.Col<DuelQueue, ulong>(tableName, "ticket_id");
            ZoneId = new global::SpacetimeDB.Col<DuelQueue, byte>(tableName, "zone_id");
            Seeker = new global::SpacetimeDB.Col<DuelQueue, SpacetimeDB.Identity>(tableName, "seeker");
            EnqueuedAt = new global::SpacetimeDB.Col<DuelQueue, SpacetimeDB.Timestamp>(tableName, "enqueued_at");
        }
    }

    public sealed class DuelQueueIxCols
    {
        public global::SpacetimeDB.IxCol<DuelQueue, ulong> TicketId { get; }

        public DuelQueueIxCols(string tableName)
        {
            TicketId = new global::SpacetimeDB.IxCol<DuelQueue, ulong>(tableName, "ticket_id");
        }
    }
}
