// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DuelChallengeHandle : RemoteTableHandle<EventContext, DuelChallenge>
        {
            protected override string RemoteTableName => "duel_challenge";

            public sealed class ChallengeIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DuelChallenge row) => row.ChallengeId;

                public ChallengeIdUniqueIndex(DuelChallengeHandle table) : base(table) { }
            }

            public readonly ChallengeIdUniqueIndex ChallengeId;

            public sealed class PlayerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(DuelChallenge row) => row.Player;

                public PlayerIndex(DuelChallengeHandle table) : base(table) { }
            }

            public readonly PlayerIndex Player;

            internal DuelChallengeHandle(DbConnection conn) : base(conn)
            {
                ChallengeId = new(this);
                Player = new(this);
            }

            protected override object GetPrimaryKey(DuelChallenge row) => row.ChallengeId;
        }

        public readonly DuelChallengeHandle DuelChallenge;
    }

    public sealed class DuelChallengeCols
    {
        public global::SpacetimeDB.Col<DuelChallenge, ulong> ChallengeId { get; }
        public global::SpacetimeDB.Col<DuelChallenge, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<DuelChallenge, Planet> Opponent { get; }
        public global::SpacetimeDB.Col<DuelChallenge, string> PlayerWord { get; }
        public global::SpacetimeDB.Col<DuelChallenge, uint> PlayerScore { get; }
        public global::SpacetimeDB.Col<DuelChallenge, string> AgentRack { get; }
        public global::SpacetimeDB.Col<DuelChallenge, string> Candidates { get; }
        public global::SpacetimeDB.Col<DuelChallenge, bool> Answered { get; }
        public global::SpacetimeDB.Col<DuelChallenge, SpacetimeDB.Timestamp> CreatedAt { get; }

        public DuelChallengeCols(string tableName)
        {
            ChallengeId = new global::SpacetimeDB.Col<DuelChallenge, ulong>(tableName, "challenge_id");
            Player = new global::SpacetimeDB.Col<DuelChallenge, SpacetimeDB.Identity>(tableName, "player");
            Opponent = new global::SpacetimeDB.Col<DuelChallenge, Planet>(tableName, "opponent");
            PlayerWord = new global::SpacetimeDB.Col<DuelChallenge, string>(tableName, "player_word");
            PlayerScore = new global::SpacetimeDB.Col<DuelChallenge, uint>(tableName, "player_score");
            AgentRack = new global::SpacetimeDB.Col<DuelChallenge, string>(tableName, "agent_rack");
            Candidates = new global::SpacetimeDB.Col<DuelChallenge, string>(tableName, "candidates");
            Answered = new global::SpacetimeDB.Col<DuelChallenge, bool>(tableName, "answered");
            CreatedAt = new global::SpacetimeDB.Col<DuelChallenge, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class DuelChallengeIxCols
    {
        public global::SpacetimeDB.IxCol<DuelChallenge, ulong> ChallengeId { get; }
        public global::SpacetimeDB.IxCol<DuelChallenge, SpacetimeDB.Identity> Player { get; }

        public DuelChallengeIxCols(string tableName)
        {
            ChallengeId = new global::SpacetimeDB.IxCol<DuelChallenge, ulong>(tableName, "challenge_id");
            Player = new global::SpacetimeDB.IxCol<DuelChallenge, SpacetimeDB.Identity>(tableName, "player");
        }
    }
}
