// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DuelRoundHandle : RemoteTableHandle<EventContext, DuelRound>
        {
            protected override string RemoteTableName => "duel_round";

            public sealed class RoundIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DuelRound row) => row.RoundId;

                public RoundIdUniqueIndex(DuelRoundHandle table) : base(table) { }
            }

            public readonly RoundIdUniqueIndex RoundId;

            internal DuelRoundHandle(DbConnection conn) : base(conn)
            {
                RoundId = new(this);
            }

            protected override object GetPrimaryKey(DuelRound row) => row.RoundId;
        }

        public readonly DuelRoundHandle DuelRound;
    }

    public sealed class DuelRoundCols
    {
        public global::SpacetimeDB.Col<DuelRound, ulong> RoundId { get; }
        public global::SpacetimeDB.Col<DuelRound, uint> PlaysCount { get; }
        public global::SpacetimeDB.Col<DuelRound, uint> TargetPlays { get; }
        public global::SpacetimeDB.Col<DuelRound, SpacetimeDB.Timestamp> CreatedAt { get; }

        public DuelRoundCols(string tableName)
        {
            RoundId = new global::SpacetimeDB.Col<DuelRound, ulong>(tableName, "round_id");
            PlaysCount = new global::SpacetimeDB.Col<DuelRound, uint>(tableName, "plays_count");
            TargetPlays = new global::SpacetimeDB.Col<DuelRound, uint>(tableName, "target_plays");
            CreatedAt = new global::SpacetimeDB.Col<DuelRound, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class DuelRoundIxCols
    {
        public global::SpacetimeDB.IxCol<DuelRound, ulong> RoundId { get; }

        public DuelRoundIxCols(string tableName)
        {
            RoundId = new global::SpacetimeDB.IxCol<DuelRound, ulong>(tableName, "round_id");
        }
    }
}
