// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DuelHandle : RemoteTableHandle<EventContext, Duel>
        {
            protected override string RemoteTableName => "duel";

            public sealed class DuelIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Duel row) => row.DuelId;

                public DuelIdUniqueIndex(DuelHandle table) : base(table) { }
            }

            public readonly DuelIdUniqueIndex DuelId;

            internal DuelHandle(DbConnection conn) : base(conn)
            {
                DuelId = new(this);
            }

            protected override object GetPrimaryKey(Duel row) => row.DuelId;
        }

        public readonly DuelHandle Duel;
    }

    public sealed class DuelCols
    {
        public global::SpacetimeDB.Col<Duel, ulong> DuelId { get; }
        public global::SpacetimeDB.Col<Duel, byte> ZoneId { get; }
        public global::SpacetimeDB.Col<Duel, SpacetimeDB.Identity> PlayerA { get; }
        public global::SpacetimeDB.Col<Duel, SpacetimeDB.Identity> PlayerB { get; }
        public global::SpacetimeDB.Col<Duel, Planet> FactionA { get; }
        public global::SpacetimeDB.Col<Duel, Planet> FactionB { get; }
        public global::SpacetimeDB.Col<Duel, System.Collections.Generic.List<ulong>> ACards { get; }
        public global::SpacetimeDB.Col<Duel, System.Collections.Generic.List<ulong>> BCards { get; }
        public global::SpacetimeDB.Col<Duel, bool> ACommitted { get; }
        public global::SpacetimeDB.Col<Duel, bool> BCommitted { get; }
        public global::SpacetimeDB.Col<Duel, DuelState> State { get; }
        public global::SpacetimeDB.Col<Duel, byte> LanesA { get; }
        public global::SpacetimeDB.Col<Duel, byte> LanesB { get; }
        public global::SpacetimeDB.Col<Duel, SpacetimeDB.Identity> Winner { get; }
        public global::SpacetimeDB.Col<Duel, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<Duel, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public DuelCols(string tableName)
        {
            DuelId = new global::SpacetimeDB.Col<Duel, ulong>(tableName, "duel_id");
            ZoneId = new global::SpacetimeDB.Col<Duel, byte>(tableName, "zone_id");
            PlayerA = new global::SpacetimeDB.Col<Duel, SpacetimeDB.Identity>(tableName, "player_a");
            PlayerB = new global::SpacetimeDB.Col<Duel, SpacetimeDB.Identity>(tableName, "player_b");
            FactionA = new global::SpacetimeDB.Col<Duel, Planet>(tableName, "faction_a");
            FactionB = new global::SpacetimeDB.Col<Duel, Planet>(tableName, "faction_b");
            ACards = new global::SpacetimeDB.Col<Duel, System.Collections.Generic.List<ulong>>(tableName, "a_cards");
            BCards = new global::SpacetimeDB.Col<Duel, System.Collections.Generic.List<ulong>>(tableName, "b_cards");
            ACommitted = new global::SpacetimeDB.Col<Duel, bool>(tableName, "a_committed");
            BCommitted = new global::SpacetimeDB.Col<Duel, bool>(tableName, "b_committed");
            State = new global::SpacetimeDB.Col<Duel, DuelState>(tableName, "state");
            LanesA = new global::SpacetimeDB.Col<Duel, byte>(tableName, "lanes_a");
            LanesB = new global::SpacetimeDB.Col<Duel, byte>(tableName, "lanes_b");
            Winner = new global::SpacetimeDB.Col<Duel, SpacetimeDB.Identity>(tableName, "winner");
            CreatedAt = new global::SpacetimeDB.Col<Duel, SpacetimeDB.Timestamp>(tableName, "created_at");
            UpdatedAt = new global::SpacetimeDB.Col<Duel, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class DuelIxCols
    {
        public global::SpacetimeDB.IxCol<Duel, ulong> DuelId { get; }

        public DuelIxCols(string tableName)
        {
            DuelId = new global::SpacetimeDB.IxCol<Duel, ulong>(tableName, "duel_id");
        }
    }
}
