// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EphemerisHandle : RemoteTableHandle<EventContext, Ephemeris>
        {
            protected override string RemoteTableName => "ephemeris";

            public sealed class BodyUniqueIndex : UniqueIndexBase<Planet>
            {
                protected override Planet GetKey(Ephemeris row) => row.Body;

                public BodyUniqueIndex(EphemerisHandle table) : base(table) { }
            }

            public readonly BodyUniqueIndex Body;

            internal EphemerisHandle(DbConnection conn) : base(conn)
            {
                Body = new(this);
            }

            protected override object GetPrimaryKey(Ephemeris row) => row.Body;
        }

        public readonly EphemerisHandle Ephemeris;
    }

    public sealed class EphemerisCols
    {
        public global::SpacetimeDB.Col<Ephemeris, Planet> Body { get; }
        public global::SpacetimeDB.Col<Ephemeris, double> Ra { get; }
        public global::SpacetimeDB.Col<Ephemeris, double> Dec { get; }
        public global::SpacetimeDB.Col<Ephemeris, byte> TransitingZone { get; }
        public global::SpacetimeDB.Col<Ephemeris, SpacetimeDB.Timestamp> Tick { get; }

        public EphemerisCols(string tableName)
        {
            Body = new global::SpacetimeDB.Col<Ephemeris, Planet>(tableName, "body");
            Ra = new global::SpacetimeDB.Col<Ephemeris, double>(tableName, "ra");
            Dec = new global::SpacetimeDB.Col<Ephemeris, double>(tableName, "dec");
            TransitingZone = new global::SpacetimeDB.Col<Ephemeris, byte>(tableName, "transiting_zone");
            Tick = new global::SpacetimeDB.Col<Ephemeris, SpacetimeDB.Timestamp>(tableName, "tick");
        }
    }

    public sealed class EphemerisIxCols
    {
        public global::SpacetimeDB.IxCol<Ephemeris, Planet> Body { get; }

        public EphemerisIxCols(string tableName)
        {
            Body = new global::SpacetimeDB.IxCol<Ephemeris, Planet>(tableName, "body");
        }
    }
}
