// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameConfigHandle : RemoteTableHandle<EventContext, GameConfig>
        {
            protected override string RemoteTableName => "game_config";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(GameConfig row) => row.Id;

                public IdUniqueIndex(GameConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GameConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(GameConfig row) => row.Id;
        }

        public readonly GameConfigHandle GameConfig;
    }

    public sealed class GameConfigCols
    {
        public global::SpacetimeDB.Col<GameConfig, byte> Id { get; }
        public global::SpacetimeDB.Col<GameConfig, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<GameConfig, ushort> SeasonDegree { get; }
        public global::SpacetimeDB.Col<GameConfig, ushort> AscendantDegree { get; }
        public global::SpacetimeDB.Col<GameConfig, bool> Seeded { get; }

        public GameConfigCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GameConfig, byte>(tableName, "id");
            Owner = new global::SpacetimeDB.Col<GameConfig, SpacetimeDB.Identity>(tableName, "owner");
            SeasonDegree = new global::SpacetimeDB.Col<GameConfig, ushort>(tableName, "season_degree");
            AscendantDegree = new global::SpacetimeDB.Col<GameConfig, ushort>(tableName, "ascendant_degree");
            Seeded = new global::SpacetimeDB.Col<GameConfig, bool>(tableName, "seeded");
        }
    }

    public sealed class GameConfigIxCols
    {
        public global::SpacetimeDB.IxCol<GameConfig, byte> Id { get; }

        public GameConfigIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GameConfig, byte>(tableName, "id");
        }
    }
}
