// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class HorizonActionReceiptHandle : RemoteTableHandle<EventContext, HorizonActionReceipt>
        {
            protected override string RemoteTableName => "horizon_action_receipt";

            public sealed class ActionKeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(HorizonActionReceipt row) => row.ActionKey;

                public ActionKeyUniqueIndex(HorizonActionReceiptHandle table) : base(table) { }
            }

            public readonly ActionKeyUniqueIndex ActionKey;

            public sealed class IntentIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(HorizonActionReceipt row) => row.IntentId;

                public IntentIdIndex(HorizonActionReceiptHandle table) : base(table) { }
            }

            public readonly IntentIdIndex IntentId;

            internal HorizonActionReceiptHandle(DbConnection conn) : base(conn)
            {
                ActionKey = new(this);
                IntentId = new(this);
            }

            protected override object GetPrimaryKey(HorizonActionReceipt row) => row.ActionKey;
        }

        public readonly HorizonActionReceiptHandle HorizonActionReceipt;
    }

    public sealed class HorizonActionReceiptCols
    {
        public global::SpacetimeDB.Col<HorizonActionReceipt, string> ActionKey { get; }
        public global::SpacetimeDB.Col<HorizonActionReceipt, ulong> IntentId { get; }
        public global::SpacetimeDB.Col<HorizonActionReceipt, string> TxHash { get; }
        public global::SpacetimeDB.Col<HorizonActionReceipt, SpacetimeDB.Timestamp> ProcessedAt { get; }

        public HorizonActionReceiptCols(string tableName)
        {
            ActionKey = new global::SpacetimeDB.Col<HorizonActionReceipt, string>(tableName, "action_key");
            IntentId = new global::SpacetimeDB.Col<HorizonActionReceipt, ulong>(tableName, "intent_id");
            TxHash = new global::SpacetimeDB.Col<HorizonActionReceipt, string>(tableName, "tx_hash");
            ProcessedAt = new global::SpacetimeDB.Col<HorizonActionReceipt, SpacetimeDB.Timestamp>(tableName, "processed_at");
        }
    }

    public sealed class HorizonActionReceiptIxCols
    {
        public global::SpacetimeDB.IxCol<HorizonActionReceipt, string> ActionKey { get; }
        public global::SpacetimeDB.IxCol<HorizonActionReceipt, ulong> IntentId { get; }

        public HorizonActionReceiptIxCols(string tableName)
        {
            ActionKey = new global::SpacetimeDB.IxCol<HorizonActionReceipt, string>(tableName, "action_key");
            IntentId = new global::SpacetimeDB.IxCol<HorizonActionReceipt, ulong>(tableName, "intent_id");
        }
    }
}
