// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class JingDuelHandle : RemoteTableHandle<EventContext, JingDuel>
        {
            protected override string RemoteTableName => "jing_duel";

            public sealed class DuelIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(JingDuel row) => row.DuelId;

                public DuelIdUniqueIndex(JingDuelHandle table) : base(table) { }
            }

            public readonly DuelIdUniqueIndex DuelId;

            public sealed class InitiatorIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(JingDuel row) => row.Initiator;

                public InitiatorIndex(JingDuelHandle table) : base(table) { }
            }

            public readonly InitiatorIndex Initiator;

            internal JingDuelHandle(DbConnection conn) : base(conn)
            {
                DuelId = new(this);
                Initiator = new(this);
            }

            protected override object GetPrimaryKey(JingDuel row) => row.DuelId;
        }

        public readonly JingDuelHandle JingDuel;
    }

    public sealed class JingDuelCols
    {
        public global::SpacetimeDB.Col<JingDuel, ulong> DuelId { get; }
        public global::SpacetimeDB.Col<JingDuel, SpacetimeDB.Identity> Initiator { get; }
        public global::SpacetimeDB.Col<JingDuel, SpacetimeDB.Identity> TargetPlayer { get; }
        public global::SpacetimeDB.Col<JingDuel, Planet> TargetAgent { get; }
        public global::SpacetimeDB.Col<JingDuel, JingMove> OpeningMove { get; }
        public global::SpacetimeDB.Col<JingDuel, JingState> State { get; }
        public global::SpacetimeDB.Col<JingDuel, bool> WinnerIsInitiator { get; }
        public global::SpacetimeDB.Col<JingDuel, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<JingDuel, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public JingDuelCols(string tableName)
        {
            DuelId = new global::SpacetimeDB.Col<JingDuel, ulong>(tableName, "duel_id");
            Initiator = new global::SpacetimeDB.Col<JingDuel, SpacetimeDB.Identity>(tableName, "initiator");
            TargetPlayer = new global::SpacetimeDB.Col<JingDuel, SpacetimeDB.Identity>(tableName, "target_player");
            TargetAgent = new global::SpacetimeDB.Col<JingDuel, Planet>(tableName, "target_agent");
            OpeningMove = new global::SpacetimeDB.Col<JingDuel, JingMove>(tableName, "opening_move");
            State = new global::SpacetimeDB.Col<JingDuel, JingState>(tableName, "state");
            WinnerIsInitiator = new global::SpacetimeDB.Col<JingDuel, bool>(tableName, "winner_is_initiator");
            CreatedAt = new global::SpacetimeDB.Col<JingDuel, SpacetimeDB.Timestamp>(tableName, "created_at");
            UpdatedAt = new global::SpacetimeDB.Col<JingDuel, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class JingDuelIxCols
    {
        public global::SpacetimeDB.IxCol<JingDuel, ulong> DuelId { get; }
        public global::SpacetimeDB.IxCol<JingDuel, SpacetimeDB.Identity> Initiator { get; }

        public JingDuelIxCols(string tableName)
        {
            DuelId = new global::SpacetimeDB.IxCol<JingDuel, ulong>(tableName, "duel_id");
            Initiator = new global::SpacetimeDB.IxCol<JingDuel, SpacetimeDB.Identity>(tableName, "initiator");
        }
    }
}
