// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class JingPoolHandle : RemoteTableHandle<EventContext, JingPool>
        {
            protected override string RemoteTableName => "jing_pool";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(JingPool row) => row.Identity;

                public IdentityUniqueIndex(JingPoolHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal JingPoolHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(JingPool row) => row.Identity;
        }

        public readonly JingPoolHandle JingPool;
    }

    public sealed class JingPoolCols
    {
        public global::SpacetimeDB.Col<JingPool, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<JingPool, System.Collections.Generic.List<ushort>> Sacred7 { get; }
        public global::SpacetimeDB.Col<JingPool, System.Collections.Generic.List<ushort>> Esms { get; }
        public global::SpacetimeDB.Col<JingPool, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public JingPoolCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<JingPool, SpacetimeDB.Identity>(tableName, "identity");
            Sacred7 = new global::SpacetimeDB.Col<JingPool, System.Collections.Generic.List<ushort>>(tableName, "sacred_7");
            Esms = new global::SpacetimeDB.Col<JingPool, System.Collections.Generic.List<ushort>>(tableName, "esms");
            UpdatedAt = new global::SpacetimeDB.Col<JingPool, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class JingPoolIxCols
    {
        public global::SpacetimeDB.IxCol<JingPool, SpacetimeDB.Identity> Identity { get; }

        public JingPoolIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<JingPool, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
