// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class JingCastHandle : RemoteTableHandle<EventContext, JingCast>
        {
            protected override string RemoteTableName => "jing_cast";

            public sealed class CastIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(JingCast row) => row.CastId;

                public CastIdUniqueIndex(JingCastHandle table) : base(table) { }
            }

            public readonly CastIdUniqueIndex CastId;

            public sealed class DuelIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(JingCast row) => row.DuelId;

                public DuelIdIndex(JingCastHandle table) : base(table) { }
            }

            public readonly DuelIdIndex DuelId;

            internal JingCastHandle(DbConnection conn) : base(conn)
            {
                CastId = new(this);
                DuelId = new(this);
            }

            protected override object GetPrimaryKey(JingCast row) => row.CastId;
        }

        public readonly JingCastHandle JingCast;
    }

    public sealed class JingCastCols
    {
        public global::SpacetimeDB.Col<JingCast, ulong> CastId { get; }
        public global::SpacetimeDB.Col<JingCast, ulong> DuelId { get; }
        public global::SpacetimeDB.Col<JingCast, SpacetimeDB.Identity> Caster { get; }
        public global::SpacetimeDB.Col<JingCast, Planet> CasterAgent { get; }
        public global::SpacetimeDB.Col<JingCast, JingMove> Mv { get; }
        public global::SpacetimeDB.Col<JingCast, byte> CostSacred7 { get; }
        public global::SpacetimeDB.Col<JingCast, byte> CostEsms { get; }
        public global::SpacetimeDB.Col<JingCast, JingMove> Deflects { get; }
        public global::SpacetimeDB.Col<JingCast, string> Voice { get; }
        public global::SpacetimeDB.Col<JingCast, SpacetimeDB.Timestamp> CreatedAt { get; }

        public JingCastCols(string tableName)
        {
            CastId = new global::SpacetimeDB.Col<JingCast, ulong>(tableName, "cast_id");
            DuelId = new global::SpacetimeDB.Col<JingCast, ulong>(tableName, "duel_id");
            Caster = new global::SpacetimeDB.Col<JingCast, SpacetimeDB.Identity>(tableName, "caster");
            CasterAgent = new global::SpacetimeDB.Col<JingCast, Planet>(tableName, "caster_agent");
            Mv = new global::SpacetimeDB.Col<JingCast, JingMove>(tableName, "mv");
            CostSacred7 = new global::SpacetimeDB.Col<JingCast, byte>(tableName, "cost_sacred7");
            CostEsms = new global::SpacetimeDB.Col<JingCast, byte>(tableName, "cost_esms");
            Deflects = new global::SpacetimeDB.Col<JingCast, JingMove>(tableName, "deflects");
            Voice = new global::SpacetimeDB.Col<JingCast, string>(tableName, "voice");
            CreatedAt = new global::SpacetimeDB.Col<JingCast, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class JingCastIxCols
    {
        public global::SpacetimeDB.IxCol<JingCast, ulong> CastId { get; }
        public global::SpacetimeDB.IxCol<JingCast, ulong> DuelId { get; }

        public JingCastIxCols(string tableName)
        {
            CastId = new global::SpacetimeDB.IxCol<JingCast, ulong>(tableName, "cast_id");
            DuelId = new global::SpacetimeDB.IxCol<JingCast, ulong>(tableName, "duel_id");
        }
    }
}
