// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NatalDecanHandle : RemoteTableHandle<EventContext, NatalDecan>
        {
            protected override string RemoteTableName => "natal_decan";

            public sealed class DecanIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NatalDecan row) => row.DecanId;

                public DecanIdUniqueIndex(NatalDecanHandle table) : base(table) { }
            }

            public readonly DecanIdUniqueIndex DecanId;

            public sealed class OwnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(NatalDecan row) => row.Owner;

                public OwnerIndex(NatalDecanHandle table) : base(table) { }
            }

            public readonly OwnerIndex Owner;

            internal NatalDecanHandle(DbConnection conn) : base(conn)
            {
                DecanId = new(this);
                Owner = new(this);
            }

            protected override object GetPrimaryKey(NatalDecan row) => row.DecanId;
        }

        public readonly NatalDecanHandle NatalDecan;
    }

    public sealed class NatalDecanCols
    {
        public global::SpacetimeDB.Col<NatalDecan, ulong> DecanId { get; }
        public global::SpacetimeDB.Col<NatalDecan, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<NatalDecan, Planet> Body { get; }
        public global::SpacetimeDB.Col<NatalDecan, byte> Sign { get; }
        public global::SpacetimeDB.Col<NatalDecan, byte> Decan { get; }
        public global::SpacetimeDB.Col<NatalDecan, byte> AbsDecan { get; }
        public global::SpacetimeDB.Col<NatalDecan, Suit> Suit { get; }
        public global::SpacetimeDB.Col<NatalDecan, byte> Rank { get; }
        public global::SpacetimeDB.Col<NatalDecan, Planet> DecanRuler { get; }
        public global::SpacetimeDB.Col<NatalDecan, bool> Retrograde { get; }

        public NatalDecanCols(string tableName)
        {
            DecanId = new global::SpacetimeDB.Col<NatalDecan, ulong>(tableName, "decan_id");
            Owner = new global::SpacetimeDB.Col<NatalDecan, SpacetimeDB.Identity>(tableName, "owner");
            Body = new global::SpacetimeDB.Col<NatalDecan, Planet>(tableName, "body");
            Sign = new global::SpacetimeDB.Col<NatalDecan, byte>(tableName, "sign");
            Decan = new global::SpacetimeDB.Col<NatalDecan, byte>(tableName, "decan");
            AbsDecan = new global::SpacetimeDB.Col<NatalDecan, byte>(tableName, "abs_decan");
            Suit = new global::SpacetimeDB.Col<NatalDecan, Suit>(tableName, "suit");
            Rank = new global::SpacetimeDB.Col<NatalDecan, byte>(tableName, "rank");
            DecanRuler = new global::SpacetimeDB.Col<NatalDecan, Planet>(tableName, "decan_ruler");
            Retrograde = new global::SpacetimeDB.Col<NatalDecan, bool>(tableName, "retrograde");
        }
    }

    public sealed class NatalDecanIxCols
    {
        public global::SpacetimeDB.IxCol<NatalDecan, ulong> DecanId { get; }
        public global::SpacetimeDB.IxCol<NatalDecan, SpacetimeDB.Identity> Owner { get; }

        public NatalDecanIxCols(string tableName)
        {
            DecanId = new global::SpacetimeDB.IxCol<NatalDecan, ulong>(tableName, "decan_id");
            Owner = new global::SpacetimeDB.IxCol<NatalDecan, SpacetimeDB.Identity>(tableName, "owner");
        }
    }
}
