// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OracleRequestHandle : RemoteTableHandle<EventContext, OracleRequest>
        {
            protected override string RemoteTableName => "oracle_request";

            public sealed class RequestIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(OracleRequest row) => row.RequestId;

                public RequestIdUniqueIndex(OracleRequestHandle table) : base(table) { }
            }

            public readonly RequestIdUniqueIndex RequestId;

            internal OracleRequestHandle(DbConnection conn) : base(conn)
            {
                RequestId = new(this);
            }

            protected override object GetPrimaryKey(OracleRequest row) => row.RequestId;
        }

        public readonly OracleRequestHandle OracleRequest;
    }

    public sealed class OracleRequestCols
    {
        public global::SpacetimeDB.Col<OracleRequest, ulong> RequestId { get; }
        public global::SpacetimeDB.Col<OracleRequest, SpacetimeDB.Identity> Asker { get; }
        public global::SpacetimeDB.Col<OracleRequest, string> Question { get; }
        public global::SpacetimeDB.Col<OracleRequest, string> Context { get; }
        public global::SpacetimeDB.Col<OracleRequest, bool> Cacheable { get; }
        public global::SpacetimeDB.Col<OracleRequest, ulong> Qhash { get; }
        public global::SpacetimeDB.Col<OracleRequest, bool> Answered { get; }
        public global::SpacetimeDB.Col<OracleRequest, SpacetimeDB.Timestamp> CreatedAt { get; }

        public OracleRequestCols(string tableName)
        {
            RequestId = new global::SpacetimeDB.Col<OracleRequest, ulong>(tableName, "request_id");
            Asker = new global::SpacetimeDB.Col<OracleRequest, SpacetimeDB.Identity>(tableName, "asker");
            Question = new global::SpacetimeDB.Col<OracleRequest, string>(tableName, "question");
            Context = new global::SpacetimeDB.Col<OracleRequest, string>(tableName, "context");
            Cacheable = new global::SpacetimeDB.Col<OracleRequest, bool>(tableName, "cacheable");
            Qhash = new global::SpacetimeDB.Col<OracleRequest, ulong>(tableName, "qhash");
            Answered = new global::SpacetimeDB.Col<OracleRequest, bool>(tableName, "answered");
            CreatedAt = new global::SpacetimeDB.Col<OracleRequest, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class OracleRequestIxCols
    {
        public global::SpacetimeDB.IxCol<OracleRequest, ulong> RequestId { get; }

        public OracleRequestIxCols(string tableName)
        {
            RequestId = new global::SpacetimeDB.IxCol<OracleRequest, ulong>(tableName, "request_id");
        }
    }
}
