// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OracleCacheHandle : RemoteTableHandle<EventContext, OracleCache>
        {
            protected override string RemoteTableName => "oracle_cache";

            public sealed class QhashUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(OracleCache row) => row.Qhash;

                public QhashUniqueIndex(OracleCacheHandle table) : base(table) { }
            }

            public readonly QhashUniqueIndex Qhash;

            internal OracleCacheHandle(DbConnection conn) : base(conn)
            {
                Qhash = new(this);
            }

            protected override object GetPrimaryKey(OracleCache row) => row.Qhash;
        }

        public readonly OracleCacheHandle OracleCache;
    }

    public sealed class OracleCacheCols
    {
        public global::SpacetimeDB.Col<OracleCache, ulong> Qhash { get; }
        public global::SpacetimeDB.Col<OracleCache, string> Question { get; }
        public global::SpacetimeDB.Col<OracleCache, string> Text { get; }
        public global::SpacetimeDB.Col<OracleCache, string> Model { get; }
        public global::SpacetimeDB.Col<OracleCache, SpacetimeDB.Timestamp> CreatedAt { get; }

        public OracleCacheCols(string tableName)
        {
            Qhash = new global::SpacetimeDB.Col<OracleCache, ulong>(tableName, "qhash");
            Question = new global::SpacetimeDB.Col<OracleCache, string>(tableName, "question");
            Text = new global::SpacetimeDB.Col<OracleCache, string>(tableName, "text");
            Model = new global::SpacetimeDB.Col<OracleCache, string>(tableName, "model");
            CreatedAt = new global::SpacetimeDB.Col<OracleCache, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class OracleCacheIxCols
    {
        public global::SpacetimeDB.IxCol<OracleCache, ulong> Qhash { get; }

        public OracleCacheIxCols(string tableName)
        {
            Qhash = new global::SpacetimeDB.IxCol<OracleCache, ulong>(tableName, "qhash");
        }
    }
}
