// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OracleReplyHandle : RemoteTableHandle<EventContext, OracleReply>
        {
            protected override string RemoteTableName => "oracle_reply";

            public sealed class RequestIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(OracleReply row) => row.RequestId;

                public RequestIdUniqueIndex(OracleReplyHandle table) : base(table) { }
            }

            public readonly RequestIdUniqueIndex RequestId;

            internal OracleReplyHandle(DbConnection conn) : base(conn)
            {
                RequestId = new(this);
            }

            protected override object GetPrimaryKey(OracleReply row) => row.RequestId;
        }

        public readonly OracleReplyHandle OracleReply;
    }

    public sealed class OracleReplyCols
    {
        public global::SpacetimeDB.Col<OracleReply, ulong> RequestId { get; }
        public global::SpacetimeDB.Col<OracleReply, SpacetimeDB.Identity> Asker { get; }
        public global::SpacetimeDB.Col<OracleReply, string> Text { get; }
        public global::SpacetimeDB.Col<OracleReply, string> Model { get; }
        public global::SpacetimeDB.Col<OracleReply, SpacetimeDB.Timestamp> CreatedAt { get; }

        public OracleReplyCols(string tableName)
        {
            RequestId = new global::SpacetimeDB.Col<OracleReply, ulong>(tableName, "request_id");
            Asker = new global::SpacetimeDB.Col<OracleReply, SpacetimeDB.Identity>(tableName, "asker");
            Text = new global::SpacetimeDB.Col<OracleReply, string>(tableName, "text");
            Model = new global::SpacetimeDB.Col<OracleReply, string>(tableName, "model");
            CreatedAt = new global::SpacetimeDB.Col<OracleReply, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class OracleReplyIxCols
    {
        public global::SpacetimeDB.IxCol<OracleReply, ulong> RequestId { get; }

        public OracleReplyIxCols(string tableName)
        {
            RequestId = new global::SpacetimeDB.IxCol<OracleReply, ulong>(tableName, "request_id");
        }
    }
}
