// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, Player>
        {
            protected override string RemoteTableName => "player";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Identity;

                public IdentityUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Identity;
        }

        public readonly PlayerHandle Player;
    }

    public sealed class PlayerCols
    {
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<Player, string> Handle { get; }
        public global::SpacetimeDB.Col<Player, Planet> Faction { get; }
        public global::SpacetimeDB.Col<Player, ulong> DeckSeed { get; }
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Timestamp> LastActive { get; }
        public global::SpacetimeDB.Col<Player, ulong> Tokens { get; }
        public global::SpacetimeDB.Col<Player, uint> WordWins { get; }

        public PlayerCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "identity");
            Handle = new global::SpacetimeDB.Col<Player, string>(tableName, "handle");
            Faction = new global::SpacetimeDB.Col<Player, Planet>(tableName, "faction");
            DeckSeed = new global::SpacetimeDB.Col<Player, ulong>(tableName, "deck_seed");
            CreatedAt = new global::SpacetimeDB.Col<Player, SpacetimeDB.Timestamp>(tableName, "created_at");
            LastActive = new global::SpacetimeDB.Col<Player, SpacetimeDB.Timestamp>(tableName, "last_active");
            Tokens = new global::SpacetimeDB.Col<Player, ulong>(tableName, "tokens");
            WordWins = new global::SpacetimeDB.Col<Player, uint>(tableName, "word_wins");
        }
    }

    public sealed class PlayerIxCols
    {
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> Identity { get; }

        public PlayerIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
