// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProcessedTxHandle : RemoteTableHandle<EventContext, ProcessedTx>
        {
            protected override string RemoteTableName => "processed_tx";

            public sealed class TxHashUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ProcessedTx row) => row.TxHash;

                public TxHashUniqueIndex(ProcessedTxHandle table) : base(table) { }
            }

            public readonly TxHashUniqueIndex TxHash;

            internal ProcessedTxHandle(DbConnection conn) : base(conn)
            {
                TxHash = new(this);
            }

            protected override object GetPrimaryKey(ProcessedTx row) => row.TxHash;
        }

        public readonly ProcessedTxHandle ProcessedTx;
    }

    public sealed class ProcessedTxCols
    {
        public global::SpacetimeDB.Col<ProcessedTx, string> TxHash { get; }
        public global::SpacetimeDB.Col<ProcessedTx, string> Chain { get; }
        public global::SpacetimeDB.Col<ProcessedTx, string> EventType { get; }
        public global::SpacetimeDB.Col<ProcessedTx, SpacetimeDB.Timestamp> ProcessedAt { get; }

        public ProcessedTxCols(string tableName)
        {
            TxHash = new global::SpacetimeDB.Col<ProcessedTx, string>(tableName, "tx_hash");
            Chain = new global::SpacetimeDB.Col<ProcessedTx, string>(tableName, "chain");
            EventType = new global::SpacetimeDB.Col<ProcessedTx, string>(tableName, "event_type");
            ProcessedAt = new global::SpacetimeDB.Col<ProcessedTx, SpacetimeDB.Timestamp>(tableName, "processed_at");
        }
    }

    public sealed class ProcessedTxIxCols
    {
        public global::SpacetimeDB.IxCol<ProcessedTx, string> TxHash { get; }

        public ProcessedTxIxCols(string tableName)
        {
            TxHash = new global::SpacetimeDB.IxCol<ProcessedTx, string>(tableName, "tx_hash");
        }
    }
}
