// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RoundParticipantHandle : RemoteTableHandle<EventContext, RoundParticipant>
        {
            protected override string RemoteTableName => "round_participant";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RoundParticipant row) => row.Id;

                public IdUniqueIndex(RoundParticipantHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class RoundIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(RoundParticipant row) => row.RoundId;

                public RoundIdIndex(RoundParticipantHandle table) : base(table) { }
            }

            public readonly RoundIdIndex RoundId;

            internal RoundParticipantHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                RoundId = new(this);
            }

            protected override object GetPrimaryKey(RoundParticipant row) => row.Id;
        }

        public readonly RoundParticipantHandle RoundParticipant;
    }

    public sealed class RoundParticipantCols
    {
        public global::SpacetimeDB.Col<RoundParticipant, ulong> Id { get; }
        public global::SpacetimeDB.Col<RoundParticipant, ulong> RoundId { get; }
        public global::SpacetimeDB.Col<RoundParticipant, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<RoundParticipant, byte> Element { get; }
        public global::SpacetimeDB.Col<RoundParticipant, uint> Weight { get; }

        public RoundParticipantCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<RoundParticipant, ulong>(tableName, "id");
            RoundId = new global::SpacetimeDB.Col<RoundParticipant, ulong>(tableName, "round_id");
            Identity = new global::SpacetimeDB.Col<RoundParticipant, SpacetimeDB.Identity>(tableName, "identity");
            Element = new global::SpacetimeDB.Col<RoundParticipant, byte>(tableName, "element");
            Weight = new global::SpacetimeDB.Col<RoundParticipant, uint>(tableName, "weight");
        }
    }

    public sealed class RoundParticipantIxCols
    {
        public global::SpacetimeDB.IxCol<RoundParticipant, ulong> Id { get; }
        public global::SpacetimeDB.IxCol<RoundParticipant, ulong> RoundId { get; }

        public RoundParticipantIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<RoundParticipant, ulong>(tableName, "id");
            RoundId = new global::SpacetimeDB.IxCol<RoundParticipant, ulong>(tableName, "round_id");
        }
    }
}
