// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RoundStateHandle : RemoteTableHandle<EventContext, RoundState>
        {
            protected override string RemoteTableName => "round_state";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(RoundState row) => row.Identity;

                public IdentityUniqueIndex(RoundStateHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal RoundStateHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(RoundState row) => row.Identity;
        }

        public readonly RoundStateHandle RoundState;
    }

    public sealed class RoundStateCols
    {
        public global::SpacetimeDB.Col<RoundState, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<RoundState, ulong> RoundIndex { get; }
        public global::SpacetimeDB.Col<RoundState, uint> Wins { get; }
        public global::SpacetimeDB.Col<RoundState, uint> Fights { get; }
        public global::SpacetimeDB.Col<RoundState, SpacetimeDB.Timestamp> LastResolvedAt { get; }

        public RoundStateCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<RoundState, SpacetimeDB.Identity>(tableName, "identity");
            RoundIndex = new global::SpacetimeDB.Col<RoundState, ulong>(tableName, "round_index");
            Wins = new global::SpacetimeDB.Col<RoundState, uint>(tableName, "wins");
            Fights = new global::SpacetimeDB.Col<RoundState, uint>(tableName, "fights");
            LastResolvedAt = new global::SpacetimeDB.Col<RoundState, SpacetimeDB.Timestamp>(tableName, "last_resolved_at");
        }
    }

    public sealed class RoundStateIxCols
    {
        public global::SpacetimeDB.IxCol<RoundState, SpacetimeDB.Identity> Identity { get; }

        public RoundStateIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<RoundState, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
