// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ServiceStatusHandle : RemoteTableHandle<EventContext, ServiceStatus>
        {
            protected override string RemoteTableName => "service_status";

            public sealed class ServiceUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ServiceStatus row) => row.Service;

                public ServiceUniqueIndex(ServiceStatusHandle table) : base(table) { }
            }

            public readonly ServiceUniqueIndex Service;

            internal ServiceStatusHandle(DbConnection conn) : base(conn)
            {
                Service = new(this);
            }

            protected override object GetPrimaryKey(ServiceStatus row) => row.Service;
        }

        public readonly ServiceStatusHandle ServiceStatus;
    }

    public sealed class ServiceStatusCols
    {
        public global::SpacetimeDB.Col<ServiceStatus, string> Service { get; }
        public global::SpacetimeDB.Col<ServiceStatus, bool> Healthy { get; }
        public global::SpacetimeDB.Col<ServiceStatus, string> Detail { get; }
        public global::SpacetimeDB.Col<ServiceStatus, uint> LatencyMs { get; }
        public global::SpacetimeDB.Col<ServiceStatus, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public ServiceStatusCols(string tableName)
        {
            Service = new global::SpacetimeDB.Col<ServiceStatus, string>(tableName, "service");
            Healthy = new global::SpacetimeDB.Col<ServiceStatus, bool>(tableName, "healthy");
            Detail = new global::SpacetimeDB.Col<ServiceStatus, string>(tableName, "detail");
            LatencyMs = new global::SpacetimeDB.Col<ServiceStatus, uint>(tableName, "latency_ms");
            UpdatedAt = new global::SpacetimeDB.Col<ServiceStatus, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class ServiceStatusIxCols
    {
        public global::SpacetimeDB.IxCol<ServiceStatus, string> Service { get; }

        public ServiceStatusIxCols(string tableName)
        {
            Service = new global::SpacetimeDB.IxCol<ServiceStatus, string>(tableName, "service");
        }
    }
}
