// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StarNodeHandle : RemoteTableHandle<EventContext, StarNode>
        {
            protected override string RemoteTableName => "star_node";

            public sealed class HipIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(StarNode row) => row.HipId;

                public HipIdUniqueIndex(StarNodeHandle table) : base(table) { }
            }

            public readonly HipIdUniqueIndex HipId;

            internal StarNodeHandle(DbConnection conn) : base(conn)
            {
                HipId = new(this);
            }

            protected override object GetPrimaryKey(StarNode row) => row.HipId;
        }

        public readonly StarNodeHandle StarNode;
    }

    public sealed class StarNodeCols
    {
        public global::SpacetimeDB.Col<StarNode, uint> HipId { get; }
        public global::SpacetimeDB.Col<StarNode, string> Name { get; }
        public global::SpacetimeDB.Col<StarNode, double> Ra { get; }
        public global::SpacetimeDB.Col<StarNode, double> Dec { get; }
        public global::SpacetimeDB.Col<StarNode, float> Magnitude { get; }
        public global::SpacetimeDB.Col<StarNode, Planet> HeldBy { get; }
        public global::SpacetimeDB.Col<StarNode, byte> RegionHint { get; }

        public StarNodeCols(string tableName)
        {
            HipId = new global::SpacetimeDB.Col<StarNode, uint>(tableName, "hip_id");
            Name = new global::SpacetimeDB.Col<StarNode, string>(tableName, "name");
            Ra = new global::SpacetimeDB.Col<StarNode, double>(tableName, "ra");
            Dec = new global::SpacetimeDB.Col<StarNode, double>(tableName, "dec");
            Magnitude = new global::SpacetimeDB.Col<StarNode, float>(tableName, "magnitude");
            HeldBy = new global::SpacetimeDB.Col<StarNode, Planet>(tableName, "held_by");
            RegionHint = new global::SpacetimeDB.Col<StarNode, byte>(tableName, "region_hint");
        }
    }

    public sealed class StarNodeIxCols
    {
        public global::SpacetimeDB.IxCol<StarNode, uint> HipId { get; }

        public StarNodeIxCols(string tableName)
        {
            HipId = new global::SpacetimeDB.IxCol<StarNode, uint>(tableName, "hip_id");
        }
    }
}
