// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StarAgentHandle : RemoteTableHandle<EventContext, StarAgent>
        {
            protected override string RemoteTableName => "star_agent";

            public sealed class HipIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(StarAgent row) => row.HipId;

                public HipIdUniqueIndex(StarAgentHandle table) : base(table) { }
            }

            public readonly HipIdUniqueIndex HipId;

            internal StarAgentHandle(DbConnection conn) : base(conn)
            {
                HipId = new(this);
            }

            protected override object GetPrimaryKey(StarAgent row) => row.HipId;
        }

        public readonly StarAgentHandle StarAgent;
    }

    public sealed class StarAgentCols
    {
        public global::SpacetimeDB.Col<StarAgent, uint> HipId { get; }
        public global::SpacetimeDB.Col<StarAgent, string> DisplayName { get; }
        public global::SpacetimeDB.Col<StarAgent, byte> Element { get; }
        public global::SpacetimeDB.Col<StarAgent, System.Collections.Generic.List<ushort>> Composition { get; }
        public global::SpacetimeDB.Col<StarAgent, string> Specialty { get; }
        public global::SpacetimeDB.Col<StarAgent, bool> Active { get; }

        public StarAgentCols(string tableName)
        {
            HipId = new global::SpacetimeDB.Col<StarAgent, uint>(tableName, "hip_id");
            DisplayName = new global::SpacetimeDB.Col<StarAgent, string>(tableName, "display_name");
            Element = new global::SpacetimeDB.Col<StarAgent, byte>(tableName, "element");
            Composition = new global::SpacetimeDB.Col<StarAgent, System.Collections.Generic.List<ushort>>(tableName, "composition");
            Specialty = new global::SpacetimeDB.Col<StarAgent, string>(tableName, "specialty");
            Active = new global::SpacetimeDB.Col<StarAgent, bool>(tableName, "active");
        }
    }

    public sealed class StarAgentIxCols
    {
        public global::SpacetimeDB.IxCol<StarAgent, uint> HipId { get; }

        public StarAgentIxCols(string tableName)
        {
            HipId = new global::SpacetimeDB.IxCol<StarAgent, uint>(tableName, "hip_id");
        }
    }
}
