// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StarStakePoolHandle : RemoteTableHandle<EventContext, StarStakePool>
        {
            protected override string RemoteTableName => "star_stake_pool";

            public sealed class StarIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(StarStakePool row) => row.StarId;

                public StarIdUniqueIndex(StarStakePoolHandle table) : base(table) { }
            }

            public readonly StarIdUniqueIndex StarId;

            internal StarStakePoolHandle(DbConnection conn) : base(conn)
            {
                StarId = new(this);
            }

            protected override object GetPrimaryKey(StarStakePool row) => row.StarId;
        }

        public readonly StarStakePoolHandle StarStakePool;
    }

    public sealed class StarStakePoolCols
    {
        public global::SpacetimeDB.Col<StarStakePool, uint> StarId { get; }
        public global::SpacetimeDB.Col<StarStakePool, ulong> TotalPrincipalUsdc { get; }
        public global::SpacetimeDB.Col<StarStakePool, U128> TotalShares { get; }

        public StarStakePoolCols(string tableName)
        {
            StarId = new global::SpacetimeDB.Col<StarStakePool, uint>(tableName, "star_id");
            TotalPrincipalUsdc = new global::SpacetimeDB.Col<StarStakePool, ulong>(tableName, "total_principal_usdc");
            TotalShares = new global::SpacetimeDB.Col<StarStakePool, U128>(tableName, "total_shares");
        }
    }

    public sealed class StarStakePoolIxCols
    {
        public global::SpacetimeDB.IxCol<StarStakePool, uint> StarId { get; }

        public StarStakePoolIxCols(string tableName)
        {
            StarId = new global::SpacetimeDB.IxCol<StarStakePool, uint>(tableName, "star_id");
        }
    }
}
