// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StarStakeHandle : RemoteTableHandle<EventContext, StarStake>
        {
            protected override string RemoteTableName => "star_stake";

            public sealed class StakeIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(StarStake row) => row.StakeId;

                public StakeIdUniqueIndex(StarStakeHandle table) : base(table) { }
            }

            public readonly StakeIdUniqueIndex StakeId;

            public sealed class StakerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(StarStake row) => row.Staker;

                public StakerIndex(StarStakeHandle table) : base(table) { }
            }

            public readonly StakerIndex Staker;

            public sealed class StarIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(StarStake row) => row.StarId;

                public StarIdIndex(StarStakeHandle table) : base(table) { }
            }

            public readonly StarIdIndex StarId;

            internal StarStakeHandle(DbConnection conn) : base(conn)
            {
                StakeId = new(this);
                Staker = new(this);
                StarId = new(this);
            }

            protected override object GetPrimaryKey(StarStake row) => row.StakeId;
        }

        public readonly StarStakeHandle StarStake;
    }

    public sealed class StarStakeCols
    {
        public global::SpacetimeDB.Col<StarStake, ulong> StakeId { get; }
        public global::SpacetimeDB.Col<StarStake, SpacetimeDB.Identity> Staker { get; }
        public global::SpacetimeDB.Col<StarStake, uint> StarId { get; }
        public global::SpacetimeDB.Col<StarStake, byte> Element { get; }
        public global::SpacetimeDB.Col<StarStake, ulong> PrincipalUsdc { get; }
        public global::SpacetimeDB.Col<StarStake, U128> Shares { get; }
        public global::SpacetimeDB.Col<StarStake, U128> AccruedEssence { get; }
        public global::SpacetimeDB.Col<StarStake, U128> ClaimedEssence { get; }
        public global::SpacetimeDB.Col<StarStake, U128> PendingEssence { get; }
        public global::SpacetimeDB.Col<StarStake, ulong> ClaimNonce { get; }
        public global::SpacetimeDB.Col<StarStake, SpacetimeDB.Timestamp> StakedAt { get; }
        public global::SpacetimeDB.Col<StarStake, SpacetimeDB.Timestamp> LastAccrualAt { get; }

        public StarStakeCols(string tableName)
        {
            StakeId = new global::SpacetimeDB.Col<StarStake, ulong>(tableName, "stake_id");
            Staker = new global::SpacetimeDB.Col<StarStake, SpacetimeDB.Identity>(tableName, "staker");
            StarId = new global::SpacetimeDB.Col<StarStake, uint>(tableName, "star_id");
            Element = new global::SpacetimeDB.Col<StarStake, byte>(tableName, "element");
            PrincipalUsdc = new global::SpacetimeDB.Col<StarStake, ulong>(tableName, "principal_usdc");
            Shares = new global::SpacetimeDB.Col<StarStake, U128>(tableName, "shares");
            AccruedEssence = new global::SpacetimeDB.Col<StarStake, U128>(tableName, "accrued_essence");
            ClaimedEssence = new global::SpacetimeDB.Col<StarStake, U128>(tableName, "claimed_essence");
            PendingEssence = new global::SpacetimeDB.Col<StarStake, U128>(tableName, "pending_essence");
            ClaimNonce = new global::SpacetimeDB.Col<StarStake, ulong>(tableName, "claim_nonce");
            StakedAt = new global::SpacetimeDB.Col<StarStake, SpacetimeDB.Timestamp>(tableName, "staked_at");
            LastAccrualAt = new global::SpacetimeDB.Col<StarStake, SpacetimeDB.Timestamp>(tableName, "last_accrual_at");
        }
    }

    public sealed class StarStakeIxCols
    {
        public global::SpacetimeDB.IxCol<StarStake, ulong> StakeId { get; }
        public global::SpacetimeDB.IxCol<StarStake, SpacetimeDB.Identity> Staker { get; }
        public global::SpacetimeDB.IxCol<StarStake, uint> StarId { get; }

        public StarStakeIxCols(string tableName)
        {
            StakeId = new global::SpacetimeDB.IxCol<StarStake, ulong>(tableName, "stake_id");
            Staker = new global::SpacetimeDB.IxCol<StarStake, SpacetimeDB.Identity>(tableName, "staker");
            StarId = new global::SpacetimeDB.IxCol<StarStake, uint>(tableName, "star_id");
        }
    }
}
