// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TraceAttestationHandle : RemoteTableHandle<EventContext, TraceAttestation>
        {
            protected override string RemoteTableName => "trace_attestation";

            public sealed class IntentIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TraceAttestation row) => row.IntentId;

                public IntentIdUniqueIndex(TraceAttestationHandle table) : base(table) { }
            }

            public readonly IntentIdUniqueIndex IntentId;

            public sealed class TraderIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(TraceAttestation row) => row.Trader;

                public TraderIndex(TraceAttestationHandle table) : base(table) { }
            }

            public readonly TraderIndex Trader;

            internal TraceAttestationHandle(DbConnection conn) : base(conn)
            {
                IntentId = new(this);
                Trader = new(this);
            }

            protected override object GetPrimaryKey(TraceAttestation row) => row.IntentId;
        }

        public readonly TraceAttestationHandle TraceAttestation;
    }

    public sealed class TraceAttestationCols
    {
        public global::SpacetimeDB.Col<TraceAttestation, ulong> IntentId { get; }
        public global::SpacetimeDB.Col<TraceAttestation, SpacetimeDB.Identity> Trader { get; }
        public global::SpacetimeDB.Col<TraceAttestation, ushort> ConstellationId { get; }
        public global::SpacetimeDB.Col<TraceAttestation, string> RegionCommit { get; }
        public global::SpacetimeDB.Col<TraceAttestation, byte> VisibleStars { get; }
        public global::SpacetimeDB.Col<TraceAttestation, ulong> Nonce { get; }
        public global::SpacetimeDB.Col<TraceAttestation, ulong> Deadline { get; }
        public global::SpacetimeDB.Col<TraceAttestation, string> Signature { get; }
        public global::SpacetimeDB.Col<TraceAttestation, SpacetimeDB.Timestamp> CreatedAt { get; }

        public TraceAttestationCols(string tableName)
        {
            IntentId = new global::SpacetimeDB.Col<TraceAttestation, ulong>(tableName, "intent_id");
            Trader = new global::SpacetimeDB.Col<TraceAttestation, SpacetimeDB.Identity>(tableName, "trader");
            ConstellationId = new global::SpacetimeDB.Col<TraceAttestation, ushort>(tableName, "constellation_id");
            RegionCommit = new global::SpacetimeDB.Col<TraceAttestation, string>(tableName, "region_commit");
            VisibleStars = new global::SpacetimeDB.Col<TraceAttestation, byte>(tableName, "visible_stars");
            Nonce = new global::SpacetimeDB.Col<TraceAttestation, ulong>(tableName, "nonce");
            Deadline = new global::SpacetimeDB.Col<TraceAttestation, ulong>(tableName, "deadline");
            Signature = new global::SpacetimeDB.Col<TraceAttestation, string>(tableName, "signature");
            CreatedAt = new global::SpacetimeDB.Col<TraceAttestation, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class TraceAttestationIxCols
    {
        public global::SpacetimeDB.IxCol<TraceAttestation, ulong> IntentId { get; }
        public global::SpacetimeDB.IxCol<TraceAttestation, SpacetimeDB.Identity> Trader { get; }

        public TraceAttestationIxCols(string tableName)
        {
            IntentId = new global::SpacetimeDB.IxCol<TraceAttestation, ulong>(tableName, "intent_id");
            Trader = new global::SpacetimeDB.IxCol<TraceAttestation, SpacetimeDB.Identity>(tableName, "trader");
        }
    }
}
