// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TraceIntentHandle : RemoteTableHandle<EventContext, TraceIntent>
        {
            protected override string RemoteTableName => "trace_intent";

            public sealed class IntentIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TraceIntent row) => row.IntentId;

                public IntentIdUniqueIndex(TraceIntentHandle table) : base(table) { }
            }

            public readonly IntentIdUniqueIndex IntentId;

            public sealed class TraderIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(TraceIntent row) => row.Trader;

                public TraderIndex(TraceIntentHandle table) : base(table) { }
            }

            public readonly TraderIndex Trader;

            internal TraceIntentHandle(DbConnection conn) : base(conn)
            {
                IntentId = new(this);
                Trader = new(this);
            }

            protected override object GetPrimaryKey(TraceIntent row) => row.IntentId;
        }

        public readonly TraceIntentHandle TraceIntent;
    }

    public sealed class TraceIntentCols
    {
        public global::SpacetimeDB.Col<TraceIntent, ulong> IntentId { get; }
        public global::SpacetimeDB.Col<TraceIntent, SpacetimeDB.Identity> Trader { get; }
        public global::SpacetimeDB.Col<TraceIntent, string> EvmAddress { get; }
        public global::SpacetimeDB.Col<TraceIntent, ushort> ConstellationId { get; }
        public global::SpacetimeDB.Col<TraceIntent, ushort> VisibleStars { get; }
        public global::SpacetimeDB.Col<TraceIntent, bool> Attested { get; }
        public global::SpacetimeDB.Col<TraceIntent, SpacetimeDB.Timestamp> CreatedAt { get; }

        public TraceIntentCols(string tableName)
        {
            IntentId = new global::SpacetimeDB.Col<TraceIntent, ulong>(tableName, "intent_id");
            Trader = new global::SpacetimeDB.Col<TraceIntent, SpacetimeDB.Identity>(tableName, "trader");
            EvmAddress = new global::SpacetimeDB.Col<TraceIntent, string>(tableName, "evm_address");
            ConstellationId = new global::SpacetimeDB.Col<TraceIntent, ushort>(tableName, "constellation_id");
            VisibleStars = new global::SpacetimeDB.Col<TraceIntent, ushort>(tableName, "visible_stars");
            Attested = new global::SpacetimeDB.Col<TraceIntent, bool>(tableName, "attested");
            CreatedAt = new global::SpacetimeDB.Col<TraceIntent, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class TraceIntentIxCols
    {
        public global::SpacetimeDB.IxCol<TraceIntent, ulong> IntentId { get; }
        public global::SpacetimeDB.IxCol<TraceIntent, SpacetimeDB.Identity> Trader { get; }

        public TraceIntentIxCols(string tableName)
        {
            IntentId = new global::SpacetimeDB.IxCol<TraceIntent, ulong>(tableName, "intent_id");
            Trader = new global::SpacetimeDB.IxCol<TraceIntent, SpacetimeDB.Identity>(tableName, "trader");
        }
    }
}
