// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TradeHandle : RemoteTableHandle<EventContext, Trade>
        {
            protected override string RemoteTableName => "trade";

            public sealed class PartnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Trade row) => row.Partner;

                public PartnerIndex(TradeHandle table) : base(table) { }
            }

            public readonly PartnerIndex Partner;

            public sealed class ProposerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Trade row) => row.Proposer;

                public ProposerIndex(TradeHandle table) : base(table) { }
            }

            public readonly ProposerIndex Proposer;

            public sealed class TradeIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Trade row) => row.TradeId;

                public TradeIdUniqueIndex(TradeHandle table) : base(table) { }
            }

            public readonly TradeIdUniqueIndex TradeId;

            internal TradeHandle(DbConnection conn) : base(conn)
            {
                Partner = new(this);
                Proposer = new(this);
                TradeId = new(this);
            }

            protected override object GetPrimaryKey(Trade row) => row.TradeId;
        }

        public readonly TradeHandle Trade;
    }

    public sealed class TradeCols
    {
        public global::SpacetimeDB.Col<Trade, ulong> TradeId { get; }
        public global::SpacetimeDB.Col<Trade, SpacetimeDB.Identity> Proposer { get; }
        public global::SpacetimeDB.Col<Trade, SpacetimeDB.Identity> Partner { get; }
        public global::SpacetimeDB.Col<Trade, System.Collections.Generic.List<ulong>> Offer { get; }
        public global::SpacetimeDB.Col<Trade, System.Collections.Generic.List<ulong>> Request { get; }
        public global::SpacetimeDB.Col<Trade, bool> ProposerOk { get; }
        public global::SpacetimeDB.Col<Trade, bool> PartnerOk { get; }
        public global::SpacetimeDB.Col<Trade, TradeState> State { get; }
        public global::SpacetimeDB.Col<Trade, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<Trade, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public TradeCols(string tableName)
        {
            TradeId = new global::SpacetimeDB.Col<Trade, ulong>(tableName, "trade_id");
            Proposer = new global::SpacetimeDB.Col<Trade, SpacetimeDB.Identity>(tableName, "proposer");
            Partner = new global::SpacetimeDB.Col<Trade, SpacetimeDB.Identity>(tableName, "partner");
            Offer = new global::SpacetimeDB.Col<Trade, System.Collections.Generic.List<ulong>>(tableName, "offer");
            Request = new global::SpacetimeDB.Col<Trade, System.Collections.Generic.List<ulong>>(tableName, "request");
            ProposerOk = new global::SpacetimeDB.Col<Trade, bool>(tableName, "proposer_ok");
            PartnerOk = new global::SpacetimeDB.Col<Trade, bool>(tableName, "partner_ok");
            State = new global::SpacetimeDB.Col<Trade, TradeState>(tableName, "state");
            CreatedAt = new global::SpacetimeDB.Col<Trade, SpacetimeDB.Timestamp>(tableName, "created_at");
            UpdatedAt = new global::SpacetimeDB.Col<Trade, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class TradeIxCols
    {
        public global::SpacetimeDB.IxCol<Trade, ulong> TradeId { get; }
        public global::SpacetimeDB.IxCol<Trade, SpacetimeDB.Identity> Proposer { get; }
        public global::SpacetimeDB.IxCol<Trade, SpacetimeDB.Identity> Partner { get; }

        public TradeIxCols(string tableName)
        {
            TradeId = new global::SpacetimeDB.IxCol<Trade, ulong>(tableName, "trade_id");
            Proposer = new global::SpacetimeDB.IxCol<Trade, SpacetimeDB.Identity>(tableName, "proposer");
            Partner = new global::SpacetimeDB.IxCol<Trade, SpacetimeDB.Identity>(tableName, "partner");
        }
    }
}
