// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class VerifiedEvmWalletHandle : RemoteTableHandle<EventContext, VerifiedEvmWallet>
        {
            protected override string RemoteTableName => "verified_evm_wallet";

            public sealed class EvmAddressUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(VerifiedEvmWallet row) => row.EvmAddress;

                public EvmAddressUniqueIndex(VerifiedEvmWalletHandle table) : base(table) { }
            }

            public readonly EvmAddressUniqueIndex EvmAddress;

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(VerifiedEvmWallet row) => row.Identity;

                public IdentityUniqueIndex(VerifiedEvmWalletHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal VerifiedEvmWalletHandle(DbConnection conn) : base(conn)
            {
                EvmAddress = new(this);
                Identity = new(this);
            }

            protected override object GetPrimaryKey(VerifiedEvmWallet row) => row.Identity;
        }

        public readonly VerifiedEvmWalletHandle VerifiedEvmWallet;
    }

    public sealed class VerifiedEvmWalletCols
    {
        public global::SpacetimeDB.Col<VerifiedEvmWallet, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<VerifiedEvmWallet, string> EvmAddress { get; }
        public global::SpacetimeDB.Col<VerifiedEvmWallet, string> ProofHash { get; }
        public global::SpacetimeDB.Col<VerifiedEvmWallet, SpacetimeDB.Timestamp> VerifiedAt { get; }

        public VerifiedEvmWalletCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<VerifiedEvmWallet, SpacetimeDB.Identity>(tableName, "identity");
            EvmAddress = new global::SpacetimeDB.Col<VerifiedEvmWallet, string>(tableName, "evm_address");
            ProofHash = new global::SpacetimeDB.Col<VerifiedEvmWallet, string>(tableName, "proof_hash");
            VerifiedAt = new global::SpacetimeDB.Col<VerifiedEvmWallet, SpacetimeDB.Timestamp>(tableName, "verified_at");
        }
    }

    public sealed class VerifiedEvmWalletIxCols
    {
        public global::SpacetimeDB.IxCol<VerifiedEvmWallet, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<VerifiedEvmWallet, string> EvmAddress { get; }

        public VerifiedEvmWalletIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<VerifiedEvmWallet, SpacetimeDB.Identity>(tableName, "identity");
            EvmAddress = new global::SpacetimeDB.IxCol<VerifiedEvmWallet, string>(tableName, "evm_address");
        }
    }
}
