// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class VerifiedSolanaWalletHandle : RemoteTableHandle<EventContext, VerifiedSolanaWallet>
        {
            protected override string RemoteTableName => "verified_solana_wallet";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(VerifiedSolanaWallet row) => row.Identity;

                public IdentityUniqueIndex(VerifiedSolanaWalletHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class SolanaPubkeyUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(VerifiedSolanaWallet row) => row.SolanaPubkey;

                public SolanaPubkeyUniqueIndex(VerifiedSolanaWalletHandle table) : base(table) { }
            }

            public readonly SolanaPubkeyUniqueIndex SolanaPubkey;

            internal VerifiedSolanaWalletHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                SolanaPubkey = new(this);
            }

            protected override object GetPrimaryKey(VerifiedSolanaWallet row) => row.Identity;
        }

        public readonly VerifiedSolanaWalletHandle VerifiedSolanaWallet;
    }

    public sealed class VerifiedSolanaWalletCols
    {
        public global::SpacetimeDB.Col<VerifiedSolanaWallet, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<VerifiedSolanaWallet, string> SolanaPubkey { get; }
        public global::SpacetimeDB.Col<VerifiedSolanaWallet, string> ProofHash { get; }
        public global::SpacetimeDB.Col<VerifiedSolanaWallet, SpacetimeDB.Timestamp> VerifiedAt { get; }

        public VerifiedSolanaWalletCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<VerifiedSolanaWallet, SpacetimeDB.Identity>(tableName, "identity");
            SolanaPubkey = new global::SpacetimeDB.Col<VerifiedSolanaWallet, string>(tableName, "solana_pubkey");
            ProofHash = new global::SpacetimeDB.Col<VerifiedSolanaWallet, string>(tableName, "proof_hash");
            VerifiedAt = new global::SpacetimeDB.Col<VerifiedSolanaWallet, SpacetimeDB.Timestamp>(tableName, "verified_at");
        }
    }

    public sealed class VerifiedSolanaWalletIxCols
    {
        public global::SpacetimeDB.IxCol<VerifiedSolanaWallet, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<VerifiedSolanaWallet, string> SolanaPubkey { get; }

        public VerifiedSolanaWalletIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<VerifiedSolanaWallet, SpacetimeDB.Identity>(tableName, "identity");
            SolanaPubkey = new global::SpacetimeDB.IxCol<VerifiedSolanaWallet, string>(tableName, "solana_pubkey");
        }
    }
}
