// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WordDuelHandle : RemoteTableHandle<EventContext, WordDuel>
        {
            protected override string RemoteTableName => "word_duel";

            public sealed class DuelIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(WordDuel row) => row.DuelId;

                public DuelIdUniqueIndex(WordDuelHandle table) : base(table) { }
            }

            public readonly DuelIdUniqueIndex DuelId;

            public sealed class PlayerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(WordDuel row) => row.Player;

                public PlayerIndex(WordDuelHandle table) : base(table) { }
            }

            public readonly PlayerIndex Player;

            internal WordDuelHandle(DbConnection conn) : base(conn)
            {
                DuelId = new(this);
                Player = new(this);
            }

            protected override object GetPrimaryKey(WordDuel row) => row.DuelId;
        }

        public readonly WordDuelHandle WordDuel;
    }

    public sealed class WordDuelCols
    {
        public global::SpacetimeDB.Col<WordDuel, ulong> DuelId { get; }
        public global::SpacetimeDB.Col<WordDuel, SpacetimeDB.Identity> Player { get; }
        public global::SpacetimeDB.Col<WordDuel, Planet> Opponent { get; }
        public global::SpacetimeDB.Col<WordDuel, string> PlayerWord { get; }
        public global::SpacetimeDB.Col<WordDuel, uint> PlayerScore { get; }
        public global::SpacetimeDB.Col<WordDuel, string> AgentWord { get; }
        public global::SpacetimeDB.Col<WordDuel, uint> AgentScore { get; }
        public global::SpacetimeDB.Col<WordDuel, bool> Won { get; }
        public global::SpacetimeDB.Col<WordDuel, ulong> TokensAwarded { get; }
        public global::SpacetimeDB.Col<WordDuel, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<WordDuel, string> AgentRationale { get; }

        public WordDuelCols(string tableName)
        {
            DuelId = new global::SpacetimeDB.Col<WordDuel, ulong>(tableName, "duel_id");
            Player = new global::SpacetimeDB.Col<WordDuel, SpacetimeDB.Identity>(tableName, "player");
            Opponent = new global::SpacetimeDB.Col<WordDuel, Planet>(tableName, "opponent");
            PlayerWord = new global::SpacetimeDB.Col<WordDuel, string>(tableName, "player_word");
            PlayerScore = new global::SpacetimeDB.Col<WordDuel, uint>(tableName, "player_score");
            AgentWord = new global::SpacetimeDB.Col<WordDuel, string>(tableName, "agent_word");
            AgentScore = new global::SpacetimeDB.Col<WordDuel, uint>(tableName, "agent_score");
            Won = new global::SpacetimeDB.Col<WordDuel, bool>(tableName, "won");
            TokensAwarded = new global::SpacetimeDB.Col<WordDuel, ulong>(tableName, "tokens_awarded");
            CreatedAt = new global::SpacetimeDB.Col<WordDuel, SpacetimeDB.Timestamp>(tableName, "created_at");
            AgentRationale = new global::SpacetimeDB.Col<WordDuel, string>(tableName, "agent_rationale");
        }
    }

    public sealed class WordDuelIxCols
    {
        public global::SpacetimeDB.IxCol<WordDuel, ulong> DuelId { get; }
        public global::SpacetimeDB.IxCol<WordDuel, SpacetimeDB.Identity> Player { get; }

        public WordDuelIxCols(string tableName)
        {
            DuelId = new global::SpacetimeDB.IxCol<WordDuel, ulong>(tableName, "duel_id");
            Player = new global::SpacetimeDB.IxCol<WordDuel, SpacetimeDB.Identity>(tableName, "player");
        }
    }
}
