// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ZoneHandle : RemoteTableHandle<EventContext, Zone>
        {
            protected override string RemoteTableName => "zone";

            public sealed class ZoneIdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(Zone row) => row.ZoneId;

                public ZoneIdUniqueIndex(ZoneHandle table) : base(table) { }
            }

            public readonly ZoneIdUniqueIndex ZoneId;

            internal ZoneHandle(DbConnection conn) : base(conn)
            {
                ZoneId = new(this);
            }

            protected override object GetPrimaryKey(Zone row) => row.ZoneId;
        }

        public readonly ZoneHandle Zone;
    }

    public sealed class ZoneCols
    {
        public global::SpacetimeDB.Col<Zone, byte> ZoneId { get; }
        public global::SpacetimeDB.Col<Zone, ZoneKind> Kind { get; }
        public global::SpacetimeDB.Col<Zone, Planet> Owner { get; }
        public global::SpacetimeDB.Col<Zone, int> Control { get; }
        public global::SpacetimeDB.Col<Zone, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public ZoneCols(string tableName)
        {
            ZoneId = new global::SpacetimeDB.Col<Zone, byte>(tableName, "zone_id");
            Kind = new global::SpacetimeDB.Col<Zone, ZoneKind>(tableName, "kind");
            Owner = new global::SpacetimeDB.Col<Zone, Planet>(tableName, "owner");
            Control = new global::SpacetimeDB.Col<Zone, int>(tableName, "control");
            UpdatedAt = new global::SpacetimeDB.Col<Zone, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class ZoneIxCols
    {
        public global::SpacetimeDB.IxCol<Zone, byte> ZoneId { get; }

        public ZoneIxCols(string tableName)
        {
            ZoneId = new global::SpacetimeDB.IxCol<Zone, byte>(tableName, "zone_id");
        }
    }
}
