// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Battle
    {
        [DataMember(Name = "battle_id")]
        public ulong BattleId;
        [DataMember(Name = "star_id")]
        public uint StarId;
        [DataMember(Name = "attacker")]
        public SpacetimeDB.Identity Attacker;
        [DataMember(Name = "won")]
        public bool Won;
        [DataMember(Name = "attacker_score")]
        public uint AttackerScore;
        [DataMember(Name = "defense_rating")]
        public uint DefenseRating;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public Battle(
            ulong BattleId,
            uint StarId,
            SpacetimeDB.Identity Attacker,
            bool Won,
            uint AttackerScore,
            uint DefenseRating,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.BattleId = BattleId;
            this.StarId = StarId;
            this.Attacker = Attacker;
            this.Won = Won;
            this.AttackerScore = AttackerScore;
            this.DefenseRating = DefenseRating;
            this.CreatedAt = CreatedAt;
        }

        public Battle()
        {
        }
    }
}
