// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BattleLog
    {
        [DataMember(Name = "model")]
        public CombatModel Model;
        [DataMember(Name = "plays")]
        public System.Collections.Generic.List<ulong> Plays;

        public BattleLog(
            CombatModel Model,
            System.Collections.Generic.List<ulong> Plays
        )
        {
            this.Model = Model;
            this.Plays = Plays;
        }

        public BattleLog()
        {
            this.Plays = new();
        }
    }
}
