// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BridgeTransfer
    {
        [DataMember(Name = "burn_tx_hash")]
        public string BurnTxHash;
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "source_chain")]
        public BridgeChain SourceChain;
        [DataMember(Name = "target_chain")]
        public BridgeChain TargetChain;
        [DataMember(Name = "source_address")]
        public string SourceAddress;
        [DataMember(Name = "target_address")]
        public string TargetAddress;
        [DataMember(Name = "element_id")]
        public byte ElementId;
        [DataMember(Name = "amount")]
        public U128 Amount;
        [DataMember(Name = "status")]
        public BridgeStatus Status;
        [DataMember(Name = "destination_tx_hash")]
        public string? DestinationTxHash;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public BridgeTransfer(
            string BurnTxHash,
            SpacetimeDB.Identity Player,
            BridgeChain SourceChain,
            BridgeChain TargetChain,
            string SourceAddress,
            string TargetAddress,
            byte ElementId,
            U128 Amount,
            BridgeStatus Status,
            string? DestinationTxHash,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.BurnTxHash = BurnTxHash;
            this.Player = Player;
            this.SourceChain = SourceChain;
            this.TargetChain = TargetChain;
            this.SourceAddress = SourceAddress;
            this.TargetAddress = TargetAddress;
            this.ElementId = ElementId;
            this.Amount = Amount;
            this.Status = Status;
            this.DestinationTxHash = DestinationTxHash;
            this.CreatedAt = CreatedAt;
            this.UpdatedAt = UpdatedAt;
        }

        public BridgeTransfer()
        {
            this.BurnTxHash = "";
            this.SourceAddress = "";
            this.TargetAddress = "";
        }
    }
}
