// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Card
    {
        [DataMember(Name = "card_id")]
        public ulong CardId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "suit")]
        public Suit Suit;
        [DataMember(Name = "rank")]
        public byte Rank;
        [DataMember(Name = "health")]
        public ushort Health;
        [DataMember(Name = "attack")]
        public ushort Attack;
        [DataMember(Name = "armour")]
        public ushort Armour;
        [DataMember(Name = "cooldown_ms")]
        public ushort CooldownMs;
        [DataMember(Name = "source_body")]
        public Planet SourceBody;
        [DataMember(Name = "inverted")]
        public bool Inverted;
        [DataMember(Name = "is_trump")]
        public bool IsTrump;
        [DataMember(Name = "level")]
        public byte Level;
        [DataMember(Name = "minted_at")]
        public SpacetimeDB.Timestamp MintedAt;
        [DataMember(Name = "letter")]
        public byte Letter;

        public Card(
            ulong CardId,
            SpacetimeDB.Identity Owner,
            Suit Suit,
            byte Rank,
            ushort Health,
            ushort Attack,
            ushort Armour,
            ushort CooldownMs,
            Planet SourceBody,
            bool Inverted,
            bool IsTrump,
            byte Level,
            SpacetimeDB.Timestamp MintedAt,
            byte Letter
        )
        {
            this.CardId = CardId;
            this.Owner = Owner;
            this.Suit = Suit;
            this.Rank = Rank;
            this.Health = Health;
            this.Attack = Attack;
            this.Armour = Armour;
            this.CooldownMs = CooldownMs;
            this.SourceBody = SourceBody;
            this.Inverted = Inverted;
            this.IsTrump = IsTrump;
            this.Level = Level;
            this.MintedAt = MintedAt;
            this.Letter = Letter;
        }

        public Card()
        {
        }
    }
}
