// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClaimGrant
    {
        [DataMember(Name = "code_hash")]
        public string CodeHash;
        [DataMember(Name = "old_identity")]
        public SpacetimeDB.Identity OldIdentity;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "expires_at")]
        public SpacetimeDB.Timestamp ExpiresAt;

        public ClaimGrant(
            string CodeHash,
            SpacetimeDB.Identity OldIdentity,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp ExpiresAt
        )
        {
            this.CodeHash = CodeHash;
            this.OldIdentity = OldIdentity;
            this.CreatedAt = CreatedAt;
            this.ExpiresAt = ExpiresAt;
        }

        public ClaimGrant()
        {
            this.CodeHash = "";
        }
    }
}
