// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Comet
    {
        [DataMember(Name = "comet_id")]
        public ushort CometId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "designation")]
        public string Designation;
        [DataMember(Name = "element")]
        public byte Element;
        [DataMember(Name = "composition")]
        public System.Collections.Generic.List<ushort> Composition;
        [DataMember(Name = "specialty")]
        public string Specialty;
        [DataMember(Name = "semi_major_au")]
        public double SemiMajorAu;
        [DataMember(Name = "eccentricity")]
        public double Eccentricity;
        [DataMember(Name = "inclination_deg")]
        public double InclinationDeg;
        [DataMember(Name = "mean_long_deg")]
        public double MeanLongDeg;
        [DataMember(Name = "long_peri_deg")]
        public double LongPeriDeg;
        [DataMember(Name = "long_node_deg")]
        public double LongNodeDeg;
        [DataMember(Name = "mean_long_rate")]
        public double MeanLongRate;
        [DataMember(Name = "active")]
        public bool Active;

        public Comet(
            ushort CometId,
            string Name,
            string Designation,
            byte Element,
            System.Collections.Generic.List<ushort> Composition,
            string Specialty,
            double SemiMajorAu,
            double Eccentricity,
            double InclinationDeg,
            double MeanLongDeg,
            double LongPeriDeg,
            double LongNodeDeg,
            double MeanLongRate,
            bool Active
        )
        {
            this.CometId = CometId;
            this.Name = Name;
            this.Designation = Designation;
            this.Element = Element;
            this.Composition = Composition;
            this.Specialty = Specialty;
            this.SemiMajorAu = SemiMajorAu;
            this.Eccentricity = Eccentricity;
            this.InclinationDeg = InclinationDeg;
            this.MeanLongDeg = MeanLongDeg;
            this.LongPeriDeg = LongPeriDeg;
            this.LongNodeDeg = LongNodeDeg;
            this.MeanLongRate = MeanLongRate;
            this.Active = Active;
        }

        public Comet()
        {
            this.Name = "";
            this.Designation = "";
            this.Composition = new();
            this.Specialty = "";
        }
    }
}
