// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstellationBlock
    {
        [DataMember(Name = "block_id")]
        public ulong BlockId;
        [DataMember(Name = "constellation_id")]
        public ushort ConstellationId;
        [DataMember(Name = "minter")]
        public SpacetimeDB.Identity Minter;
        [DataMember(Name = "hip_id")]
        public uint HipId;
        [DataMember(Name = "level_after")]
        public ushort LevelAfter;
        [DataMember(Name = "onchain_block")]
        public ulong? OnchainBlock;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public ConstellationBlock(
            ulong BlockId,
            ushort ConstellationId,
            SpacetimeDB.Identity Minter,
            uint HipId,
            ushort LevelAfter,
            ulong? OnchainBlock,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.BlockId = BlockId;
            this.ConstellationId = ConstellationId;
            this.Minter = Minter;
            this.HipId = HipId;
            this.LevelAfter = LevelAfter;
            this.OnchainBlock = OnchainBlock;
            this.CreatedAt = CreatedAt;
        }

        public ConstellationBlock()
        {
        }
    }
}
