// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstellationResolution
    {
        [DataMember(Name = "constellation_id")]
        public ushort ConstellationId;
        [DataMember(Name = "baseline_members")]
        public ushort BaselineMembers;
        [DataMember(Name = "added_members")]
        public ushort AddedMembers;
        [DataMember(Name = "resolution_level")]
        public ushort ResolutionLevel;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public ConstellationResolution(
            ushort ConstellationId,
            ushort BaselineMembers,
            ushort AddedMembers,
            ushort ResolutionLevel,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.ConstellationId = ConstellationId;
            this.BaselineMembers = BaselineMembers;
            this.AddedMembers = AddedMembers;
            this.ResolutionLevel = ResolutionLevel;
            this.UpdatedAt = UpdatedAt;
        }

        public ConstellationResolution()
        {
        }
    }
}
