// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstellationStar
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "constellation_id")]
        public ushort ConstellationId;
        [DataMember(Name = "hip_id")]
        public uint HipId;

        public ConstellationStar(
            ulong Id,
            ushort ConstellationId,
            uint HipId
        )
        {
            this.Id = Id;
            this.ConstellationId = ConstellationId;
            this.HipId = HipId;
        }

        public ConstellationStar()
        {
        }
    }
}
