// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConstellationLine
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "constellation_id")]
        public ushort ConstellationId;
        [DataMember(Name = "hip_a")]
        public uint HipA;
        [DataMember(Name = "hip_b")]
        public uint HipB;

        public ConstellationLine(
            ulong Id,
            ushort ConstellationId,
            uint HipA,
            uint HipB
        )
        {
            this.Id = Id;
            this.ConstellationId = ConstellationId;
            this.HipA = HipA;
            this.HipB = HipB;
        }

        public ConstellationLine()
        {
        }
    }
}
