// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Constellation
    {
        [DataMember(Name = "constellation_id")]
        public ushort ConstellationId;
        [DataMember(Name = "abbr")]
        public string Abbr;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "elem_a")]
        public byte ElemA;
        [DataMember(Name = "elem_b")]
        public byte ElemB;
        [DataMember(Name = "degenerate")]
        public bool Degenerate;
        [DataMember(Name = "fee_bps")]
        public ushort FeeBps;
        [DataMember(Name = "member_count")]
        public ushort MemberCount;
        [DataMember(Name = "visible_threshold")]
        public ushort VisibleThreshold;

        public Constellation(
            ushort ConstellationId,
            string Abbr,
            string Name,
            byte ElemA,
            byte ElemB,
            bool Degenerate,
            ushort FeeBps,
            ushort MemberCount,
            ushort VisibleThreshold
        )
        {
            this.ConstellationId = ConstellationId;
            this.Abbr = Abbr;
            this.Name = Name;
            this.ElemA = ElemA;
            this.ElemB = ElemB;
            this.Degenerate = Degenerate;
            this.FeeBps = FeeBps;
            this.MemberCount = MemberCount;
            this.VisibleThreshold = VisibleThreshold;
        }

        public Constellation()
        {
            this.Abbr = "";
            this.Name = "";
        }
    }
}
