// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DeckSlot
    {
        [DataMember(Name = "slot_id")]
        public ulong SlotId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "card_id")]
        public ulong CardId;
        [DataMember(Name = "loadout")]
        public Loadout Loadout;

        public DeckSlot(
            ulong SlotId,
            SpacetimeDB.Identity Owner,
            ulong CardId,
            Loadout Loadout
        )
        {
            this.SlotId = SlotId;
            this.Owner = Owner;
            this.CardId = CardId;
            this.Loadout = Loadout;
        }

        public DeckSlot()
        {
        }
    }
}
