// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DuelQueue
    {
        [DataMember(Name = "ticket_id")]
        public ulong TicketId;
        [DataMember(Name = "zone_id")]
        public byte ZoneId;
        [DataMember(Name = "seeker")]
        public SpacetimeDB.Identity Seeker;
        [DataMember(Name = "enqueued_at")]
        public SpacetimeDB.Timestamp EnqueuedAt;

        public DuelQueue(
            ulong TicketId,
            byte ZoneId,
            SpacetimeDB.Identity Seeker,
            SpacetimeDB.Timestamp EnqueuedAt
        )
        {
            this.TicketId = TicketId;
            this.ZoneId = ZoneId;
            this.Seeker = Seeker;
            this.EnqueuedAt = EnqueuedAt;
        }

        public DuelQueue()
        {
        }
    }
}
