// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Duel
    {
        [DataMember(Name = "duel_id")]
        public ulong DuelId;
        [DataMember(Name = "zone_id")]
        public byte ZoneId;
        [DataMember(Name = "player_a")]
        public SpacetimeDB.Identity PlayerA;
        [DataMember(Name = "player_b")]
        public SpacetimeDB.Identity PlayerB;
        [DataMember(Name = "faction_a")]
        public Planet FactionA;
        [DataMember(Name = "faction_b")]
        public Planet FactionB;
        [DataMember(Name = "a_cards")]
        public System.Collections.Generic.List<ulong> ACards;
        [DataMember(Name = "b_cards")]
        public System.Collections.Generic.List<ulong> BCards;
        [DataMember(Name = "a_committed")]
        public bool ACommitted;
        [DataMember(Name = "b_committed")]
        public bool BCommitted;
        [DataMember(Name = "state")]
        public DuelState State;
        [DataMember(Name = "lanes_a")]
        public byte LanesA;
        [DataMember(Name = "lanes_b")]
        public byte LanesB;
        [DataMember(Name = "winner")]
        public SpacetimeDB.Identity? Winner;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public Duel(
            ulong DuelId,
            byte ZoneId,
            SpacetimeDB.Identity PlayerA,
            SpacetimeDB.Identity PlayerB,
            Planet FactionA,
            Planet FactionB,
            System.Collections.Generic.List<ulong> ACards,
            System.Collections.Generic.List<ulong> BCards,
            bool ACommitted,
            bool BCommitted,
            DuelState State,
            byte LanesA,
            byte LanesB,
            SpacetimeDB.Identity? Winner,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.DuelId = DuelId;
            this.ZoneId = ZoneId;
            this.PlayerA = PlayerA;
            this.PlayerB = PlayerB;
            this.FactionA = FactionA;
            this.FactionB = FactionB;
            this.ACards = ACards;
            this.BCards = BCards;
            this.ACommitted = ACommitted;
            this.BCommitted = BCommitted;
            this.State = State;
            this.LanesA = LanesA;
            this.LanesB = LanesB;
            this.Winner = Winner;
            this.CreatedAt = CreatedAt;
            this.UpdatedAt = UpdatedAt;
        }

        public Duel()
        {
            this.ACards = new();
            this.BCards = new();
        }
    }
}
