// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DuelRound
    {
        [DataMember(Name = "round_id")]
        public ulong RoundId;
        [DataMember(Name = "plays_count")]
        public uint PlaysCount;
        [DataMember(Name = "target_plays")]
        public uint TargetPlays;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public DuelRound(
            ulong RoundId,
            uint PlaysCount,
            uint TargetPlays,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.RoundId = RoundId;
            this.PlaysCount = PlaysCount;
            this.TargetPlays = TargetPlays;
            this.CreatedAt = CreatedAt;
        }

        public DuelRound()
        {
        }
    }
}
