// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DuelChallenge
    {
        [DataMember(Name = "challenge_id")]
        public ulong ChallengeId;
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "opponent")]
        public Planet Opponent;
        [DataMember(Name = "player_word")]
        public string PlayerWord;
        [DataMember(Name = "player_score")]
        public uint PlayerScore;
        [DataMember(Name = "agent_rack")]
        public string AgentRack;
        [DataMember(Name = "candidates")]
        public string Candidates;
        [DataMember(Name = "answered")]
        public bool Answered;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public DuelChallenge(
            ulong ChallengeId,
            SpacetimeDB.Identity Player,
            Planet Opponent,
            string PlayerWord,
            uint PlayerScore,
            string AgentRack,
            string Candidates,
            bool Answered,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.ChallengeId = ChallengeId;
            this.Player = Player;
            this.Opponent = Opponent;
            this.PlayerWord = PlayerWord;
            this.PlayerScore = PlayerScore;
            this.AgentRack = AgentRack;
            this.Candidates = Candidates;
            this.Answered = Answered;
            this.CreatedAt = CreatedAt;
        }

        public DuelChallenge()
        {
            this.PlayerWord = "";
            this.AgentRack = "";
            this.Candidates = "";
        }
    }
}
