// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Ephemeris
    {
        [DataMember(Name = "body")]
        public Planet Body;
        [DataMember(Name = "ra")]
        public double Ra;
        [DataMember(Name = "dec")]
        public double Dec;
        [DataMember(Name = "transiting_zone")]
        public byte TransitingZone;
        [DataMember(Name = "tick")]
        public SpacetimeDB.Timestamp Tick;
        [DataMember(Name = "retrograde")]
        public bool Retrograde;

        public Ephemeris(
            Planet Body,
            double Ra,
            double Dec,
            byte TransitingZone,
            SpacetimeDB.Timestamp Tick,
            bool Retrograde
        )
        {
            this.Body = Body;
            this.Ra = Ra;
            this.Dec = Dec;
            this.TransitingZone = TransitingZone;
            this.Tick = Tick;
            this.Retrograde = Retrograde;
        }

        public Ephemeris()
        {
        }
    }
}
