// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameConfig
    {
        [DataMember(Name = "id")]
        public byte Id;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "season_degree")]
        public ushort SeasonDegree;
        [DataMember(Name = "ascendant_degree")]
        public ushort AscendantDegree;
        [DataMember(Name = "seeded")]
        public bool Seeded;

        public GameConfig(
            byte Id,
            SpacetimeDB.Identity Owner,
            ushort SeasonDegree,
            ushort AscendantDegree,
            bool Seeded
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.SeasonDegree = SeasonDegree;
            this.AscendantDegree = AscendantDegree;
            this.Seeded = Seeded;
        }

        public GameConfig()
        {
        }
    }
}
