// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HorizonActionReceipt
    {
        [DataMember(Name = "action_key")]
        public string ActionKey;
        [DataMember(Name = "intent_id")]
        public ulong IntentId;
        [DataMember(Name = "tx_hash")]
        public string TxHash;
        [DataMember(Name = "processed_at")]
        public SpacetimeDB.Timestamp ProcessedAt;

        public HorizonActionReceipt(
            string ActionKey,
            ulong IntentId,
            string TxHash,
            SpacetimeDB.Timestamp ProcessedAt
        )
        {
            this.ActionKey = ActionKey;
            this.IntentId = IntentId;
            this.TxHash = TxHash;
            this.ProcessedAt = ProcessedAt;
        }

        public HorizonActionReceipt()
        {
            this.ActionKey = "";
            this.TxHash = "";
        }
    }
}
