// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class JingCast
    {
        [DataMember(Name = "cast_id")]
        public ulong CastId;
        [DataMember(Name = "duel_id")]
        public ulong DuelId;
        [DataMember(Name = "caster")]
        public SpacetimeDB.Identity Caster;
        [DataMember(Name = "caster_agent")]
        public Planet? CasterAgent;
        [DataMember(Name = "mv")]
        public JingMove Mv;
        [DataMember(Name = "cost_sacred7")]
        public byte CostSacred7;
        [DataMember(Name = "cost_esms")]
        public byte CostEsms;
        [DataMember(Name = "deflects")]
        public JingMove? Deflects;
        [DataMember(Name = "voice")]
        public string Voice;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public JingCast(
            ulong CastId,
            ulong DuelId,
            SpacetimeDB.Identity Caster,
            Planet? CasterAgent,
            JingMove Mv,
            byte CostSacred7,
            byte CostEsms,
            JingMove? Deflects,
            string Voice,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.CastId = CastId;
            this.DuelId = DuelId;
            this.Caster = Caster;
            this.CasterAgent = CasterAgent;
            this.Mv = Mv;
            this.CostSacred7 = CostSacred7;
            this.CostEsms = CostEsms;
            this.Deflects = Deflects;
            this.Voice = Voice;
            this.CreatedAt = CreatedAt;
        }

        public JingCast()
        {
            this.Voice = "";
        }
    }
}
