// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class JingPool
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "sacred7")]
        public System.Collections.Generic.List<ushort> Sacred7;
        [DataMember(Name = "esms")]
        public System.Collections.Generic.List<ushort> Esms;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public JingPool(
            SpacetimeDB.Identity Identity,
            System.Collections.Generic.List<ushort> Sacred7,
            System.Collections.Generic.List<ushort> Esms,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.Identity = Identity;
            this.Sacred7 = Sacred7;
            this.Esms = Esms;
            this.UpdatedAt = UpdatedAt;
        }

        public JingPool()
        {
            this.Sacred7 = new();
            this.Esms = new();
        }
    }
}
