// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class JingDuel
    {
        [DataMember(Name = "duel_id")]
        public ulong DuelId;
        [DataMember(Name = "initiator")]
        public SpacetimeDB.Identity Initiator;
        [DataMember(Name = "target_player")]
        public SpacetimeDB.Identity? TargetPlayer;
        [DataMember(Name = "target_agent")]
        public Planet? TargetAgent;
        [DataMember(Name = "opening_move")]
        public JingMove OpeningMove;
        [DataMember(Name = "state")]
        public JingState State;
        [DataMember(Name = "winner_is_initiator")]
        public bool? WinnerIsInitiator;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public JingDuel(
            ulong DuelId,
            SpacetimeDB.Identity Initiator,
            SpacetimeDB.Identity? TargetPlayer,
            Planet? TargetAgent,
            JingMove OpeningMove,
            JingState State,
            bool? WinnerIsInitiator,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.DuelId = DuelId;
            this.Initiator = Initiator;
            this.TargetPlayer = TargetPlayer;
            this.TargetAgent = TargetAgent;
            this.OpeningMove = OpeningMove;
            this.State = State;
            this.WinnerIsInitiator = WinnerIsInitiator;
            this.CreatedAt = CreatedAt;
            this.UpdatedAt = UpdatedAt;
        }

        public JingDuel()
        {
        }
    }
}
