// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NatalChart
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "birth_unix")]
        public long BirthUnix;
        [DataMember(Name = "birth_lat")]
        public double BirthLat;
        [DataMember(Name = "birth_lon")]
        public double BirthLon;
        [DataMember(Name = "time_known")]
        public bool TimeKnown;
        [DataMember(Name = "placements")]
        public System.Collections.Generic.List<Placement> Placements;
        [DataMember(Name = "ascendant")]
        public ushort Ascendant;
        [DataMember(Name = "midheaven")]
        public ushort Midheaven;

        public NatalChart(
            SpacetimeDB.Identity Identity,
            long BirthUnix,
            double BirthLat,
            double BirthLon,
            bool TimeKnown,
            System.Collections.Generic.List<Placement> Placements,
            ushort Ascendant,
            ushort Midheaven
        )
        {
            this.Identity = Identity;
            this.BirthUnix = BirthUnix;
            this.BirthLat = BirthLat;
            this.BirthLon = BirthLon;
            this.TimeKnown = TimeKnown;
            this.Placements = Placements;
            this.Ascendant = Ascendant;
            this.Midheaven = Midheaven;
        }

        public NatalChart()
        {
            this.Placements = new();
        }
    }
}
