// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NatalDecan
    {
        [DataMember(Name = "decan_id")]
        public ulong DecanId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "body")]
        public Planet Body;
        [DataMember(Name = "sign")]
        public byte Sign;
        [DataMember(Name = "decan")]
        public byte Decan;
        [DataMember(Name = "abs_decan")]
        public byte AbsDecan;
        [DataMember(Name = "suit")]
        public Suit Suit;
        [DataMember(Name = "rank")]
        public byte Rank;
        [DataMember(Name = "decan_ruler")]
        public Planet DecanRuler;
        [DataMember(Name = "retrograde")]
        public bool Retrograde;

        public NatalDecan(
            ulong DecanId,
            SpacetimeDB.Identity Owner,
            Planet Body,
            byte Sign,
            byte Decan,
            byte AbsDecan,
            Suit Suit,
            byte Rank,
            Planet DecanRuler,
            bool Retrograde
        )
        {
            this.DecanId = DecanId;
            this.Owner = Owner;
            this.Body = Body;
            this.Sign = Sign;
            this.Decan = Decan;
            this.AbsDecan = AbsDecan;
            this.Suit = Suit;
            this.Rank = Rank;
            this.DecanRuler = DecanRuler;
            this.Retrograde = Retrograde;
        }

        public NatalDecan()
        {
        }
    }
}
