// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OracleReply
    {
        [DataMember(Name = "request_id")]
        public ulong RequestId;
        [DataMember(Name = "asker")]
        public SpacetimeDB.Identity Asker;
        [DataMember(Name = "text")]
        public string Text;
        [DataMember(Name = "model")]
        public string Model;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public OracleReply(
            ulong RequestId,
            SpacetimeDB.Identity Asker,
            string Text,
            string Model,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.RequestId = RequestId;
            this.Asker = Asker;
            this.Text = Text;
            this.Model = Model;
            this.CreatedAt = CreatedAt;
        }

        public OracleReply()
        {
            this.Text = "";
            this.Model = "";
        }
    }
}
