// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OracleRate
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "last_at")]
        public SpacetimeDB.Timestamp LastAt;
        [DataMember(Name = "count")]
        public uint Count;

        public OracleRate(
            SpacetimeDB.Identity Identity,
            SpacetimeDB.Timestamp LastAt,
            uint Count
        )
        {
            this.Identity = Identity;
            this.LastAt = LastAt;
            this.Count = Count;
        }

        public OracleRate()
        {
        }
    }
}
