// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OracleCache
    {
        [DataMember(Name = "qhash")]
        public ulong Qhash;
        [DataMember(Name = "question")]
        public string Question;
        [DataMember(Name = "text")]
        public string Text;
        [DataMember(Name = "model")]
        public string Model;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public OracleCache(
            ulong Qhash,
            string Question,
            string Text,
            string Model,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Qhash = Qhash;
            this.Question = Question;
            this.Text = Text;
            this.Model = Model;
            this.CreatedAt = CreatedAt;
        }

        public OracleCache()
        {
            this.Question = "";
            this.Text = "";
            this.Model = "";
        }
    }
}
