// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class OracleRequest
    {
        [DataMember(Name = "request_id")]
        public ulong RequestId;
        [DataMember(Name = "asker")]
        public SpacetimeDB.Identity Asker;
        [DataMember(Name = "question")]
        public string Question;
        [DataMember(Name = "context")]
        public string Context;
        [DataMember(Name = "cacheable")]
        public bool Cacheable;
        [DataMember(Name = "qhash")]
        public ulong Qhash;
        [DataMember(Name = "answered")]
        public bool Answered;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public OracleRequest(
            ulong RequestId,
            SpacetimeDB.Identity Asker,
            string Question,
            string Context,
            bool Cacheable,
            ulong Qhash,
            bool Answered,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.RequestId = RequestId;
            this.Asker = Asker;
            this.Question = Question;
            this.Context = Context;
            this.Cacheable = Cacheable;
            this.Qhash = Qhash;
            this.Answered = Answered;
            this.CreatedAt = CreatedAt;
        }

        public OracleRequest()
        {
            this.Question = "";
            this.Context = "";
        }
    }
}
