// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Placement
    {
        [DataMember(Name = "body")]
        public Planet Body;
        [DataMember(Name = "sign")]
        public byte Sign;
        [DataMember(Name = "arc_minutes")]
        public ushort ArcMinutes;
        [DataMember(Name = "retrograde")]
        public bool Retrograde;
        [DataMember(Name = "dignity")]
        public sbyte Dignity;

        public Placement(
            Planet Body,
            byte Sign,
            ushort ArcMinutes,
            bool Retrograde,
            sbyte Dignity
        )
        {
            this.Body = Body;
            this.Sign = Sign;
            this.ArcMinutes = ArcMinutes;
            this.Retrograde = Retrograde;
            this.Dignity = Dignity;
        }

        public Placement()
        {
        }
    }
}
