// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "handle")]
        public string Handle;
        [DataMember(Name = "faction")]
        public Planet Faction;
        [DataMember(Name = "deck_seed")]
        public ulong DeckSeed;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "last_active")]
        public SpacetimeDB.Timestamp LastActive;
        [DataMember(Name = "tokens")]
        public ulong Tokens;
        [DataMember(Name = "word_wins")]
        public uint WordWins;
        [DataMember(Name = "evm_address")]
        public string? EvmAddress;
        [DataMember(Name = "solana_pubkey")]
        public string? SolanaPubkey;

        public Player(
            SpacetimeDB.Identity Identity,
            string Handle,
            Planet Faction,
            ulong DeckSeed,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp LastActive,
            ulong Tokens,
            uint WordWins,
            string? EvmAddress,
            string? SolanaPubkey
        )
        {
            this.Identity = Identity;
            this.Handle = Handle;
            this.Faction = Faction;
            this.DeckSeed = DeckSeed;
            this.CreatedAt = CreatedAt;
            this.LastActive = LastActive;
            this.Tokens = Tokens;
            this.WordWins = WordWins;
            this.EvmAddress = EvmAddress;
            this.SolanaPubkey = SolanaPubkey;
        }

        public Player()
        {
            this.Handle = "";
        }
    }
}
