// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerLocation
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "lat")]
        public double Lat;
        [DataMember(Name = "lon")]
        public double Lon;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public PlayerLocation(
            SpacetimeDB.Identity Identity,
            double Lat,
            double Lon,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.Identity = Identity;
            this.Lat = Lat;
            this.Lon = Lon;
            this.UpdatedAt = UpdatedAt;
        }

        public PlayerLocation()
        {
        }
    }
}
