// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ProcessedTx
    {
        [DataMember(Name = "tx_hash")]
        public string TxHash;
        [DataMember(Name = "chain")]
        public string Chain;
        [DataMember(Name = "event_type")]
        public string EventType;
        [DataMember(Name = "processed_at")]
        public SpacetimeDB.Timestamp ProcessedAt;

        public ProcessedTx(
            string TxHash,
            string Chain,
            string EventType,
            SpacetimeDB.Timestamp ProcessedAt
        )
        {
            this.TxHash = TxHash;
            this.Chain = Chain;
            this.EventType = EventType;
            this.ProcessedAt = ProcessedAt;
        }

        public ProcessedTx()
        {
            this.TxHash = "";
            this.Chain = "";
            this.EventType = "";
        }
    }
}
