// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoundTimer
    {
        [DataMember(Name = "scheduled_id")]
        public ulong ScheduledId;
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;

        public RoundTimer(
            ulong ScheduledId,
            SpacetimeDB.Identity Player,
            SpacetimeDB.ScheduleAt ScheduledAt
        )
        {
            this.ScheduledId = ScheduledId;
            this.Player = Player;
            this.ScheduledAt = ScheduledAt;
        }

        public RoundTimer()
        {
            this.ScheduledAt = null!;
        }
    }
}
