// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoundState
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "round_index")]
        public ulong RoundIndex;
        [DataMember(Name = "wins")]
        public uint Wins;
        [DataMember(Name = "fights")]
        public uint Fights;
        [DataMember(Name = "last_resolved_at")]
        public SpacetimeDB.Timestamp LastResolvedAt;

        public RoundState(
            SpacetimeDB.Identity Identity,
            ulong RoundIndex,
            uint Wins,
            uint Fights,
            SpacetimeDB.Timestamp LastResolvedAt
        )
        {
            this.Identity = Identity;
            this.RoundIndex = RoundIndex;
            this.Wins = Wins;
            this.Fights = Fights;
            this.LastResolvedAt = LastResolvedAt;
        }

        public RoundState()
        {
        }
    }
}
