// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RoundParticipant
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "round_id")]
        public ulong RoundId;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "element")]
        public byte Element;
        [DataMember(Name = "weight")]
        public uint Weight;

        public RoundParticipant(
            ulong Id,
            ulong RoundId,
            SpacetimeDB.Identity Identity,
            byte Element,
            uint Weight
        )
        {
            this.Id = Id;
            this.RoundId = RoundId;
            this.Identity = Identity;
            this.Element = Element;
            this.Weight = Weight;
        }

        public RoundParticipant()
        {
        }
    }
}
