// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ServiceStatus
    {
        [DataMember(Name = "service")]
        public string Service;
        [DataMember(Name = "healthy")]
        public bool Healthy;
        [DataMember(Name = "detail")]
        public string Detail;
        [DataMember(Name = "latency_ms")]
        public uint LatencyMs;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public ServiceStatus(
            string Service,
            bool Healthy,
            string Detail,
            uint LatencyMs,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.Service = Service;
            this.Healthy = Healthy;
            this.Detail = Detail;
            this.LatencyMs = LatencyMs;
            this.UpdatedAt = UpdatedAt;
        }

        public ServiceStatus()
        {
            this.Service = "";
            this.Detail = "";
        }
    }
}
