// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StarStake
    {
        [DataMember(Name = "stake_id")]
        public ulong StakeId;
        [DataMember(Name = "staker")]
        public SpacetimeDB.Identity Staker;
        [DataMember(Name = "star_id")]
        public uint StarId;
        [DataMember(Name = "element")]
        public byte Element;
        [DataMember(Name = "principal_usdc")]
        public ulong PrincipalUsdc;
        [DataMember(Name = "shares")]
        public U128 Shares;
        [DataMember(Name = "accrued_essence")]
        public U128 AccruedEssence;
        [DataMember(Name = "claimed_essence")]
        public U128 ClaimedEssence;
        [DataMember(Name = "pending_essence")]
        public U128 PendingEssence;
        [DataMember(Name = "claim_nonce")]
        public ulong ClaimNonce;
        [DataMember(Name = "staked_at")]
        public SpacetimeDB.Timestamp StakedAt;
        [DataMember(Name = "last_accrual_at")]
        public SpacetimeDB.Timestamp LastAccrualAt;

        public StarStake(
            ulong StakeId,
            SpacetimeDB.Identity Staker,
            uint StarId,
            byte Element,
            ulong PrincipalUsdc,
            U128 Shares,
            U128 AccruedEssence,
            U128 ClaimedEssence,
            U128 PendingEssence,
            ulong ClaimNonce,
            SpacetimeDB.Timestamp StakedAt,
            SpacetimeDB.Timestamp LastAccrualAt
        )
        {
            this.StakeId = StakeId;
            this.Staker = Staker;
            this.StarId = StarId;
            this.Element = Element;
            this.PrincipalUsdc = PrincipalUsdc;
            this.Shares = Shares;
            this.AccruedEssence = AccruedEssence;
            this.ClaimedEssence = ClaimedEssence;
            this.PendingEssence = PendingEssence;
            this.ClaimNonce = ClaimNonce;
            this.StakedAt = StakedAt;
            this.LastAccrualAt = LastAccrualAt;
        }

        public StarStake()
        {
        }
    }
}
