// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StarAgent
    {
        [DataMember(Name = "hip_id")]
        public uint HipId;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "element")]
        public byte Element;
        [DataMember(Name = "composition")]
        public System.Collections.Generic.List<ushort> Composition;
        [DataMember(Name = "specialty")]
        public string Specialty;
        [DataMember(Name = "active")]
        public bool Active;

        public StarAgent(
            uint HipId,
            string DisplayName,
            byte Element,
            System.Collections.Generic.List<ushort> Composition,
            string Specialty,
            bool Active
        )
        {
            this.HipId = HipId;
            this.DisplayName = DisplayName;
            this.Element = Element;
            this.Composition = Composition;
            this.Specialty = Specialty;
            this.Active = Active;
        }

        public StarAgent()
        {
            this.DisplayName = "";
            this.Composition = new();
            this.Specialty = "";
        }
    }
}
