// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StarStakePool
    {
        [DataMember(Name = "star_id")]
        public uint StarId;
        [DataMember(Name = "total_principal_usdc")]
        public ulong TotalPrincipalUsdc;
        [DataMember(Name = "total_shares")]
        public U128 TotalShares;

        public StarStakePool(
            uint StarId,
            ulong TotalPrincipalUsdc,
            U128 TotalShares
        )
        {
            this.StarId = StarId;
            this.TotalPrincipalUsdc = TotalPrincipalUsdc;
            this.TotalShares = TotalShares;
        }

        public StarStakePool()
        {
        }
    }
}
