// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StarNode
    {
        [DataMember(Name = "hip_id")]
        public uint HipId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "ra")]
        public double Ra;
        [DataMember(Name = "dec")]
        public double Dec;
        [DataMember(Name = "magnitude")]
        public float Magnitude;
        [DataMember(Name = "constellation")]
        public string Constellation;
        [DataMember(Name = "zodiac_sign")]
        public string ZodiacSign;
        [DataMember(Name = "ecliptic_deg")]
        public byte EclipticDeg;
        [DataMember(Name = "ecliptic_min")]
        public byte EclipticMin;
        [DataMember(Name = "ecliptic_sec")]
        public byte EclipticSec;
        [DataMember(Name = "refracted_alt")]
        public float RefractedAlt;
        [DataMember(Name = "azimuth")]
        public float Azimuth;
        [DataMember(Name = "horizon_state")]
        public string HorizonState;
        [DataMember(Name = "held_by")]
        public Planet? HeldBy;
        [DataMember(Name = "region_hint")]
        public byte RegionHint;

        public StarNode(
            uint HipId,
            string Name,
            double Ra,
            double Dec,
            float Magnitude,
            string Constellation,
            string ZodiacSign,
            byte EclipticDeg,
            byte EclipticMin,
            byte EclipticSec,
            float RefractedAlt,
            float Azimuth,
            string HorizonState,
            Planet? HeldBy,
            byte RegionHint
        )
        {
            this.HipId = HipId;
            this.Name = Name;
            this.Ra = Ra;
            this.Dec = Dec;
            this.Magnitude = Magnitude;
            this.Constellation = Constellation;
            this.ZodiacSign = ZodiacSign;
            this.EclipticDeg = EclipticDeg;
            this.EclipticMin = EclipticMin;
            this.EclipticSec = EclipticSec;
            this.RefractedAlt = RefractedAlt;
            this.Azimuth = Azimuth;
            this.HorizonState = HorizonState;
            this.HeldBy = HeldBy;
            this.RegionHint = RegionHint;
        }

        public StarNode()
        {
            this.Name = "";
            this.Constellation = "";
            this.ZodiacSign = "";
            this.HorizonState = "";
        }
    }
}
