// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StarNode
    {
        [DataMember(Name = "hip_id")]
        public uint HipId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "ra")]
        public double Ra;
        [DataMember(Name = "dec")]
        public double Dec;
        [DataMember(Name = "magnitude")]
        public float Magnitude;
        [DataMember(Name = "held_by")]
        public Planet? HeldBy;
        [DataMember(Name = "region_hint")]
        public byte RegionHint;

        public StarNode(
            uint HipId,
            string Name,
            double Ra,
            double Dec,
            float Magnitude,
            Planet? HeldBy,
            byte RegionHint
        )
        {
            this.HipId = HipId;
            this.Name = Name;
            this.Ra = Ra;
            this.Dec = Dec;
            this.Magnitude = Magnitude;
            this.HeldBy = HeldBy;
            this.RegionHint = RegionHint;
        }

        public StarNode()
        {
            this.Name = "";
        }
    }
}
