// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TraceAttestation
    {
        [DataMember(Name = "intent_id")]
        public ulong IntentId;
        [DataMember(Name = "trader")]
        public SpacetimeDB.Identity Trader;
        [DataMember(Name = "constellation_id")]
        public ushort ConstellationId;
        [DataMember(Name = "region_commit")]
        public string RegionCommit;
        [DataMember(Name = "visible_stars")]
        public byte VisibleStars;
        [DataMember(Name = "nonce")]
        public ulong Nonce;
        [DataMember(Name = "deadline")]
        public ulong Deadline;
        [DataMember(Name = "signature")]
        public string Signature;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public TraceAttestation(
            ulong IntentId,
            SpacetimeDB.Identity Trader,
            ushort ConstellationId,
            string RegionCommit,
            byte VisibleStars,
            ulong Nonce,
            ulong Deadline,
            string Signature,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.IntentId = IntentId;
            this.Trader = Trader;
            this.ConstellationId = ConstellationId;
            this.RegionCommit = RegionCommit;
            this.VisibleStars = VisibleStars;
            this.Nonce = Nonce;
            this.Deadline = Deadline;
            this.Signature = Signature;
            this.CreatedAt = CreatedAt;
        }

        public TraceAttestation()
        {
            this.RegionCommit = "";
            this.Signature = "";
        }
    }
}
