// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TraceIntent
    {
        [DataMember(Name = "intent_id")]
        public ulong IntentId;
        [DataMember(Name = "trader")]
        public SpacetimeDB.Identity Trader;
        [DataMember(Name = "evm_address")]
        public string EvmAddress;
        [DataMember(Name = "constellation_id")]
        public ushort ConstellationId;
        [DataMember(Name = "visible_stars")]
        public ushort VisibleStars;
        [DataMember(Name = "attested")]
        public bool Attested;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public TraceIntent(
            ulong IntentId,
            SpacetimeDB.Identity Trader,
            string EvmAddress,
            ushort ConstellationId,
            ushort VisibleStars,
            bool Attested,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.IntentId = IntentId;
            this.Trader = Trader;
            this.EvmAddress = EvmAddress;
            this.ConstellationId = ConstellationId;
            this.VisibleStars = VisibleStars;
            this.Attested = Attested;
            this.CreatedAt = CreatedAt;
        }

        public TraceIntent()
        {
            this.EvmAddress = "";
        }
    }
}
