// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Trade
    {
        [DataMember(Name = "trade_id")]
        public ulong TradeId;
        [DataMember(Name = "proposer")]
        public SpacetimeDB.Identity Proposer;
        [DataMember(Name = "partner")]
        public SpacetimeDB.Identity Partner;
        [DataMember(Name = "offer")]
        public System.Collections.Generic.List<ulong> Offer;
        [DataMember(Name = "request")]
        public System.Collections.Generic.List<ulong> Request;
        [DataMember(Name = "proposer_ok")]
        public bool ProposerOk;
        [DataMember(Name = "partner_ok")]
        public bool PartnerOk;
        [DataMember(Name = "state")]
        public TradeState State;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public Trade(
            ulong TradeId,
            SpacetimeDB.Identity Proposer,
            SpacetimeDB.Identity Partner,
            System.Collections.Generic.List<ulong> Offer,
            System.Collections.Generic.List<ulong> Request,
            bool ProposerOk,
            bool PartnerOk,
            TradeState State,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.TradeId = TradeId;
            this.Proposer = Proposer;
            this.Partner = Partner;
            this.Offer = Offer;
            this.Request = Request;
            this.ProposerOk = ProposerOk;
            this.PartnerOk = PartnerOk;
            this.State = State;
            this.CreatedAt = CreatedAt;
            this.UpdatedAt = UpdatedAt;
        }

        public Trade()
        {
            this.Offer = new();
            this.Request = new();
        }
    }
}
