// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VerifiedSolanaWallet
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "solana_pubkey")]
        public string SolanaPubkey;
        [DataMember(Name = "proof_hash")]
        public string ProofHash;
        [DataMember(Name = "verified_at")]
        public SpacetimeDB.Timestamp VerifiedAt;

        public VerifiedSolanaWallet(
            SpacetimeDB.Identity Identity,
            string SolanaPubkey,
            string ProofHash,
            SpacetimeDB.Timestamp VerifiedAt
        )
        {
            this.Identity = Identity;
            this.SolanaPubkey = SolanaPubkey;
            this.ProofHash = ProofHash;
            this.VerifiedAt = VerifiedAt;
        }

        public VerifiedSolanaWallet()
        {
            this.SolanaPubkey = "";
            this.ProofHash = "";
        }
    }
}
