// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class VerifiedEvmWallet
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "evm_address")]
        public string EvmAddress;
        [DataMember(Name = "proof_hash")]
        public string ProofHash;
        [DataMember(Name = "verified_at")]
        public SpacetimeDB.Timestamp VerifiedAt;

        public VerifiedEvmWallet(
            SpacetimeDB.Identity Identity,
            string EvmAddress,
            string ProofHash,
            SpacetimeDB.Timestamp VerifiedAt
        )
        {
            this.Identity = Identity;
            this.EvmAddress = EvmAddress;
            this.ProofHash = ProofHash;
            this.VerifiedAt = VerifiedAt;
        }

        public VerifiedEvmWallet()
        {
            this.EvmAddress = "";
            this.ProofHash = "";
        }
    }
}
