// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WordRate
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "last_at")]
        public SpacetimeDB.Timestamp LastAt;
        [DataMember(Name = "plays")]
        public uint Plays;

        public WordRate(
            SpacetimeDB.Identity Identity,
            SpacetimeDB.Timestamp LastAt,
            uint Plays
        )
        {
            this.Identity = Identity;
            this.LastAt = LastAt;
            this.Plays = Plays;
        }

        public WordRate()
        {
        }
    }
}
