// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WordDuel
    {
        [DataMember(Name = "duel_id")]
        public ulong DuelId;
        [DataMember(Name = "player")]
        public SpacetimeDB.Identity Player;
        [DataMember(Name = "opponent")]
        public Planet Opponent;
        [DataMember(Name = "player_word")]
        public string PlayerWord;
        [DataMember(Name = "player_score")]
        public uint PlayerScore;
        [DataMember(Name = "agent_word")]
        public string AgentWord;
        [DataMember(Name = "agent_score")]
        public uint AgentScore;
        [DataMember(Name = "won")]
        public bool Won;
        [DataMember(Name = "tokens_awarded")]
        public ulong TokensAwarded;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public WordDuel(
            ulong DuelId,
            SpacetimeDB.Identity Player,
            Planet Opponent,
            string PlayerWord,
            uint PlayerScore,
            string AgentWord,
            uint AgentScore,
            bool Won,
            ulong TokensAwarded,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.DuelId = DuelId;
            this.Player = Player;
            this.Opponent = Opponent;
            this.PlayerWord = PlayerWord;
            this.PlayerScore = PlayerScore;
            this.AgentWord = AgentWord;
            this.AgentScore = AgentScore;
            this.Won = Won;
            this.TokensAwarded = TokensAwarded;
            this.CreatedAt = CreatedAt;
        }

        public WordDuel()
        {
            this.PlayerWord = "";
            this.AgentWord = "";
        }
    }
}
