// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Zone
    {
        [DataMember(Name = "zone_id")]
        public byte ZoneId;
        [DataMember(Name = "kind")]
        public ZoneKind Kind;
        [DataMember(Name = "owner")]
        public Planet? Owner;
        [DataMember(Name = "control")]
        public int Control;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public Zone(
            byte ZoneId,
            ZoneKind Kind,
            Planet? Owner,
            int Control,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.ZoneId = ZoneId;
            this.Kind = Kind;
            this.Owner = Owner;
            this.Control = Control;
            this.UpdatedAt = UpdatedAt;
        }

        public Zone()
        {
        }
    }
}
